Working GNU and Berkeley UPC with SMP conduit.
Changed all instances of GNU_UPC to GUPC to match GNU branding.


Former-commit-id: c52bdd83e608c197c4e7990927dfb5be07ebce94

diff --git a/src/wrappers/upc/gupc/tau_upc_wrapper b/src/wrappers/upc/gupc/tau_upc_wrapper
--- a/src/wrappers/upc/gupc/tau_upc_wrapper
+++ b/src/wrappers/upc/gupc/tau_upc_wrapper
@@ -14,13 +14,13 @@ usage()
     echo " -upc=<dir> : specifies the upc directory"
     echo "NOTE: $cmd reads the TAU_MAKEFILE  environment variable to get PDT settings"
     echo " Example: "
-    echo " % $cmd tau_upcr.h -lm -gasnet=/usr/local/packages/gasnet-1.18.0-mpi-smp -gasnetconduit=mpi -upc=/usr/local/packages/bupc-2.14.2/opt_inst"
+    echo " % $cmd tau_upcr.h -lm -gasnet=/usr/local/packages/gasnet-1.18.0 -gasnetconduit=mpi -upc=/usr/local/packages/gupc-4.7.0.2"
     echo " generates a wrapper library that may be linked in using TAU_OPTIONS -optTauWrapFile=<wrapperdir>/link_options.tau"
     echo "" 
     exit 1
 }
 
-upcdir=/usr/local/packages/bupc/opt_inst
+upcdir=/usr/local/packages/gupc
 gasnetdir=/usr/local/packages/gasnet
 gasnetconduit=mpi
 runtime_specified=0;
@@ -35,31 +35,31 @@ fi
 if [ $# -gt 1 ]; then
   headerfile=$1
   library=$2
-  shift
-  shift
+  shift;
+  shift;
 fi
 
 for arg in "$@"; do
   case $arg in 
     -r)
       runtime_specified=1; 
-      shift
+      shift; 
       ;;
     -d)
       header_redirection_specified=1; 
-      shift
+      shift; 
       ;;
     -gasnet=*)
       gasnetdir=`echo $arg | sed -e 's/-gasnet=//g'`
-      shift
+      shift;
       ;;
     -gasnetconduit=*)
       gasnetconduit="`echo $arg | sed -e 's/-gasnetconduit=//g'`-conduit"
-      shift
+      shift;
       ;;
     -upc=*)
       upcdir=`echo $arg | sed -e 's/-upc=//g'`
-      shift
+      shift;
       ;;
   esac
 done
@@ -100,9 +100,8 @@ if [ ! -x $parser ]; then
 fi
 baseheader=`basename $headerfile .h`
 
-# Parse the header file to create pdb file
 echo $parser $headerfile -DGASNET_SEQ -I$upcdir/include -DUPCRI_BUILDING_LIBUPCR=1 -I$gasnetdir/include -I$gasnetdir/include/$gasnetconduit -DGASNETT_USE_GCC_ATTRIBUTE_MAYALIAS
-$parser $headerfile -DGASNET_SEQ -I$upcdir/include -DUPCRI_BUILDING_LIBUPCR=1 -I$gasnetdir/include -I$gasnetdir/include/$gasnetconduit -DGASNETT_USE_GCC_ATTRIBUTE_MAYALIAS
+$parser $headerfile -DGASNET_SEQ -I$upcdir/include -I$gasnetdir/include -I$gasnetdir/include/$gasnetconduit -DGASNETT_USE_GCC_ATTRIBUTE_MAYALIAS
 mv $baseheader.pdb $headerfile.pdb 
 
 if [ $runtime_specified = 1 ] ; then
@@ -115,36 +114,47 @@ else
   fi
 fi
 
+
+# Locate libgupc.a
+if [ -r "$upcdir/lib64/libgupc.a" ] ; then
+  libgupc="$upcdir/lib64/libgupc.a"
+elif [ -r "$upcdir/lib/libgupc.a" ] ; then
+  libgupc="$upcdir/lib/libgupc.a"
+else
+  echo "ERROR: Cannot locate libgupc.a in $upcdir"
+  exit 1
+fi
+
 # Generate select.tau
 echo "BEGIN_INCLUDE_LIST" > select.tau
-for sym in _upcr UPCRL upcr _bupc_ ; do
-  nm -A $upcdir/lib/*.a | grep " $sym" | awk '{ print $3;}' | sed -e "s/$sym/\"# $sym/g" -e 's/$/(#"/g' >> select.tau
+for sym in _upc upc upcr ; do
+  nm -A $libgupc | grep " $sym" | awk '{ print $3;}' | sed -e "s/$sym/\"# $sym/g" -e 's/$/(#"/g' >> select.tau
 done
 echo "END_INCLUDE_LIST" >> select.tau
 
 # Generate wr.c
-echo $basedir/bin/tau_wrap $headerfile.pdb $headerfile -o wr.c $runtimeopt $library $* -f select.tau --upc berkeley
-$basedir/bin/tau_wrap $headerfile.pdb $headerfile -o wr.c $runtimeopt $library $* -f select.tau --upc berkeley
-headerbase=`basename $headerfile .h`
-dirname="${headerbase}_wrapper"
-libname="lib${headerbase}_wrap.a"
+echo $basedir/bin/tau_wrap $headerfile.pdb $headerfile -o wr.c $runtimeopt $library $* -f select.tau --upc gnu
+$basedir/bin/tau_wrap $headerfile.pdb $headerfile -o wr.c $runtimeopt $library $* -f select.tau --upc gnu
+dirname=`basename ${headerfile} .h`_wrapper
 
-# replace bupc_smemvec_t [] a with bupc_smemvec_t * a
-sed -e 's/\[\]/\*/g' ${dirname}/wr.c > ${dirname}/wr.c~
-mv ${dirname}/wr.c~ ${dirname}/wr.c 
+# Fix the Makefile with the correct smp args.
+sed -e "s@^EXTRA_FLAGS=@EXTRA_FLAGS=-DGASNET_SEQ -I$upcdir/include -I$gasnetdir/include -I$gasnetdir/include/$gasnetconduit -DGASNETT_USE_GCC_ATTRIBUTE_MAYALIAS @g" $dirname/Makefile > $dirname/Makefile~
+mv -f $dirname/Makefile~ $dirname/Makefile
 
-# Add correct paths and arguments to Makefile
-sed -e "s@^EXTRA_FLAGS=@EXTRA_FLAGS=-DGASNET_SEQ -I$upcdir/include -DUPCRI_BUILDING_LIBUPCR=1 -I$gasnetdir/include -I$gasnetdir/include/$gasnetconduit -DGASNETT_USE_GCC_ATTRIBUTE_MAYALIAS@" $dirname/Makefile.master > $dirname/Makefile
+# Add the library to the link options
+# GNU UPC can't link static archives of UPC code as of Aug. 2012.
+# Link the object file directly.
+sed -e "s@WRAPPER_LIBRARY@$basedir/lib/wrappers/upc/gupc/tau_gupc_wrap.o@" $dirname/link_options.tau.master > $dirname/link_options.tau
 
-# Add library to link options
-sed -e "s/@@WRAPPER_LIBRARY@@/-l${headerbase}_wrap/" $dirname/link_options.tau.master > $dirname/link_options.tau
-
+# Build and install
 cd $dirname
 make
 cd ..
-rm -f ${headerfile}.pdb 
-mkdir -p $basedir/lib/wrappers/upc/bupc
-echo cp $dirname/link_options.tau $basedir/lib/wrappers/upc/bupc
-cp $dirname/link_options.tau $basedir/lib/wrappers/upc/bupc
-echo cp $dirname/$libname $basedir/lib/
-cp $dirname/$libname $basedir/lib/
+rm -f ${headerfile}.pdb
+mkdir -p $basedir/lib/wrappers/upc/gupc
+echo cp $dirname/link_options.tau $basedir/lib/wrappers/upc/gupc
+cp $dirname/link_options.tau $basedir/lib/wrappers/upc/gupc
+echo cp $dirname/tau_gupc_wrap.o $basedir/lib/wrappers/upc/gupc
+cp $dirname/tau_gupc_wrap.o $basedir/lib/wrappers/upc/gupc
+echo cp $dirname/libtau_gupc_wrap.a $basedir/lib/
+cp $dirname/libtau_gupc_wrap.a $basedir/lib/
