Added -slog2=<dir> option to configure. We check javac to set JDKDIR in include/Makefile (JAVA option is not enabled. That happens when the user explicitly calls -jdk=<dir> ). SLOG2DIR points to the location of SLOG2 directory.
git-svn-id: file:///mnt/fast/tau2git/svnroot/trunk/tau2@3074 a8e31b63-e6ca-409b-a01b-2eec1b506579

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -198,6 +198,7 @@ tauoptions=
 pdt_root_dir="."
 pdt=no
 vtf=no
+slog2=no
 opari=no
 epilog=no
 opari_region=no
@@ -505,6 +506,19 @@ do
       fi
     shift
     ;;
+
+  -slog2=*)
+      slog2=yes
+      trace=yes
+      slog2dir=`echo $arg | sed -e 's/-slog2=//'`
+      if [ ! -d $slog2dir ]
+      then
+        echo "Error: Cannot access SLOG2 directory $slog2dir"
+        exit 1
+      fi
+    shift
+    ;;
+
 
   -pcxxopt=*)
     pcxxopt=`echo $arg | sed -e 's/-pcxxopt=//' -e 's/ /_/g'`
@@ -2967,6 +2981,17 @@ fi
 if [ $vtf = yes ]
 then
   fixmakeargs="$fixmakeargs VTF vtfdir=$vtfdir"
+fi
+
+if [ $slog2 = yes ]
+then
+  fixmakeargs="$fixmakeargs SLOG2 slog2dir=$slog2dir"
+  jdkdir=`which javac | sed s/javac/../`
+  if [ "x$jdkdir" = "x" ]
+  then
+    echo "You need javac in your path while using SLOG2. Please re-configure TAU."
+  fi
+  fixmakeargs="$fixmakeargs jdkdir=$jdkdir"
 fi
 
 if [ $pdt = yes ]
