If the installation prefix doesn't exist, terminate early.
Former-commit-id: 8a2f98496e6c45204197aa14907ebf81320e1437

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2613,6 +2613,13 @@ for arg in "$@"; do
 	-prefix=*)
 	    tauprefix=`echo $arg | sed -e 's/-prefix=//' -e 's/ /_/g'`
 	    fixmakeargs="$fixmakeargs tauprefix=$tauprefix"
+        echo "Testing directory $tauprefix "
+        mkdir -p ${tauprefix}
+        rc=$?
+        if [ $rc -ne 0 ] ; then
+            echo "Failed to create installation directory: ${tauprefix}"
+            exit $rc
+        fi
 	    shift
 	    ;;
 
