Check if both -ompt=<download> and -opari are defined. Do not allow this for now.
Former-commit-id: b670f677079332ba10f5f72b2bca91dd5a012bdd

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -7212,6 +7212,11 @@ else
   fi
 fi
 
+if [ $ompt = yes -a $opari = yes ] ; then
+  echo "ERROR: Please enable either OMPT or Opari for instrumentation, but not both"
+  exit 1
+fi 
+
 # GOMP wrapping is only available for openmp
 if [ $openmp = yes ] ; then
     # GOMP wrapping is only available for GCC
