Fix failed pythonlib detection causing bindings dir without tags.
Former-commit-id: b71dc145d53ee856809b5f1611eb6227e30b3092

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2232,10 +2232,15 @@ if [ "x$python"  = "xyes" ] ; then
     fi
   fi
   if [ "x$pythonlib" = "x" ] ; then
-    pythonlib=`echo ${pythonbin}../lib/python* | sed -e 's/ .*//g'`
+    for libdir in "lib" "lib32" "lib64" ; do
+      pythonlib=`echo ${pythonbin}../${libdir}/python* | sed -e 's/ .*//g'`
+      if [ -d "$pythonlib" ] ; then
+        break
+      fi
+    done
     if [ ! -d $pythonlib ] ; then
-        echo "Error: Cannot access Python lib directory $pythonlib"
-        exit 1
+      echo "Error: Cannot access Python lib directory $pythonlib"
+      exit 1
     fi
   fi
 fi
@@ -9433,6 +9438,11 @@ echo $fixmakeargs >> ./utils/FixMakefile.info
 
 # Now FINALLY FixMakefile with the string I have built
 utils/FixMakefile $fixmakeargs
+retval=$?
+if [ $retval -ne 0 ] ; then
+  echo "ERROR: One or more TAU components could not be configured. Please check above for error messages"
+  exit $retval
+fi
 
 # Use default setups, forget everything else (PHB)
 if [ $machine = default ] ; then
diff --git a/utils/FixMakefile b/utils/FixMakefile
--- a/utils/FixMakefile
+++ b/utils/FixMakefile
@@ -465,17 +465,31 @@ case $1 in
      pythonlib=*)
         pythonlib=`echo $1 | sed -e 's/^pythonlib=//'`
 	# Discover python library version
-	pythonso=`ls $pythonlib/libpython*.so 2>/dev/null | head -1 | xargs basename | sed -e 's/lib//' -e 's/\.so//'`
-	if [ "x$pythonso" = "x" ] ; then
-	  pythonso=`ls $pythonlib/libpython*.dylib 2>/dev/null | head -1 | xargs basename | sed -e 's/lib//' -e 's/\.dylib//'`
-	  if [ "x$pythonso" = "x" ] ; then
-	    echo "ERROR: Cannot find python library (libpython*.[so|dylib]"
-	    exit 1
-	  fi
+	for subdir in "" ".." "python*" ; do
+          for ext in "so" "dylib" ; do
+            _checkpath="${pythonlib}/${subdir}/libpython*.${ext}"
+            echo "Checking ${_checkpath}"
+  	    pythonso=`ls ${_checkpath} 2>/dev/null | head -1`
+            if [ "x$pythonso" == "x" ] ; then
+              continue
+            fi
+            pythonlib=`dirname $pythonso`
+            pythonso=`echo $pythonso | xargs basename | sed -e "s#lib##" -e "s#\.${ext}##"`
+            if [ "x$pythonso" != "x" ] ; then
+              # Break out of both loops
+              break 2
+            fi
+          done
+        done
+	pythonlib_full="$pythonlib/lib$pythonso.$ext"
+	if [ ! -f "$pythonlib_full" ] ; then
+	  echo "ERROR: Cannot find python library (libpython*.[so|dylib]"
+	  exit 1
+        else
+          echo "Found Python library: $pythonlib_full"
 	fi
 	echo "s,^PYTHON_LIBDIR=.*$,PYTHON_LIBDIR=$pythonlib,g" >> $sedout
 	echo "s,^PYTHON_LIB_SO=.*$,PYTHON_LIB_SO=$pythonso,g" >> $sedout
-	#echo "Using PYTHON LIB DIR =" $pythonlib
 	;;
 
      stffdir=*)
