Updated apex submodule. Added options zerosum= and apex= , where a path to their installation can be added to use them. tau_exec can use -apex and -zerosum tau_exec will check if we are using mpi or not to select which libzerosum version it should use. In the case of APEX, there are still some issues to resolve and only the base libapex.so is used.
Former-commit-id: c0fdcfcee27ee571f3ed4d57edd4fc0e89d31f46

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -917,7 +917,9 @@ for arg in "$@"; do
         echo "-asmdex=<dir | download> ...... Specify a asmdex directory or download."
         echo "-boost=<dir> ....................... Specify location of Boost package."
         echo "-apex ......................................... Build the APEX package."
+        echo "-apex=<dir> ,,,...................... Specify location of APEX package."
         echo "-zerosum ................................... Build the ZeroSum package."
+        echo "-zerosum=<dir> ................... Specify location of ZeroSum package."
         echo "-sycl=<dir> ..................................... Path to SYCL include."
         echo "-mochi ............................ Add MOCHI backend database support."
         echo "-dyninst=<dir> ................... Specify location of DynInst package."
@@ -1497,6 +1499,8 @@ nccl_lib=""
 nccl_inc=""
 l0_lib_dir=""
 l0_iga_lib=""
+zerosumlib="@ZEROSUM_LIB_DIR@"
+apexlib="@APEX_LIB_DIR@"
 restore_perfdmf_and_paraprof
 
 handle_python_option() {
@@ -2382,9 +2386,31 @@ for arg in "$@"; do
             apex=yes
             shift
             ;;
+        
+        -apex=*)
+            apex_root_path=`echo $arg | sed -e 's/-apex=//'`
+            if [ ! -d ${apex_root_path}/lib ]
+            then
+                echo "Error: Cannot access APEX directory ${apex_root_path}/lib"
+                exit 1
+            fi
+            apexlib=${apex_root_path}/lib
+            shift
+            ;;
 
         -zerosum)
             zerosum=yes
+            shift
+            ;;
+        
+        -zerosum=*)
+            zerosum_root_path=`echo $arg | sed -e 's/-zerosum=//'`
+            if [ ! -d ${zerosum_root_path}/lib ]
+            then
+                echo "Error: Cannot access ZeroSum directory ${zerosum_root_path}/lib"
+                exit 1
+            fi
+            zerosumlib=${zerosum_root_path}/lib
             shift
             ;;
         
@@ -12094,9 +12120,12 @@ build_apex() {
     fi
     echo "TAUOPENCL=-DAPEX_WITH_OPENCL=TRUE" >> ${apex_include_file}
     cp etc/Makefile.apex apex/Makefile
-    fixmakeargs="$fixmakeargs APEX "
+    fixmakeargs="$fixmakeargs APEX"
     make -C apex clean
     make -C apex
+    apexlib=${targetdir}/${architecture}/lib/
+    sed -i "/@APEX_LIB_DIR@/ s,@APEX_LIB_DIR@,${apexlib},g" \
+        "${targetdir}/${architecture}/bin/tau-config"
 }
 
 build_zerosum() {
@@ -12141,9 +12170,13 @@ build_zerosum() {
         echo "TAUMPI=-DZeroSum_WITH_MPI=FALSE" >> ${zerosum_include_file}
     fi
     cp etc/Makefile.zerosum zerosum/Makefile
-    fixmakeargs="$fixmakeargs ZeroSum "
+    fixmakeargs="$fixmakeargs ZeroSum"
     make -C zerosum clean
     make -C zerosum
+    zerosumlib=${targetdir}/${architecture}/lib/
+    sed -i "/@ZEROSUM_LIB_DIR@/ s,@ZEROSUM_LIB_DIR@,${zerosumlib},g" \
+        "${targetdir}/${architecture}/bin/tau-config"
+         
 }
 
 build_perfstubs() {
@@ -14054,6 +14087,7 @@ cp ${tauroot}/tools/src/tau2slog2/bin/tau2slog2.jar ${targetdir}/${architecture}
 
 cat ${tauroot}/tools/src/tau-config.in |
 sed -e 's,@TAUROOTDIR@,'$targetdir',' -e 's,@SHELL@,'$taushell',' -e 's,@ARCH@,'$architecture',' -e 's,@PYTHONINTV@,'$pythonintv',' \
+    -e 's,@APEX_LIB_DIR@,'$apexlib','  -e 's,@ZEROSUM_LIB_DIR@,'$zerosumlib',' \
     > ${targetdir}/${architecture}/bin/tau-config
 chmod a+rx ${targetdir}/${architecture}/bin/tau-config
 
