Added support for specifying the location of the Intel OpenMP library with OMPT support.
-omptlib=/home3/khuck/src/intel-openmp-rtl/branches/ompt-support/itt/libomp_oss/tmp/lin_32e-rtl_5_nor_dyn.12.deb.40.c0.t0-hn1/libiomp5.so

...for example. this will split the input into path and filename, and add the following to linking:
-Wl,-rpath=<path> <path>/<library>

This will also enable -ompt, obviously.


Former-commit-id: 1ec4031e79e8328d342b2b200437411f05f446b0

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -779,6 +779,7 @@ dwarf=no
 java=no
 openmp=no
 ompt=no
+omptlib=
 omptenabled=no
 xlsmp=no
 ibmxlc=no
@@ -1485,10 +1486,31 @@ for arg in "$@"; do
       openmp=yes
     shift
     ;;
+
+  -omptlib=*)
+      ompt=yes
+      omptfile=`echo $arg | sed -e 's/-omptlib=//'`
+      if [ ! -f $omptfile ]
+      then
+        echo "Error: Cannot access OpenMP runtime library $omptfile"
+        exit 1
+      fi
+      # split the ompt library path
+      omptdir=${omptfile%/*}
+      if [ ! -d $omptdir ]
+      then
+        echo "Error: Cannot access directory $omptdir"
+        exit 1
+      fi
+      omptlib="-Wl,-rpath=$omptdir#$omptfile"
+    shift
+    ;;
+
   -ompt*)
       ompt=yes
     shift
     ;;
+
   -xlsmp=*)
       xlsmp=yes
       xlsmpdir=`echo $arg | sed -e 's/-xlsmp=//'`
@@ -1972,7 +1994,6 @@ else
     mpi=yes
   fi
 fi
-
 
 # -- some functions
 
@@ -2836,7 +2857,7 @@ if [ "$machine" = "apple" ] ; then
 fi
 
 if [ $ompt = yes ]; then
-  fixmakeargs="$fixmakeargs TAU_OMPT"
+  fixmakeargs="$fixmakeargs TAU_OMPT omptlib=$omptlib"
 fi
 
 if [ $machine = bgq -o $machine = bgp -o $machine = bgl ] ; then
