Pulled the updated configure from the master branch.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -66,6 +66,7 @@ for arg in "$@"; do
     echo "-arch=<architecture> ................... Specify a target architecture."
     echo "       options          [xt3|craycnl|bgp|bgl|ibm64|ibm64linux|sunx86_64"
     echo "                        crayxmt|solaris2-64|mips32|sgin32|sgi64|sgio32]"
+    echo "-bfd=<dir | download> ............ Specify a BFD directory or download."
     echo ""
     echo "MPI Options:"
     echo "-mpi .......................... Specify use of TAU MPI wrapper library."
@@ -108,7 +109,14 @@ for arg in "$@"; do
     echo "-epilogbin=<dir> ........... Specify full path to EPILOG bin directory."
     echo "-epiloginc=<dir> ....... Specify full path to EPILOG include directory."
     echo "-vampirtrace=<dir>  .. Specify location of VampirTrace Tracing package."
-    echo "-scorep=<dir>  ........................ Specify location of SCOREP package."
+    echo "-mon-mpi ..... Specify MPI as TAU monitoring transport layer.          "
+    echo "-mon-mrnet=<dir> .. Specify location to MRNet package as TAU monitoring"
+    echo "                    transport layer (ToM).                             "
+    echo "-mon-mrnet-lib=<dir> ............... Specify full path to MRNet library"
+    echo "                                     installation.                     "
+    echo "-mon-mrnet-use-lightweight ..... Instructs ToM to use MRNet lightweight"
+    echo "                                 interface.                            "
+    echo "-scorep=<dir>  .................... Specify location of SCOREP package."
     echo "-python .. Automatically choose python options based on Python in path."
     echo "-pythoninc=<dir> ........ Specify location of Python include directory."
     echo "-pythonlib=<dir> ............ Specify location of Python lib directory."
@@ -182,6 +190,7 @@ for arg in "$@"; do
     echo "-jdk=<dir>  Build a library for profiling Java code with specified jdk."
     echo "-dyninst=<dir> ................... Specify location of DynInst Package."
     echo "-dwarf=<dir> ................ Specify location of the libdwarf Package."
+    echo "-bfd=<dir | download> ............ Specify a BFD directory or download."
     echo "-vtf=<dir> ......... Specify location of VTF3 Trace Generation Package."
     echo "-otf=<dir> ....... Specify location of Open Trace Format (OTF) Package."
     echo "-mpi .......................... Specify use of TAU MPI wrapper library."
@@ -207,7 +216,14 @@ for arg in "$@"; do
     echo "-epilogbin=<dir> ........... Specify full path to EPILOG bin directory."
     echo "-epiloginc=<dir> ....... Specify full path to EPILOG include directory."
     echo "-vampirtrace=<dir>  .. Specify location of VampirTrace Tracing package."
-    echo "-scorep=<dir>  ........................ Specify location of SCOREP package."
+    echo "-mon-mpi ..... Specify MPI as TAU monitoring transport layer.          "
+    echo "-mon-mrnet=<dir> .. Specify location to MRNet package as TAU monitoring"
+    echo "                    transport layer (ToM).                             "
+    echo "-mon-mrnet-lib=<dir> ............... Specify full path to MRNet library"
+    echo "                                     installation.                     "
+    echo "-mon-mrnet-use-lightweight ..... Instructs ToM to use MRNet lightweight"
+    echo "                                 interface.                            "
+    echo "-scorep=<dir>  .................... Specify location of SCOREP package."
     echo "-upcnetwork=<value> .. Specify network (mpi, udp,...) for Berkeley UPC."
     echo "-python .. Automatically choose python options based on Python in path."
     echo "-pythoninc=<dir> ........ Specify location of Python include directory."
@@ -313,6 +329,7 @@ pdt_cxx_compiler=default
 fixmakeargs=""
 useropt=-g#-O2
 tag=no
+pathscale=no
 tautag=
 orig_useropt="-g -O2"
 mpi=no
@@ -321,6 +338,7 @@ mpiio=no
 mpiinc=
 mpilib=
 mpilibrary=no
+mon_mpi=no
 mrnet=no
 mrnet_use_lightweight=no
 mrnet_root=
@@ -404,6 +422,7 @@ tautoplevel=
 tauoptions=
 pdt_root_dir="."
 pdt=no
+armci=no
 vtf=no
 otf=no
 opari=no
@@ -458,6 +477,7 @@ for i in include/Makefile ; do
     sed -f utils/FixMakefile.sed.default < ${i} > ${i}~~0
     mv ${i}~~0 ${i}
 done
+
 
 ###############################################################
 # PARSE OPTIONS
@@ -678,9 +698,14 @@ for arg in "$@"; do
     shift
     ;;
 
-  -mrnet=*)
+  -mon-mpi)
+    mon_mpi=yes
+    shift
+    ;;
+
+  -mon-mrnet=*)
     mrnet=yes
-    mrnet_root=`echo $arg | sed -e 's/-mrnet=//' -e 's/ /#/g'`
+    mrnet_root=`echo $arg | sed -e 's/-mon-mrnet=//' -e 's/ /#/g'`
     if [ ! -e $mrnet_root ]
     then
       echo "Error: Cannot access MRNet root directory $mrnet_root"
@@ -689,9 +714,9 @@ for arg in "$@"; do
     shift
     ;;
 
-  -mrnetlib=*)
+  -mon-mrnet-lib=*)
     mrnet=yes
-    mrnet_lib=`echo $arg | sed -e 's/-mrnetlib=//' -e 's/ /#/g'`
+    mrnet_lib=`echo $arg | sed -e 's/-mon-mrnet-lib=//' -e 's/ /#/g'`
     if [ ! -e $mrnet_lib ]
     then
       echo "Error: Cannot access MRNet library directory $mrnet_lib"
@@ -700,7 +725,7 @@ for arg in "$@"; do
     shift
     ;;
 
-  -mrnet_use_lightweight)
+  -mon-mrnet-use-lightweight)
     mrnet_use_lightweight=yes
     shift
     ;;
@@ -896,6 +921,16 @@ for arg in "$@"; do
       shift
       ;;
 
+  -armci=*)
+      armci=yes
+      armcidir=`echo $arg | sed -e 's/-armci=//'`
+      if [ ! -d $armcidir ] ; then
+          echo "Error: Cannot access ARMCI directory $armcidir"
+          exit 1
+      fi
+      shift
+      ;;
+
   -vtf=*)
       vtf=yes
       trace=yes
@@ -956,11 +991,18 @@ for arg in "$@"; do
         exit 1
       fi 
       jv=`$jdkdir/bin/java -version 2>&1 | grep version | awk '{ print $3; }'| sed -e s/\"//g`
-    if [ `echo $jv | sed -e s/1.6\.*// | wc -c` -eq 1 ] || [ `echo $jv | sed -e s/1.7\.*// | wc -c` -eq 1 ]
-    then
-        echo "Error: Specify a JDK of version 1.5 or earlier"
-        exit 1
-    fi
+      eval major=${jv/./;minor=}
+      minor=`echo $minor | sed 's/\([0-9]*\).*/\1/g'`
+      echo "major = $major, minor = $minor"
+      if [ $major = 1 ]
+      then
+        if [ $minor -lt 5 ]
+        then
+          echo "Error: Specify a JDK of version 1.5 or later"
+          exit 1
+        fi
+      fi
+
     shift
     ;;
 
@@ -993,9 +1035,9 @@ for arg in "$@"; do
  
   -useropt=*)
 # Note you might be passed -g#-O3 which becomes -g -O3
-    orig_useropt=`echo $arg | sed -e 's/-useropt=//' -e 's/#/ /g'`
+    orig_useropt="$orig_useropt "`echo $arg | sed -e 's/-useropt=//' -e 's/#/ /g'`
 # Note you might be passed -g -O3 which becomes -g#-O3 here
-    useropt=`echo $arg | sed -e 's/-useropt=//' -e 's/ /#/g'`
+    useropt="$useropt#"`echo $arg | sed -e 's/-useropt=//' -e 's/ /#/g'`
     shift
     ;;
 
@@ -1308,16 +1350,17 @@ for arg in "$@"; do
     shift
     ;;
 
-  -cudainc=*)
-    cudainclude=`echo $arg | sed -e 's/-cudainc=//' -e 's/ /#/g'`
+  -cuda=*)
+    cudainclude=`echo $arg | sed -e 's/-cuda=//' -e 's/ /#/g'`/include
     if [ ! -d $cudainclude ] ; then
       echo "Error: Cannot access GPU include directory $cudainclude"
       exit 1
     fi
     if [ -f "$cudainclude/cuda.h" ] ; then
-    	fixmakeargs="$fixmakeargs cudainclude=$cudainclude useropt=-DTAU_MAX_THREADS=3"
+			useropt="$useropt#-DTAU_MAX_THREADS=3"
+    	fixmakeargs="$fixmakeargs cudainclude=$cudainclude"
 			if [ -f "$cudainclude/CL/cl.h" ] ; then
-    		fixmakeargs="$fixmakeargs cudainclude=$cudainclude openclinclude=$cudainclude useropt=-DTAU_MAX_THREADS=3"
+    		fixmakeargs="$fixmakeargs openclinclude=$cudainclude"
 			fi
 		else
 			echo "Error: Cannot find GPU headers, TAU currently supports either CUDA or OpenCL"
@@ -1325,14 +1368,15 @@ for arg in "$@"; do
     shift
     ;;
 
-  -openclinc=*)
-    openclinclude=`echo $arg | sed -e 's/-openclinc=//' -e 's/ /#/g'`
+  -opencl=*)
+    openclinclude=`echo $arg | sed -e 's/-opencl=//' -e 's/ /#/g'`/include
     if [ ! -d $openclinclude ] ; then
       echo "Error: Cannot access GPU include directory $openclinclude"
       exit 1
     fi
 		if [ -f "$openclinclude/CL/cl.h" ] ; then
-      fixmakeargs="$fixmakeargs openclinclude=$openclinclude useropt=-DTAU_MAX_THREADS=3"
+			useropt="$useropt#-DTAU_MAX_THREADS=3"
+      fixmakeargs="$fixmakeargs openclinclude=$openclinclude"
 		else
 			echo "Error: Cannot find GPU headers, TAU currently supports either CUDA or OpenCL"
     fi
@@ -1351,6 +1395,18 @@ for arg in "$@"; do
 			echo "Error: Cannot find CUPTI headers."
     fi
     shift
+    ;;
+	default)
+    echo "Fixing Makefiles"
+    ;;	
+  '')
+    #echo "NULL switch!"
+    # Required for HP/Compaq Tru64 machines.
+    ;;
+  *)
+    echo "ERROR: Command line switch \`$arg' not recognized" 1>&2
+    echo "Run configure with -help to see a list of options" 1>&2
+    exit 1
     ;;
 	default)
     echo "Fixing Makefiles"
@@ -1438,6 +1494,15 @@ sed -e 's,@TAUROOTDIR@,'$targetdir',' \
 -e 's,@TARGETDIR@,'$targetdir',' \
  > ${targetdir}/${architecture}/bin/perfexplorer_configure
 chmod a+rx ${targetdir}/${architecture}/bin/perfexplorer_configure
+
+cat ${tauroot}/tools/src/java-1.4/configure-1.4.skel | 
+sed -e 's,@TAUROOTDIR@,'$targetdir',' \
+-e 's,@SHELL@,'$taushell',' \
+-e 's,@ARCH@,'$architecture',' \
+-e 's,@TARGETDIR@,'$targetdir',' \
+ > ${targetdir}/${architecture}/bin/configure-1.4
+chmod a+rx ${targetdir}/${architecture}/bin/configure-1.4
+
 
 if [ ! -d ${targetdir}/etc ] ; then
     mkdir -p ${targetdir}/etc
@@ -1970,6 +2035,7 @@ case $machine in
 	elif [ "x$PE_ENV" = xPATHSCALE ] ; then
 	    tauoptions="${tauoptions}-pathscale"
 	    default_fortran=pathscale
+            pathscale=yes
 	    fixmakeargs="$fixmakeargs COMPINST_GNU"
 	fi
 	if [ $fortran_compiler = no ] ; then
@@ -2000,7 +2066,8 @@ case $machine in
 	elif [ "x$PE_ENV" = xPATHSCALE ] ; then
 	    tauoptions="${tauoptions}-pathscale"
 	    default_fortran=pathscale
-	    fixmakeargs="$fixmakeargs COMPINST_GNU"
+            pathscale=yes
+	    fixmakeargs="$fixmakeargs COMPINST_GNU USE_PATHCC"
 	elif [ "x$PE_ENV" = xINTEL ] ; then
 	    tauoptions="${tauoptions}-intel"
 	    default_fortran=intel
@@ -2015,7 +2082,7 @@ case $machine in
 	    rm -f conf_test.c
 
 	    # not implemented yet
-#	    fixmakeargs="$fixmakeargs COMPINST_CRAY"
+#	    fixmakeargs="$fixmakeargs COMPINST_CRAYCC"
 	fi
 	if [ $fortran_compiler = no ] ; then
 	    fortran_compiler=$default_fortran
@@ -2702,7 +2769,9 @@ case $fortran_compiler in
           fixmakeargs="$fixmakeargs SC_GFORTRAN"
       else
 	  gfortran=`which gfortran 2>&1`
-	  if [ "x$gfortran" != "x" ] ; then
+          retval=$?
+# when gfortran is not found, it returns a value of 1, otherwise it returns 0. 
+	  if [ "x$gfortran" != "x" -a "x$retval" != "x1" ] ; then
 	      if [ -x $gfortran ] ; then
 		  taugfortranlibdir=`gfortran -print-libgcc-file-name | sed s/libgcc.a//`
 	    fi
@@ -2932,7 +3001,8 @@ then
 	mpiinc=/opt/xt-mpt/default/mpich2-64/P2/include
 	;;
   craycnl)
-	mpiinc=/opt/xt-mpt/default/mpich2-64/P/include
+#	mpiinc=/opt/xt-mpt/default/mpich2-64/P/include
+	mpiinc=$MPICH_DIR/include
         if [ ! -r $mpiinc ] ; then
             if [ $default_fortran = gfortran ] ; then
                 mpiinc=/opt/mpt/$MPT_VERSION/xt/mpich2-gnu/include
@@ -2943,6 +3013,7 @@ then
                 mpiinc=/opt/mpt/default/xt/mpich2-pgi/include
 	    fi
         fi
+        echo "Using MPI INCLUDE dir from $mpiinc"
 	;;
   solaris2*)
 	mpiinc=/opt/SUNWhpc/include
@@ -3043,7 +3114,7 @@ then
 	mpilib=/opt/xt-mpt/default/mpich2-64/P2/lib
 	;;
   craycnl)
-	mpilib=
+	mpilib=$MPICH_DIR/lib
 	;;
   solaris2*)
 	mpilib=/opt/SUNWhpc/lib
@@ -3405,6 +3476,8 @@ fi
 
 ######################################################################
 # Set default compiler options
+
+
 
 
 fixmakeargs="c_compiler=$c_compiler cxx_compiler=$cxx_compiler useropt=$useropt extradir=$extradir extradircxx=$extradircxx extrashlibopts=$extrashlibopts $fixmakeargs"
@@ -4680,7 +4753,12 @@ fi
 if [ $mpi = yes ] ; then
     if [ "x$machine" = "xxt3" -o "x$machine" = "xcraycnl" ] ; then
 	if [ $epilog = no -a $vampirtrace = no ] ; then
+# On Crays, Pathscale compilers require  a -lmpichcxx for C and Fortran
+	  if [ $pathscale = yes ] ; then
+	    mpilibargs="-L$tautoplevel/$machine/lib#-lTauMpi\$(TAU_CONFIG)#-lmpichcxx"
+          else
 	    mpilibargs="-L$tautoplevel/$machine/lib#-lTauMpi\$(TAU_CONFIG)"
+          fi
 	    mpiflibargs=$mpilibargs
 	    fixmakeargs="$fixmakeargs mpilibargs=$mpilibargs mpiflibargs=$mpiflibargs"
 	else
@@ -5192,6 +5270,29 @@ EOF
   /bin/rm -f checkpdt.o checkpdt.cpp
 fi
 
+if [ $armci = yes ]; then
+   cat <<EOF>armcitest.c
+#include <stdio.h>
+#include <sys/types.h>
+#include "parmci.h"
+#include "armci.h"
+
+int
+ARMCI_AccV (int op, void *scale, armci_giov_t * darr, int len, int proc)
+{
+  int rval;
+  rval = PARMCI_AccV (op, scale, darr, len, proc);
+  return rval;
+}
+EOF
+    if $cxx_compiler $orig_useropt -I$armcidir/include -c armcitest.c 1> /dev/null 2>&1 ; then
+	echo "ARMCI check successful"
+	fixmakeargs="$fixmakeargs ARMCI armcidir=$armcidir"
+    else
+	echo "ARMCI check unsuccessful. Does not support PARMCI interface found in GA 5.0+."
+    fi
+    /bin/rm -f armcitest.c armcitest.o
+fi
 
 if [ $vampirtrace = yes ]; then
     cat <<EOF>vttest.cpp
@@ -5441,7 +5542,7 @@ EOF
       
       $cxx_compiler -c f1.cpp
       icc -c f2.c
-      if icc f1.o f2.o -o foo -lcprts 1>/dev/null 2>&1 ; then
+      if icc f1.o f2.o -o foo.exe -lcprts 1>/dev/null 2>&1 ; then
           echo "Intel v8.0 compilers used"
       else
           $cxx_compiler -c -cxxlib-icc f1.cpp 1>/dev/null 2>&1
@@ -5456,7 +5557,7 @@ EOF
           taugcclibdir=`g++ $tau_opt_bits -print-libgcc-file-name | sed -e 's,[^/]*$,,'`
           taugcclib=`g++ $tau_opt_bits -print-libgcc-file-name `
           taugcclib2dir=`which g++ | sed s/g++/../`         
-          if icc f1.o f2.o -o foo -L$taugcclib2dir/lib -L$taugcclibdir -lstdc++ $taugcclib 1>/dev/null 2>&1 ; then
+          if icc f1.o f2.o -o foo.exe -L$taugcclib2dir/lib -L$taugcclibdir -lstdc++ $taugcclib 1>/dev/null 2>&1 ; then
 #          echo "Confirmed  - links with gcc libs"
               echo "Intel v8.1+ compilers used"
               if [ "x$taugcclib2dir" != "x/usr/bin/../lib" ] ; then
@@ -5470,7 +5571,7 @@ EOF
               fixmakeargs="$fixmakeargs $tauextralibopts taugcclibdir=$taugcclibdir INTEL81FIX" 
           fi
       fi
-      /bin/rm -f f1.o f2.o f1.cpp f2.c foo
+      /bin/rm -f f1.o f2.o f1.cpp f2.c foo.exe
       # Check over!
 fi
 
@@ -5580,9 +5681,27 @@ if [ $hpctoolkit = yes ] ; then
     fixmakeargs="$fixmakeargs HPCTOOLKIT hpctoolkit_include=${hpctoolkit_include} hpctoolkit_link=${hpctoolkit_link}"
 fi
 
-# TAUmon MRNet
+# TAUmon MPI                                                                                
+if [ $mon_mpi = yes ] ; then
+  if [ $mrnet = yes ] ; then
+       echo "ERROR: MRNet and MPI cannot simultaneously be used as TAUmon transport"
+       exit 1
+  fi
+  if [ $mpi = yes ] ; then
+       fixmakeargs="$fixmakeargs MON_MPI"
+  else
+       echo "ERROR: MPI TAUmon transport requires MPI support"
+       exit 1
+  fi
+fi
+
+# TAUmon MRNet                                                                              
 if [ $mrnet = yes ] ; then
-  if [ $mpi = yes ] ; then 
+  if [ $mon_mpi = yes ] ; then
+       echo "ERROR: MRNet and MPI cannot simultaneously be used as TAUmon transport"
+       exit 1
+  fi
+  if [ $mpi = yes ] ; then
        fixmakeargs="$fixmakeargs MRNET"
        if [ $mrnet_use_lightweight = yes ] ; then
             fixmakeargs="$fixmakeargs mrnet_lw=-DMRNET_LIGHTWEIGHT"
@@ -5918,6 +6037,8 @@ if [ "y$1"  = "ydefault" ] ; then
     sed -f $sedex < ${i} > ${i}~~0
     mv ${i}~~0 ${i}
   done
+	
+	echo "" > include/tauroot.h
 
   STUB="default"
 else
