If -MULTIPLECOUNTERS is configured with -PROFILECALLS, -PROFILECOUNTERS, or -PROFILESTATS, it gives a big error message and exits. These options are mutually incompatible at this stage.
git-svn-id: file:///mnt/fast/tau2git/svnroot/trunk/tau2@1073 a8e31b63-e6ca-409b-a01b-2eec1b506579

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -830,6 +830,14 @@ if [ $multiplecounters = yes ]
   then
     fixmakeargs="$fixmakeargs MULTIPLECOUNTERS"
     tauoptions="${tauoptions}-multiplecounters"
+    if [ $profilecalls = yes -o $profilestats = yes -o $profilecounters = yes ]
+    then
+      echo "******** ERROR : -MULTIPLECOUNTERS option is incompatible with "
+      echo "**************** -PROFILECOUNTERS, -PROFILECALLS, or -PROFILESTATS"
+      echo "**************** Please reconfigure TAU without these."
+      echo "******** EXITING .... "
+      exit 1
+    fi
 fi
 
 if [ $papivirtual = yes ]
