Added support for the "-slog2" flag which makes tau2slog2, jumpshot and slog2print from TAU's internal subset of the slog2sdk
git-svn-id: file:///mnt/fast/tau2git/svnroot/trunk/tau2@3335 a8e31b63-e6ca-409b-a01b-2eec1b506579

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -204,6 +204,7 @@ pdt_root_dir="."
 pdt=no
 vtf=no
 slog2=no
+internalslog2=no
 opari=no
 epilog=no
 opari_region=no
@@ -533,7 +534,14 @@ do
     ;;
 
 
-  -pcxxopt=*)
+  -slog2)
+      slog2=yes
+      trace=yes
+      internalslog2=yes
+    shift
+    ;;
+    
+    -pcxxopt=*)
     pcxxopt=`echo $arg | sed -e 's/-pcxxopt=//' -e 's/ /_/g'`
     shift
     ;;
@@ -857,6 +865,7 @@ do
     echo "-dyninst=<dir> ................... Specify location of DynInst Package."
     echo "-vtf=<dir> ......... Specify location of VTF3 Trace Generation Package."
     echo "-slog2=<dir> .......... Specify location of SLOG2 SDK/Jumpshot Package."
+    echo "-slog2 ......... Specify use of TAU internal SLOG2 SDK/Jumpshot Package"
     echo "-mpi .......................... Specify use of TAU MPI wrapper library."
     echo "-mpiinc=<dir> ............. Specify location of MPI include dir and use"
     echo "                           the TAU MPI Profiling and Tracing Interface."
@@ -3139,6 +3148,15 @@ fi
 
 if [ $slog2 = yes ]
 then
+  if [ $internalslog2 = yes ]
+  then
+     slog2dir=$tauroot/tools/src/contrib/slog2sdk/
+      if [ ! -d $slog2dir ]
+      then
+        echo "Error: Cannot access SLOG2 directory $slog2dir"
+        exit 1
+      fi
+  fi
   fixmakeargs="$fixmakeargs SLOG2 slog2dir=$slog2dir"
   jdkdir=`which javac | sed s/javac/../`
   if [ "x$jdkdir" = "x" ]
@@ -3669,6 +3687,23 @@ fi
 
 if [ $slog2 = yes ]
 then
+  if [ $internalslog2 = yes ]
+  then
+    cat ${tauroot}/tools/src/contrib/slog2sdk/bin/jumpshot.skel | 
+    sed -e 's,@TAUROOTDIR@,'$targetdir','  -e 's,@SHELL@,'$taushell',' -e 's,@ARCH@,'$architecture',' > ${targetdir}/${architecture}/bin/jumpshot
+    chmod a+rx ${targetdir}/${architecture}/bin/jumpshot
+    
+    cat ${tauroot}/tools/src/contrib/slog2sdk/bin/slog2print.skel | 
+    sed -e 's,@TAUROOTDIR@,'$targetdir','  -e 's,@SHELL@,'$taushell',' -e 's,@ARCH@,'$architecture',' > ${targetdir}/${architecture}/bin/slog2print
+    chmod a+rx ${targetdir}/${architecture}/bin/slog2print
+    echo "TAU: installed slog2print and jumpshot in ${targetdir}/${architecture}/bin"
+    cp ${tauroot}/tools/src/contrib/slog2sdk/lib/jumpshot.jar ${targetdir}/${architecture}/lib
+    cp ${tauroot}/tools/src/contrib/slog2sdk/lib/traceTOslog2.jar ${targetdir}/${architecture}/lib
+    cp ${tauroot}/tools/src/contrib/slog2sdk/lib/slog2printserial.jar ${targetdir}/${architecture}/lib
+    echo "TAU: installed required slog2sdk jars in ${targetdir}/${architecture}/lib"
+    
+    slog2dir=$targetdir/$architecture
+  fi
   utils/slogconverter/tau2slog2.skel $jdkdir $targetdir $slog2dir $architecture > $targetdir/$architecture/bin/tau2slog2
   chmod a+rx ${targetdir}/${architecture}/bin/tau2slog2
   echo "TAU: installed tau2slog2 in ${targetdir}/${architecture}/bin"
