Add separate support for OMPT TR7 and 5.0
Adding support for OMPT TR7 and 5.0 while keeping the TR6 support as it
is.

The configure script will now detect if the compiler support either OMPT
5.0, TR7 or TR6 and won't download the LLVM OpenMP runtime if that's the
case.


Former-commit-id: 5a96983b1637c872c59f4c8cc1f23ff7554de916

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -969,6 +969,7 @@ stdcxxlib=no
 intelcxxlibicc=no
 intelifort=no
 intel=no
+llvm=no
 mpiwarnings=
 gnu=no
 sol2cc=no
@@ -1088,6 +1089,8 @@ download_ompt=no
 download_ompt_tr6=no
 install_ompt=no
 ompt_use_tr6_version=no
+ompt_use_tr7_version=no
+ompt_use_v5_version=no
 xlsmp=no
 ibmxlc=no
 ibmxlc_r=no
@@ -2067,6 +2070,8 @@ for arg in "$@"; do
         ;;
 
     -ompt-tr6*)
+        openmp=yes
+        ompt=yes
         ompt_use_tr6_version=yes
         shift
         ;;
@@ -3635,7 +3640,7 @@ case $machine in
 	    default_fortran=pgi
 	    fixmakeargs="$fixmakeargs PGI COMPINST_PGI"
         elif [ "x$PE_ENV" = xGNU -a "x$CLANG_HOME" != "x" ]; then 
-            llvm=yes
+	    llvm=yes
 	    tauoptions="${tauoptions}-llvm"
 	    default_fortran=gfortran
 	    fixmakeargs="$fixmakeargs COMPINST_LLVM"
@@ -4232,11 +4237,12 @@ case $cxx_compiler in
 	fixmakeargs="$fixmakeargs USE_CFRONT"
 	;;
     *llvm*|*clang* | hcc | hipcc )
-	echo "Using CLANG Compilers"
+	echo "Default C++ compiler will be clang++"
+        llvm=yes
         fixmakeargs="$fixmakeargs CLANG COMPINST_LLVM"
         tauoptions="${tauoptions}-clang"
-	if [ $machine = apple ]; then
-	    gnu=yes
+	    if [ $machine = apple ]; then
+	        gnu=yes
             fixmakeargs="$fixmakeargs taugcclibdir=/usr/lib taugccstdcxxlibdir=/usr/lib"
             fixmakeargs="$fixmakeargs APPLECXX"
 
@@ -4716,6 +4722,7 @@ case $cxx_compiler in
 		;;
             *clang* | hcc | hipcc )
 		tauoptions="${tauoptions}-clang"
+		llvm=yes
 		echo "Using CLANG Compilers"
 		fixmakeargs="$fixmakeargs CLANG"
 		if [ $machine = apple ]; then
@@ -6935,6 +6942,186 @@ if [ "x$download_unwind" = xyes ] ; then
   cd $prebfddir
 fi #unwind=download
 
+if [ $ompt = yes -a $download_ompt_tr6 = no -a $download_ompt = no ] ; then
+#checking OMP compiler OMPT support
+echo "Checking Compiler OMPT support : "
+touch ompt_ver_test.c
+cat <<EOF > ompt_ver_test.c
+#if defined(VERTEST_OMPT_TR7) || defined(VERTEST_OMPT_5_0)
+#include "omp-tools.h"
+#endif /* VERTEST_OMPT_TR7 || VERTEST_OMPT_5_0 */
+#if defined(VERTEST_OMPT_TR6)
+#include "ompt.h"
+#endif /* VERTEST_OMPT_TR6 */
+#include "omp.h"
+#include "stdio.h"
+
+#if !defined(VERTEST_OMPT_5_0) && !defined(VERTEST_OMPT_TR7) && !defined(VERTEST_OMPT_TR6)
+#error "No OMPT Version was chosen"
+#endif
+
+void on_ompt_callback_mutex_acquire(
+#if defined(VERTEST_OMPT_5_0) || defined(VERTEST_OMPT_TR7)
+ompt_mutex_t kind,
+#endif /* VERTEST_OMPT_5_0)|| VERTEST_OMPT_5_0 */
+#if defined(VERTEST_OMPT_TR6)
+ompt_mutex_kind_t kind,
+#endif /* VERTEST_OMPT_TR6 */
+unsigned int hint,
+unsigned int impl,
+#if defined(VERTEST_OMPT_5_0)
+ompt_wait_id_t wait_id,
+#endif /* VERTEST_OMPT_5_0 */
+#if defined(VERTEST_OMPT_TR7) || defined(VERTEST_OMPT_TR6)
+omp_wait_id_t wait_id,
+#endif /* VERTEST_OMPT_TR7 || VERTEST_OMPT_TR6 */
+const void *codeptr_ra)
+{
+    printf("Useless Callback\n");
+}
+
+int ompt_initialize(
+ompt_function_lookup_t lookup,
+int initial_device_num,
+ompt_data_t* tool_data)
+{
+    ompt_set_callback_t ompt_set_callback = (ompt_set_callback_t) lookup("ompt_set_callback");
+    int ret = ompt_set_callback(ompt_callback_mutex_acquire, (ompt_callback_t)on_ompt_callback_mutex_acquire);
+    return 1;
+}
+
+void ompt_finalize(ompt_data_t* tool_data)
+{
+    return;
+}
+
+/* This function should probably check the version returned by omp_version - although clang 8.0 is returning 201611... */
+ompt_start_tool_result_t * ompt_start_tool(
+#if defined(VERTEST_OMPT_5_0)
+unsigned int omp_version,
+#endif /* VERTEST_OMPT_5_0 */
+const char *runtime_version)
+{
+    static ompt_start_tool_result_t result;
+    result.initialize = &ompt_initialize;
+    result.finalize = &ompt_finalize;
+    result.tool_data.value = 0L;
+    result.tool_data.ptr = NULL;
+    return &result;
+}
+
+int main (int argc, char * argv[])
+{
+    #if defined(VERTEST_OMPT_5_0)
+    printf("Testing Version 5.0\n");
+    #endif /* VERTEST_OMPT_5_0 */
+    #if defined(VERTEST_OMPT_TR7)
+    printf("Testing Version TR7\n");
+    #endif /* VERTEST_OMPT_TR7 */
+    #if defined(VERTEST_OMPT_TR6)
+    printf("Testing Version TR6\n");
+    #endif /* VERTEST_OMPT_TR6 */
+    #pragma omp parallel
+    {
+        printf ("Hi from thread %d\n", omp_get_thread_num());
+    }
+}
+EOF
+
+#find openmp flag
+if [ "$sol2cc" = "yes" ]; then openmp_flag=-xopenmp; fi
+if [ "$suncc" = "yes" ]; then openmp_flag=-xopenmp=parallel; fi
+if [ "$compaq" = "yes" ]; then openmp_flag=-omp; fi
+if [ "$ibmxlc" = "yes" ]; then openmp_flag=-qsmp=omp; fi
+if [ "$open64" = "yes" ]; then openmp_flag=-mp; fi
+if [ "$gnu" = "yes" ]; then openmp_flag=-fopenmp; fi
+if [ "$llvm" = "yes" ]; then openmp_flag=-fopenmp; fi
+if [ "$pgi" = "yes" ]; then openmp_flag=-mp; fi
+if [ "$fujitsu" = "yes" ]; then openmp_flag=-kopenmp; fi
+if [ "$default_fortran" = "cray" ]; then openmp_flag=-h#omp; fi
+if [ "$intel" = "yes" ]; then openmp_flag=-qopenmp; fi
+ompt_support_found=no
+
+if [ $ompt_use_tr6_version = "no" ] ; then
+
+    #checking for OMPT Version 5.0
+    echo -ne "\t Checking for version 5.0 ..."
+    $c_compiler $openmp_flag $orig_useropt -DVERTEST_OMPT_5_0 ompt_ver_test.c -o ompt_ver_test 1>/dev/null 2>&1
+    ./ompt_ver_test 1>/dev/null 2>&1
+    result=$?
+    if [ $result = "0" ]; then
+        echo " yes"
+        ompt_support_found=yes
+        download_ompt=no
+        download_ompt_tr6=no
+        ompt_use_v5_version=yes
+    else
+        echo " no"
+    fi
+    rm -f ./ompt_ver_test
+fi
+
+if [ $ompt_support_found = no -a $ompt_use_tr6_version = no ] ; then
+    #checking for OMPT Version TR7
+    echo -ne "\t Checking for version TR7 ..."
+    $c_compiler $openmp_flag $orig_useropt -DVERTEST_OMPT_TR7 ompt_ver_test.c -o ompt_ver_test 1>/dev/null 2>&1
+    ./ompt_ver_test 1>/dev/null 2>&1
+    result=$?
+    if [ $result = "0" ]; then
+        echo " yes"
+        ompt_support_found=yes
+        download_ompt=no
+        download_ompt_tr6=no
+        ompt_use_tr7_version=yes
+    else
+        echo " no"
+    fi
+    rm -f ./ompt_ver_test
+fi
+
+if [ $ompt_support_found = no ] ; then
+    #checking for OMPT Version TR6
+    echo -ne "\t Checking for version TR6 ..."
+    $c_compiler $openmp_flag $orig_useropt -DVERTEST_OMPT_TR6 ompt_ver_test.c -o ompt_ver_test 1>/dev/null 2>&1
+    ./ompt_ver_test 1>/dev/null 2>&1
+    result=$?
+    if [ $result = "0" ]; then
+        echo " yes"
+        ompt_support_found=yes
+        download_ompt=no
+        download_ompt_tr6=no
+    else
+        echo " no"
+    fi
+    rm -f ./ompt_ver_test
+fi
+
+rm -f ./ompt_ver_test.c
+if [ $ompt_support_found = no ] ; then
+    if [ $ompt_use_tr6_version = no ] ; then
+        echo -n "Compiler does not support OMPT ... "
+        if [ $gnu = yes -o $llvm = yes -o $intel = yes ] ; then
+            echo "Downloading LLVM-OpenMP"
+            download_ompt=yes
+        else
+            echo "LLVM-OpenMP does not support detected compiler"
+            (>&2 echo 'ERROR: OMPT Requested, but there is no way to provide it.')
+            exit 1;
+        fi
+    else
+        echo -n "Compiler does not support OMPT TR6 ... "
+        if [ $gnu = yes -o $llvm = yes -o $intel = yes ] ; then
+            echo "Downloading LLVM-OpenMP"
+            download_ompt=yes
+        else
+            echo "LLVM-OpenMP does not support detected compiler"
+            (>&2 echo 'ERROR: OMPT TR6 Requested, but there is no way to provide it.')
+            exit 1;
+        fi
+    fi
+fi
+fi
+
 ######################################################################
 # Install Scalable Observation System (SOS) if requested
 ######################################################################
@@ -7165,12 +7352,17 @@ else # intel OMPT support
         if [ "x$download_ompt_tr6" = "xyes" -o "x$ompt_use_tr6_version" = "xyes" ] ; then
           echo "Using OMPT TR6"
 	      fixmakeargs="$fixmakeargs TAU_OMPT_TR6 omptlib=$omptlinking"
-        else
-          echo "Using OMPT"
-          fixmakeargs="$fixmakeargs TAU_OMPT omptlib=$omptlinking"
+        elif [ "x$download_ompt" = "xyes" ] ; then
+            echo "Using OMPT"
+            fixmakeargs="$fixmakeargs TAU_OMPT omptlib=$omptlinking"
+        elif [ "$ompt_use_v5_version" = yes ] ; then
+            echo "Using OMPT 5"
+            fixmakeargs="$fixmakeargs TAU_OMPT_5_0 omptlib=$omptlinking"
+        elif [ "$ompt_use_tr7_version" = yes ] ; then
+            echo "Using OMPT TR7"
+            fixmakeargs="$fixmakeargs TAU_OMPT_TR7 omptlib=$omptlinking"
         fi  
     fi 
-
 fi
 
 
@@ -9886,11 +10078,11 @@ if [ $openmp = yes ] ; then
     if [ "$ibmxlc" = "yes" ]; then openmp_flag=-qsmp=omp; fi
     if [ "$open64" = "yes" ]; then openmp_flag=-mp; fi
     if [ "$gnu" = "yes" ]; then openmp_flag=-fopenmp; fi
+    if [ "$llvm" = "yes" ]; then openmp_flag=-fopenmp; fi
     if [ "$pgi" = "yes" ]; then openmp_flag=-mp; fi
     if [ "$fujitsu" = "yes" ]; then openmp_flag=-Kopenmp; fi
     if [ "$default_fortran" = "cray" ]; then openmp_flag=-h#omp; fi
-    if [ "$intel" = "yes" ]; then openmp_flag=-openmp; fi
-
+    if [ "$intel" = "yes" ]; then openmp_flag=-qopenmp; fi
 
     #checking OMP compiler nested supported
     echo -n "Checking OMP NESTED support..."
