Revert tbb check
Former-commit-id: 61a8d49adbd6830be802e11f2d8d9e9cfa6eb3c8

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -10686,9 +10686,9 @@ else
   if [ "x$tbb" = xyes ] ; then
     echo "TBB : not found, downloading..."
     download_tbb=yes
-  else
-    echo "ERROR: Dyninst requires TBB and it was not found in the Dyninst directory. Reconfigure TAU with TBB."
-    exit 1
+#  else
+#    echo "ERROR: Dyninst requires TBB and it was not found in the Dyninst directory. Reconfigure TAU with TBB."
+#    exit 1
   fi
 fi
 
