Updating APEX build support to include OMPT if requested.
Former-commit-id: 48d3194bd6a1401c9bd55909d2f20b40e3e33e63

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6014,7 +6014,6 @@ if [ "x$download_ompt" = xyes ] ; then
         echo "Please check `pwd`/${libomp_oss_log}"
 		exit 1; 
       fi
-	  cd ..
     fi
   else
     install_ompt=no
@@ -8342,8 +8341,14 @@ EOF
 fi
 	
 if [ $apex = yes ] ; then
+    cd ${START_DIR}
+	echo "in directory: `pwd`"
     if [ $boost = no ] ; then 
 	    echo "Error: APEX requires Boost 1.54 or newer. Please specify the Boost installation location with the -boost option."
+	    exit 1;
+	fi
+    if [ $openmp = no -a $pthread = no ] ; then 
+	    echo "Error: APEX is for multithreaded runtimes. Please configure TAU with thread support (pthread or OpenMP)."
 	    exit 1;
 	fi
     cmake_cmd=`which cmake`
@@ -8353,23 +8358,30 @@ if [ $apex = yes ] ; then
     fi
 	echo "Note: Building APEX"
 	apex_include_file=apex/apex.mk
-	rm -f $apex_include_file
-	touch $apex_include_file
-	echo "CC=$c_compiler" >> $apex_include_file
-    echo "CXX=$cxx_compiler" >> $apex_include_file
-    echo "PREFIX=$targetdir" >> $apex_include_file
-    echo "TAUARCH=$architecture" >> $apex_include_file
-    echo "BOOSTROOT=$boostdir" >> $apex_include_file
-	if [ ! "x$bfddir" = "x" ] ; then
-        echo 'BFDOPT="-DUSE_BFD=TRUE -DBFD_ROOT=$bfddir"' >> $apex_include_file
+	rm -f ${apex_include_file}
+	touch ${apex_include_file}
+	echo "CC=${c_compiler}" >> ${apex_include_file}
+    echo "CXX=${cxx_compiler}" >> ${apex_include_file}
+    echo "PREFIX=${targetdir}" >> ${apex_include_file}
+    echo "TAUARCH=${architecture}" >> ${apex_include_file}
+    echo "BOOSTROOT=${boostdir}" >> ${apex_include_file}
+	if [ ! "x${bfddir}" = "x" ] ; then
+        echo "BFDOPT=-USE_BFD=TRUE -DBFD_ROOT=${bfddir}" >> ${apex_include_file}
 	else 
-		if [ $bfd_worked = "yes" ] ; then
-        	echo 'BFDOPT=-DUSE_BFD=TRUE' >> $apex_include_file
+		if [ ${bfd_worked} = "yes" ] ; then
+        	echo 'BFDOPT=-DUSE_BFD=TRUE' >> ${apex_include_file}
 		fi
 	fi
-	if [ $architecture = "mic_linux" ] ; then
-		echo 'TAUCFLAGS=-DCMAKE_C_FLAGS=-mmic' >> $apex_include_file
-		echo 'TAUCXXFLAGS=-DCMAKE_CXX_FLAGS="-mmic -DBOOST_NO_CXX11_ALLOCATOR"' >> $apex_include_file
+	if [ ${architecture} = "mic_linux" ] ; then
+		echo 'TAUCFLAGS=-DCMAKE_C_FLAGS=-mmic' >> ${apex_include_file}
+		echo 'TAUCXXFLAGS=-DCMAKE_CXX_FLAGS="-mmic -DBOOST_NO_CXX11_ALLOCATOR"' >> ${apex_include_file}
+	fi
+	if [ ! "x${omptlib}" = "x" ] ; then
+		if [ "${download_ompt}" = "yes" ] ; then
+        	echo "TAUOMPT=-DUSE_OMPT=TRUE -DOMPT_ROOT=${targetdir}/${architecture}" >> ${apex_include_file}
+		else
+        	echo "TAUOMPT=-DUSE_OMPT=TRUE -DOMPT_ROOT=${omptlib}" >> ${apex_include_file}
+		fi
 	fi
 	cp etc/Makefile.apex apex/Makefile
     fixmakeargs="$fixmakeargs APEX "
@@ -9352,6 +9364,9 @@ if [ $ompt = yes -a $install_ompt = yes -a -r ${libomp_ossdir}/lib${libomp_oss_n
     ompt_instdir=${targetdir}/${architecture}/lib/shared-disable
     mkdir -p ${ompt_instdir}
     cp ${libomp_ossdir}/lib${libomp_oss_name}.a ${ompt_instdir}/lib${libomp_oss_name}.a ; 
+	# apex also needs the headers...
+	mkdir -p ${targetdir}/${architecture}/include
+    cp ${START_DIR}/include/omp*.h ${targetdir}/${architecture}/include
   fi
 fi
 # Save the FixMakefile args
