Adding cleaned up support for mochi configuration
Former-commit-id: b6a03ebdb3531abf3508d4043f5cdcb6676a3313

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1301,6 +1301,8 @@ adios2dir=
 sqlite3=no
 mochi=no
 mochi_sdskv_dir=
+mochi_symbiomon_dir=
+mochi_reducer_dir=
 sqlite3dir=
 #caliper=no
 #caliperdir=
@@ -2245,8 +2247,9 @@ for arg in "$@"; do
             exit 1
         fi
 
-        if [ `pkg-config --exists sdskv-client; echo $?` == "1" ] ; then
-            echo "Error: Cannot access mochi_sdskv install directory! Please verify that mochi-sdskv and dependent modules are loaded."
+        if [ `pkg-config --exists soma-client soma-server soma-admin uuid; echo $?` == "1" ] ; then
+            echo "Error: Cannot access soma-client, soma-server, or soma-admin install directory! Please verify that soma-client and dependent modules are loaded."
+            echo "Run: 'pkg-config --exists soma-client soma-server soma-admin' for more info."
             exit 1
         else
             mochi=yes
@@ -11830,9 +11833,21 @@ if [ $sqlite3 = yes ] ; then
 fi
 
 if [ $mochi = yes ] ; then
-        echo "Detected Mochi..."
-    mochiincludes=`pkg-config --cflags-only-I sdskv-client | sed -e 's/[[:space:]]*$//' | sed 's/ /#/g'`
-    mochilibs=`pkg-config --libs sdskv-client | sed -e 's/[[:space:]]*$//' | sed 's/ /#/g'`
+    echo "Detected Mochi..."
+    mochiincludes=`pkg-config --cflags-only-I soma-client soma-server soma-admin uuid | sed -e 's/[[:space:]]*$//' | sed 's/ /#/g'`
+    # The uuid library is stupid, it's pkgconfig is broken. trim the last /uuid off the end if necessary.
+    uuidincludes=`pkg-config --cflags-only-I uuid`
+    if [[ "$uuidincludes" == */uuid ]] ; then
+        uuidincludes=${uuidincludes::-5}
+    fi
+    mochiincludes="${mochiincludes}#${uuidincludes}"
+    mochilibs=`pkg-config --libs soma-client soma-server soma-admin | sed -e 's/[[:space:]]*$//' | sed 's/ /#/g'`
+    mochirpath=`pkg-config --libs soma-client soma-server soma-admin | sed -e 's/[[:space:]]*$//' | sed 's/ /#/g'`
+    replace="-L"
+    replacewith="-Wl,-rpath,"
+    mochirpath="${mochirpath//${replace}/${replacewith}}"
+    echo ${mochirpath}
+    #mochilibs="${mochilibs}#${mochirpath}"
     fixmakeargs="$fixmakeargs MOCHI "
     fixmakeargs="$fixmakeargs mochiincludes=${mochiincludes}#-DTAU_MOCHI"
     fixmakeargs="$fixmakeargs mochilibs=${mochilibs}"
