Revert caliper changes that broke TAU build when using a non-c++11 compliant compiler
This reverts commit 33d20542d4b00ec867d47028ce9740ddaf52d6f7 [formerly 33f81d57c818916174acd2d1fdd9fb21a3d77449].


Former-commit-id: 1660bcda5d3d4f28a6423918317690e9761f8b01

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -897,8 +897,8 @@ sos=no
 sosdir=
 adios=no
 adiosdir=
-#caliper=no
-#caliperdir=
+caliper=no
+caliperdir=
 apex=no
 dyninst=no
 dyninstinc=no
@@ -1718,16 +1718,16 @@ for arg in "$@"; do
 	    shift
 	    ;;
 
-#	-caliper=*)
-#	    caliper=yes
-#	    caliperdir=`echo $arg | sed -e 's/-caliper=//'`
-#	    if [ ! -d $caliperdir ]
-#	    then
-#		echo "Error: Cannot access CALIPER directory $caliperdir"
-#		exit 1
-#	    fi
-#	    shift
-#	    ;;
+	-caliper=*)
+	    caliper=yes
+	    caliperdir=`echo $arg | sed -e 's/-caliper=//'`
+	    if [ ! -d $caliperdir ]
+	    then
+		echo "Error: Cannot access CALIPER directory $caliperdir"
+		exit 1
+	    fi
+	    shift
+	    ;;
 
 	-dyninst=*)
 	    dyninst=yes
@@ -9803,11 +9803,11 @@ if [ $adios = yes ] ; then
     fixmakeargs="$fixmakeargs adiosdir=$adiosdir"
 fi
 
-#if [ $caliper = yes ] ; then
-#    tauoptions="${tauoptions}-caliper"
-#    fixmakeargs="$fixmakeargs CALIPER "
-#    fixmakeargs="$fixmakeargs caliperdir=$caliperdir"
-#fi
+if [ $caliper = yes ] ; then
+    tauoptions="${tauoptions}-caliper"
+    fixmakeargs="$fixmakeargs CALIPER "
+    fixmakeargs="$fixmakeargs caliperdir=$caliperdir"
+fi
 
 if [ $dyninst = yes ] ; then
     fixmakeargs="$fixmakeargs DYNINST "
