StarPU 1.4 will be released in a few hours, support it
Former-commit-id: 90df0ab086f10bf8202f4544424fcb2cb0ab6600

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3164,6 +3164,18 @@ for arg in "$@"; do
               echo  "Error: Cannot access StarPU directory $starpudir"
               exit 1
             else
+	        if [ -d ${starpudir}/include/starpu/1.4 ]; then
+		    echo "Found StarpU 1.4 and using it"
+		    starpudir=${starpudir}/include/starpu/1.4
+	        else
+		    if [ -d ${starpudir}/include/starpu/1.3 ]; then
+			echo "Found StarpU 1.3 and using it"
+			starpudir=${starpudir}/include/starpu/1.3
+		    else
+		        echo  "Error: Cannot find StarPU 1.3 or 1.4 in $starpudir"
+			exit 1
+		    fi
+		fi
               fixmakeargs="$fixmakeargs starpudir=$starpudir STARPU"
               starpu=yes
             fi
