If disableshared is on (for whatever reason) and python is specified, abort configuration.
git-svn-id: file:///mnt/fast/tau2git/svnroot/trunk/tau2@7133 a8e31b63-e6ca-409b-a01b-2eec1b506579

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4855,6 +4855,11 @@ if [ $disableshared = yes ] ; then
     fixmakeargs="$fixmakeargs NOSHARED"
 fi
 
+if [ $disableshared = yes -a $python = yes ] ; then
+    echo "ERROR: Shared libraries are disabled, but Python is specified"
+    exit 1
+fi
+
 if [ $noex = yes ] ; then
     tauoptions="${tauoptions}-noex"
     if [ $kai = yes ] ; then
