[SOS] Install sqlite3 and check its availability when installing SOS
Former-commit-id: 0a81a655504cdd73fd4580ecb02f4ba24a24700d

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -85,6 +85,17 @@ installsosdeps()
  mkdir chaos
  cd chaos
  currdir=`pwd`
+
+ echo "Install Sqlite3"
+ mkdir sqlite3
+ wget https://www.sqlite.org/2017/sqlite-autoconf-3210000.tar.gz
+ tar -xvzf sqlite-autoconf-3210000.tar.gz
+ cd sqlite-autoconf-3210000
+ ./configure --prefix=$currdir/sqlite3
+ make
+ make install
+ cd ..
+
  wget http://www.cc.gatech.edu/systems/projects/EVPath/chaos_bootstrap.pl
  export FLEXPATH_DIR=$currdir/inst
  perl ./chaos_bootstrap.pl adios-1.12 $FLEXPATH_DIR
@@ -114,6 +125,14 @@ installsos()
  #cd ../..
  #cd $dst
  currdir=`pwd`
+
+ # Check if SQLITE3 is available 
+ sqlite3_cmd=`which sqlite3`
+
+ if [ "x$sqlite3_cmd" = "x" ] ; then
+   echo 'ERROR: SQLITE3 required to build SOS, exiting.'
+   exit 1;
+ fi
 
  cd $dst
  #git checkout master
