Next iteration (may not be the final) of the Python interpreter. This version allows us to specify -python[3]=/usr/bin/python3.10 or -python=python3.10 and finds pythoninc and pythonlib properly. ./configure -python=python3.10 -bfd=download
Former-commit-id: fa5f4f7c395ff17a46d101b9a4cef3cff4e07651

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2660,12 +2660,18 @@ for arg in "$@"; do
             pythonintv=`echo $arg | sed -e 's/-python=//' -e 's/ /#/g'`
             python=yes
             pythonbin=$( which $( echo $pythonintv ) | sed 's,[^/]*$,,' )
-            if [ ! -f $pythonintv ] ; then
-                echo "Error: Cannot access Python interpreter $pythonintv"
-                exit 1
+            if [ ! -f $pythonbin/$pythonintv ] ; then
+		if [ -f $pythonintv ]; then 
+	           echo "Found $pythonintv"
+	        else
+                  echo "Error: Cannot access Python interpreter $pythonbin/$pythonintv or $pythonintv"
+                  exit 1
+		fi 
+	    else
+	        pythonintv=$pythonbin/$pythonintv
             fi
         # Python can/will spawn threads
-        pthread=yes
+            pthread=yes
             shift
             ;;
 
@@ -2683,12 +2689,19 @@ for arg in "$@"; do
 	    python=yes
             python3=yes
             pythonbin=$( which $( echo $pythonintv ) | sed 's,[^/]*$,,' )
-            if [ ! -f $pythonintv ] ; then
-                echo "Error: Cannot access Python interpreter $pythonintv"
-                exit 1
+	    if [ ! -f $pythonbin/$pythonintv ] ; then
+                if [ -f $pythonintv ]; then
+                   echo "Found $pythonintv"
+                else
+                  echo "Error: Cannot access Python interpreter $pythonbin/$pythonintv or $pythonintv"
+                  exit 1
+                fi
+            else
+                pythonintv=$pythonbin/$pythonintv
             fi
+
         # Python can/will spawn threads
-        pthread=yes
+            pthread=yes
             shift
             ;;
 
