Added -ompt=download support.
Former-commit-id: e615d5806d2c3caa1e5a318d23294f0ad57af52b

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,4 +1,4 @@
-#!/bin/sh 
+#!/bin/sh
 #****************************************************************************
 #*			TAU Portable Profiling Package			   **
 #*			http://www.cs.uoregon.edu/research/tau	           **
@@ -1512,6 +1512,12 @@ for arg in "$@"; do
 	    shift
 	    ;;
 
+	-ompt=download*)
+	    ompt=yes
+	    download_ompt=yes
+	    shift
+	    ;;
+
 	-ompt*)
 	    ompt=yes
 	    shift
@@ -2876,40 +2882,6 @@ if [ "$machine" = "apple" ] ; then
     fi
 fi
 
-if [ $machine = bgq -o $machine = bgp -o $machine = bgl ] ; then
-    if [ $ompt = yes -o $xlsmp = yes ]; then
-	comp=`which bgxlc_r`
-	if [ "x$xlsmpdir" = "x" ]; then 
-            if [ -x $comp ]; then 
-		xlsmpdir=`echo $comp | sed -e 's@bgxlc_r@../../../../xlsmp@' `
-		if [ ! -d $xlsmpdir ]; then 
-		    echo "NOTE: Could not locate the xlsmp directory using the location of bgxlc_r in your path."
-		    echo "To enable ompt support in TAU using IBM XL compilers, please configure with -xlsmp=<dir> option to specify the full path to the xlsmp directory inside the compiler directory".
-		    exit 1; 
-		fi
-            fi
-            if [ -d $xlsmpdir -a -r $xlsmpdir/bg/*/bglib64/ompt_full/libxllomp.a -a -r $xlsmpdir/bg/*/include/lomp/omp.h ]; then
-		lompinc=`echo $xlsmpdir/bg/*/include `
-		lomplib=`echo $xlsmpdir/bg/*/bglib64/ompt_full `
-		echo "NOTE: Found LOMP include directory $lompinc"
-		echo "NOTE: Found LOMP lib directory $lomplib"
-		omptenabled=yes
-		tauoptions="${tauoptions}-ompt"
-		fixmakeargs="$fixmakeargs IBMOMPT lompinc=$lompinc lomplib=$lomplib"
-            else
-		echo "NOTE: Did not find lomp/omp.h or lib64/libxllomp.a in the xlsmp subdirectory. Not enabling OMPT support for IBM compilers."
-            fi 
-	else
-	    echo "bgxlc_r not found in the path. Cannot test for OMPT support."
-	fi
-    fi
-else # intel OMPT support
-    if [ $ompt = yes ]; then
-	omptlinking="-Wl,-rpath=$omptlib#-L$omptlib#$omptlibrary"
-	fixmakeargs="$fixmakeargs TAU_OMPT omptlib=$omptlinking"
-    fi
-
-fi 
 
 if [ $machine = craycnl -o $machine = bgq -o $machine = bgp -o $machine = bgl ] ; then
     config_compiler=`which $cxx_compiler`
@@ -5355,6 +5327,109 @@ if [ $linuxtimers = yes ] ; then
     fixmakeargs="$fixmakeargs LINUXTIMERS"
 fi
 
+######################################################################
+# Install Intel OpenMP runtime with OMPT if requested
+######################################################################
+libomp_oss=libomp_oss
+libomp_osstgz=$libomp_oss.tar.gz
+libomp_ossurl=http://www.cs.uoregon.edu/research/paracomp/tau/tauprofile/dist/$libomp_osstgz
+libomp_oss_name=iomp5
+libomp_ossdir=${targetdir}/${architecture}/lib
+if [ "x$download_ompt" = xyes ] ; then
+  prebfddir=`pwd`
+
+  # only build the dynamic version for now
+
+  # if [ -r "$libomp_ossdir/lib${libomp_oss_name}.so" ] && [ -r "$libomp_ossdir/lib${libomp_oss_name}.a" ] ; then
+
+  if [ -r "$libomp_ossdir/lib${libomp_oss_name}.so" ] ; then
+    echo "libomp_oss download already found, skipping"
+  else
+    # get the tar file
+    echo "downloading $libomp_osstgz..."
+    if [ "$machine" = "apple" ] ; then
+      curl -L $libomp_ossurl > $libomp_osstgz
+    else 
+      wget $libomp_ossurl
+    fi
+
+    # check the tar file
+    if [ ! -f $libomp_osstgz ] ; then
+      echo "$libomp_osstgz did not download.  Please download it manually from: "
+      echo "$libomp_ossurl"
+      echo "Please enter the directory containing the tarball: ${nnl}" 
+      read RESPONSE
+      cp $RESPONSE/$libomp_osstgz .
+    else
+      echo "expanding $libomp_osstgz..."
+      tar -xzf $libomp_osstgz
+      echo "removing $libomp_osstgz..."
+      rm $libomp_osstgz
+      cd $libomp_oss
+      libomp_oss_log=build-dynamic.log
+      echo "building dynamic $libomp_oss (see `pwd`/${libomp_oss_log} for log)..."
+      make linktype=dynamic >& $libomp_oss_log
+      result=$?
+      signature=`ls -tr tmp | grep rel | grep dyn | tail -1`
+      cp tmp/${signature}/lib${libomp_oss_name}.so ${libomp_ossdir}/.
+      if [ $result -eq 0 ] ; then
+        echo "...Success."
+      else
+        echo "ERROR BUILDING $libomp_ossdir!"
+        echo "Please check `pwd`/${libomp_oss_log}"
+      fi
+
+      # only build the dynamic version for now
+
+      # libomp_oss_log=build-static.log
+      # echo "building static $libomp_oss... (see `pwd`/${libomp_oss_log} for log)"
+      # make linktype=static >& $libomp_oss_log
+      # signature=`ls -tr tmp | grep rel | grep sta | tail -1`
+      # cp tmp/${signature}/lib${libomp_oss_name}.a ${libomp_ossdir}/.
+
+    fi
+  fi
+  omptlib=${libomp_ossdir}
+  omptlibrary=-l${libomp_oss_name}
+  cd $prebfddir
+fi #ompt=download
+    
+
+if [ $machine = bgq -o $machine = bgp -o $machine = bgl ] ; then
+    if [ $ompt = yes -o $xlsmp = yes ]; then
+	comp=`which bgxlc_r`
+	if [ "x$xlsmpdir" = "x" ]; then 
+            if [ -x $comp ]; then 
+		xlsmpdir=`echo $comp | sed -e 's@bgxlc_r@../../../../xlsmp@' `
+		if [ ! -d $xlsmpdir ]; then 
+		    echo "NOTE: Could not locate the xlsmp directory using the location of bgxlc_r in your path."
+		    echo "To enable ompt support in TAU using IBM XL compilers, please configure with -xlsmp=<dir> option to specify the full path to the xlsmp directory inside the compiler directory".
+		    exit 1; 
+		fi
+            fi
+            if [ -d $xlsmpdir -a -r $xlsmpdir/bg/*/bglib64/ompt_full/libxllomp.a -a -r $xlsmpdir/bg/*/include/lomp/omp.h ]; then
+		lompinc=`echo $xlsmpdir/bg/*/include `
+		lomplib=`echo $xlsmpdir/bg/*/bglib64/ompt_full `
+		echo "NOTE: Found LOMP include directory $lompinc"
+		echo "NOTE: Found LOMP lib directory $lomplib"
+		omptenabled=yes
+		tauoptions="${tauoptions}-ompt"
+		fixmakeargs="$fixmakeargs IBMOMPT lompinc=$lompinc lomplib=$lomplib"
+            else
+		echo "NOTE: Did not find lomp/omp.h or lib64/libxllomp.a in the xlsmp subdirectory. Not enabling OMPT support for IBM compilers."
+            fi 
+	else
+	    echo "bgxlc_r not found in the path. Cannot test for OMPT support."
+	fi
+    fi
+else # intel OMPT support
+    if [ $ompt = yes ]; then
+	omptlinking="-Wl,-rpath=$omptlib#-L$omptlib#$omptlibrary"
+	fixmakeargs="$fixmakeargs TAU_OMPT omptlib=$omptlinking"
+    fi
+
+fi 
+
 
 echo "***********************************************************************"
 
@@ -6310,7 +6385,6 @@ else
 fi
 /bin/rm -f tau_weak_test.o tau_weak_test.c
 ##########################################################################
-
 
 
 ######################################################################
