Errors when building TAU with up-to-date MPC: compile with only necessary MPC options
Former-commit-id: 06ad0f6720d178f2e7d88faf850ecad50dac910c

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -936,6 +936,11 @@ for arg in "$@"; do
 	    if [ $myarg = cc -o $myarg = gcc -o $myarg = gcc4 -o $myarg = KCC -o $myarg = pgcc -o $myarg = guidec -o $myarg = xlc -o $myarg = ecc -o $myarg = icc -o $myarg = powerpc64-linux-gcc -o $myarg = pathcc -o $myarg = fcc -o $myarg = orcc -o $myarg = opencc -o $myarg = qk-pgcc -o $myarg = scgcc -o $myarg = scpathcc -o $myarg = mips64el-gentoo-linux-gnu-gcc -o $myarg = powerpc64-bgq-linux-gcc -o $myarg = powerpc-bgp-linux-gcc -o $myarg = x86_64-w64-mingw32-gcc -o $myarg = mpiicc -o $myarg = mpifcc -o $myarg = mpifccpx -o $myarg = clang -o $myarg = bgclang -o $myarg = mpc_cc -o $myarg = mpc_icc -o $myarg = mpicc -o $myarg = mcc -o $myarg = oshcc ]
 	    then
 		c_compiler=$myarg
+
+                if [[ ( $c_compiler = mpc_cc ) || ( $c_compiler = mpc_icc ) ]]
+                then
+	 	  mpc_c_compiler=`$myarg -show | awk '{ print $1; }'`
+                fi
 	    else
 		testxlc=`echo $myarg | sed -e 's/xlc//'`
 		testmp=`echo $myarg | sed -e 's/^mp//'`
@@ -960,6 +965,12 @@ for arg in "$@"; do
 	    if [ $myarg = CC -o $myarg = KCC -o $myarg = g++ -o $myarg = g++4 -o $myarg = cxx  -o $myarg = NCC -o $myarg = pgc++ -o $myarg = pgCC  -o $myarg = pgcpp -o $myarg = egcs -o $myarg = FCC -o $myarg = guidec++ -o $myarg = aCC -o $myarg = c++ -o $myarg = ecpc -o $myarg = icpc -o $myarg = powerpc64-linux-g++ -o $myarg = pathCC -o $myarg = orCC -o $myarg = openCC -o $myarg = qk-pgCC -o $myarg = scg++ -o $myarg = scpathCC -o $myarg = mips64el-gentoo-linux-gnu-g++ -o $myarg = powerpc-bgp-linux-g++ -o $myarg = powerpc64-bgq-linux-g++ -o $myarg = mpicxx  -o $myarg = x86_64-w64-mingw32-g++  -o $myarg = mpiicpc -o $myarg = mpiFCC -o $myarg = mpiFCCpx -o $myarg = mpc_cxx -o $myarg = mpc_icpc -o $myarg = clang++ -o $myarg = bgclang++ -o $myarg = mpicxx -o $myarg = mcxx -o $myarg = oshCC -o $myarg = oshc++ ]
 	    then
 		cxx_compiler=$myarg
+                if [[ ( $cxx_compiler = mpc_cxx ) || ( $cxx_compiler = mpc_icpc ) ]]
+                then
+                  mpc_include=`mpc_cxx -show | grep -o '[^ ]*include/mpcframework[^ ]*'`
+	 	  mpc_cxx_compiler=`$myarg -show | awk '{ print $1; }'`
+                fi
+
 	    else
 		testxlc=`echo $myarg | sed -e 's/xl//'`
 		testmp=`echo $myarg | sed -e 's/^mp//'`
@@ -2678,6 +2689,11 @@ esac
 
 if [ "$c_compiler" != "" -a "$c_compiler" != "default" ]; then
     TAU_CCOM="$c_compiler"          # for 'archfind'
+    if [ "$c_compiler" = mpc_cc ]
+    then
+      TAU_CCOM="$mpc_c_compiler"
+      echo $TAU_CCOM
+    fi
     export TAU_CCOM
 fi
 
@@ -3978,18 +3994,23 @@ case $cxx_compiler in
 
     mpc_cxx)
 	if [ $machine = x86_64 -o $machine = mic_linux ] ; then
+            #mpc_include=`mpc_cxx -show | grep '-I'`
+            #mpc_include=`mpc_cxx -show | grep -o '[^ ]-I[^ ]*'`
+            mpc_include=`mpc_cxx -show | grep -o '[^ ]*include/mpcframework[^ ]*'`
             full_cxx_compiler=`mpc_cxx -show | awk '{print $1;}'`
             full_cc_compiler=`mpc_cc -show | awk '{ print $1;}'`
             fixmakeargs="tau_build_cc=$full_cc_compiler tau_build_cxx=$full_cxx_compiler $fixmakeargs"
+            #mpilibrary=`mpc_cxx -show | sed -e "s@$full_cxx_compiler@@g" | sed -e "s/ /#/g" -e "s/''//g"`
             mpilibrary=`mpc_cxx -show | sed -e "s@$full_cxx_compiler@@g" | sed -e "s/ /#/g" -e "s/''//g"`
-            full_cxx_compiler=`mpc_cxx -show -Dmain=mpc_user_main__ | sed -e "s@-fmpc-privatize@@g" -e "s/ /#/g" -e "s/''//g"`
-            full_cc_compiler=`mpc_cc -show -Dmain=mpc_user_main__ | sed -e "s@-fmpc-privatize@@g" -e "s/ /#/g" -e "s/''//g" `
+            #full_cxx_compiler=`mpc_cxx -show -Dmain=mpc_user_main__ | sed -e "s@-fmpc-privatize@@g" -e "s/ /#/g" -e "s/''//g"`
+            #full_cc_compiler=`mpc_cc -show -Dmain=mpc_user_main__ | sed -e "s@-fmpc-privatize@@g" -e "s/ /#/g" -e "s/''//g" `
 	    #echo "CC=$cc_compiler"
 	    #echo "CXX=$cxx_compiler"
 	    #echo "mpilibrary=$mpilibrary"
 	    tauoptions="${tauoptions}-mpc"
             fixmakeargs="$fixmakeargs MPC"
             mpc=yes
+            mpi=yes
         fi
         ;;
 
@@ -7667,12 +7688,29 @@ if [ "x$bfd" = "xyes" -a ! "$turnbfdoff" = yes ] ; then
           err=$?
         fi
         ;;
-      *)
-        ./configure \
-            CFLAGS=-fPIC CXXFLAGS=-fPIC \
+      *)   
+        echo $c_compiler
+        echo $mpc_c_compiler
+        echo $mpc_cxx_compiler
+        if [ "$c_compiler" = mpc_cc ]
+        then
+           ./configure \
+            CFLAGS="-fPIC -Wno-error" CXXFLAGS="-fPIC -Wno-error" \
+            CC=$mpc_c_compiler CXX=$mpc_cxx_compiler \
             --prefix=$bfddir \
             --disable-nls --disable-werror > tau_configure.log 2>&1
-        err=$?
+            err=$?
+            echo $err
+            echo "CHECK MPC"
+        else
+          echo "NOT MPC"
+          ./configure \
+            CFLAGS=-fPIC CXXFLAGS=-fPIC \
+            #CC=$c_compiler CXX=$cxx_compiler \
+            --prefix=$bfddir \
+            --disable-nls --disable-werror > tau_configure.log 2>&1
+            err=$?
+        fi
         ;;
       esac
 
