Added support for gnu compilers on BGP.  Configure with:
-arch=bgp -cc=mpicc -c++=mpicxx -fortran=gfortran


git-svn-id: file:///mnt/fast/tau2git/svnroot/trunk/tau2@6181 a8e31b63-e6ca-409b-a01b-2eec1b506579

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1923,10 +1923,14 @@ case $machine in
     ;;
 
    bgp)
-    if [ $cxx_compiler = default ]
-    then
+    if [ $cxx_compiler = default ] ; then
       cxx_compiler=mpixlcxx_r
       c_compiler=mpixlc_r
+    elif [ $cxx_compiler = mpicxx ] ; then
+      cxx_compiler=mpicxx
+      c_compiler=mpicc
+      gnu=yes
+      fixmakeargs="$fixmakeargs GNU BGP_GFORTRAN"
     fi
     ;;
 
@@ -2403,7 +2407,6 @@ fi
 
 ######################################################################
 # Set default C++ compiler in all Makefiles
-
 case $cxx_compiler in
    CC)
       echo "Default C++ compiler will be CC"
@@ -2687,8 +2690,16 @@ case $cxx_compiler in
       fi
       ;;
 
+    mpicxx)
+	if [ $machine = bgp ] ; then
+	    echo "Using GNU Compilers for BGP"
+	else
+	    echo "ERROR Unknown C++ compiler: $cxx_compiler"
+	    exit 1
+	fi
+	;;
    *)
-      echo "ERROR Unknown C++ compiler"
+      echo "ERROR Unknown C++ compiler: $cxx_compiler"
       exit 1
       ;;
 
