Added -pin=<dir> options.
Former-commit-id: 449dc2f18b5f89fd7c04f7c4d2ab8a0c84ada79c

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -358,6 +358,7 @@ for arg in "$@"; do
 	    echo "-unwind=<dir | download> ... Specify a libunwind directory or download."
 	    echo "    Note: 'download' will download and build the library automatically."
 	    echo ""
+	    echo "-pin=<dir> ..... Specify location of Intel PIN instrumentation toolkit."
 	    echo "MPI Options:"
 	    echo "-mpi .......................... Specify use of TAU MPI wrapper library."
 	    echo "-mpiinc=<dir> ............. Specify location of MPI include dir and use"
@@ -519,6 +520,7 @@ for arg in "$@"; do
         echo "-papi=<dir> ............... Specify location of PAPI (Performance API)."
         echo "-beacon=<dir> ............... Specify location of BEACON."
         echo "-pdt=<dir> ........ Specify location of PDT (Program Database Toolkit)."
+	echo "-pin=<dir> ..... Specify location of Intel PIN instrumentation toolkit."
         echo "-jdk=<dir>  Build a library for profiling Java code with specified jdk."
         echo "-android_sdk=<dir> ................ Android SDK used for APK injection."
         echo "-android_version=VERSION ................. Android version, e.g. '4.4'."
@@ -828,6 +830,7 @@ tautoplevel=
 tauoptions=
 pdt_root_dir="."
 pdt=no
+pin=no
 armci=no
 vtf=no
 otf=no
@@ -1549,6 +1552,16 @@ for arg in "$@"; do
 	    pdtdir=`echo $arg | sed -e 's/-pdt=//'`
 	    if [ ! -d $pdtdir ] ; then
 		echo "Error: Cannot access PDT directory $pdtdir"
+		exit 1
+	    fi
+	    shift
+	    ;;
+
+	-pin=*)
+	    pin=yes
+	    pindir=`echo $arg | sed -e 's/-pin=//'`
+	    if [ $pindir != "download" -a ! -d $pindir ] ; then
+		echo "Error: Cannot access Intel PIN directory $pindir"
 		exit 1
 	    fi
 	    shift
@@ -3405,7 +3418,6 @@ if [ $stff = yes ] ; then
         echo "Error: Must specify -sddf=/path/to/sddflib along with -stff=/path/to/stfflib!"
     fi
 fi
-
 
 
 if [ $trace = yes ] ; then
@@ -7649,6 +7661,21 @@ if [ "x$machine" = "xarm_android" ]; then
 	rm -rf "$tmpdir"
     fi
 fi
+######################################################################
+# Install PIN if requested
+######################################################################
+PINURL_x86_64=http://software.intel.com/sites/landingpage/pintool/downloads/pin-3.2-81205-gcc-linux.tar.gz
+if [ "x$pindir" = "xdownload" ]; then
+  if [ $machine = craycnl -o $machine = x86_64 -o $machine = i386_linux ]; then 
+    pushd $targetdir/$machine; wget $PINURL_x86_64; 
+    tar zxf pin-*.tar.gz; rm -f pin-*.tar.gz; ln -s pin-* pin; pindir=`readlink -f pin`; popd; 
+  fi
+fi
+
+if [ $pin = yes -a "x$pindir" != "x" ]; then
+    fixmakeargs="$fixmakeargs PIN pindir=$pindir"
+    tauoptions="${tauoptions}-pin"
+fi 
 
 ######################################################################
 # Install BFD if requested
