Adding APEX build support to TAU.
To get the APEX code in the TAU git repo, do the following from the
main TAU directory:

git submodule update --init --recursive
git submodule foreach git pull origin master

then configure TAU with -apex.


Former-commit-id: 70991416afe2aa43e21bf7e03b36358f4199d73f

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -520,6 +520,7 @@ for arg in "$@"; do
 	    echo "-android_platform=VERSION ........ Android platform version, e.g. '19'."
 	    echo "-asmdex=<dir | download> ...... Specify a asmdex directory or download."
 	    echo "-boost=<dir> ....................... Specify location of Boost Package."
+	    echo "-apex ......................................... Build the APEX package."
 	    echo "-dyninst=<dir> ................... Specify location of DynInst Package."
 	    echo "-dyninstinc=<dir> ............ Specify location of DynInst include dir."
 	    echo "-dyninstlib=<dir> ................ Specify location of DynInst lib dir."
@@ -865,6 +866,7 @@ forceshared=no
 opari_region=no
 opari_construct=no
 boost=no
+apex=no
 dyninst=no
 dyninstinc=no
 dyninstlib=no
@@ -1578,6 +1580,11 @@ for arg in "$@"; do
 
 	-ebs2otf)
 	    ebs2otf=yes
+	    shift
+	    ;;
+
+	-apex)
+	    apex=yes
 	    shift
 	    ;;
 
@@ -8329,8 +8336,40 @@ EOF
     /bin/rm -f vttest.cpp vttest.o
 fi
 	
-	
-
+if [ $apex = yes ] ; then
+    if [ $boost = no ] ; then 
+	    echo "Error: APEX requires Boost 1.54 or newer. Please specify the Boost installation location with the -boost option."
+	    exit 1;
+	fi
+    cmake_cmd=`which cmake`
+    if [ "x$cmake_cmd" = "x" ] ; then 
+        echo 'ERROR: cmake version 2.8 or higher required to build APEX.'
+        exit 1;
+    fi
+	echo "Note: Building APEX"
+	apex_include_file=apex/apex.mk
+	rm -f $apex_include_file
+	touch $apex_include_file
+	echo "CC=$c_compiler" >> $apex_include_file
+    echo "CXX=$cxx_compiler" >> $apex_include_file
+    echo "PREFIX=$targetdir" >> $apex_include_file
+    echo "TAUARCH=$architecture" >> $apex_include_file
+    echo "BOOSTROOT=$boostdir" >> $apex_include_file
+	if [ ! "x$bfddir" = "x" ] ; then
+        echo 'BFDOPT="-DUSE_BFD=TRUE -DBFD_ROOT=$bfddir"' >> $apex_include_file
+	else 
+		if [ $bfd_worked = "yes" ] ; then
+        	echo 'BFDOPT=-DUSE_BFD=TRUE' >> $apex_include_file
+		fi
+	fi
+	if [ $architecture = "mic_linux" ] ; then
+		echo 'TAUCFLAGS=-DCMAKE_C_FLAGS=-mmic' >> $apex_include_file
+		echo 'TAUCXXFLAGS=-DCMAKE_CXX_FLAGS="-mmic -DBOOST_NO_CXX11_ALLOCATOR"' >> $apex_include_file
+	fi
+	cp etc/Makefile.apex apex/Makefile
+    fixmakeargs="$fixmakeargs APEX "
+	make -C apex clean
+fi
 
 if [ $java = yes ] ; then
     fixmakeargs="$fixmakeargs JAVA jdkdir=$jdkdir"
@@ -8680,7 +8719,7 @@ if [ $boost = yes ] ; then
       fixmakeargs="$fixmakeargs boostinc=-I$boostdir/include"
     fi
     if [ "x$boostdir" != "x" -a -d $boostdir -a -d $boostdir/lib ]; then
-      fixmakeargs="$fixmakeargs boostlib=-L$boostdir/lib -Wl,-rpath,$boostdir/lib"
+      fixmakeargs="$fixmakeargs boostlib=-L$boostdir/lib#-Wl,-rpath,$boostdir/lib"
     fi
 fi
 
