Added -bfd=download recognition which will download and build binutils-2.18 (from the TAU site) with -fPIC options.  Subsequent builds with -bfd=download will not redownload/rebuild, it will used the already downloaded/built one.
git-svn-id: file:///mnt/fast/tau2git/svnroot/trunk/tau2@6453 a8e31b63-e6ca-409b-a01b-2eec1b506579

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -837,14 +837,31 @@ do
   -bfd=*)
       bfd=yes
       bfddir=`echo $arg | sed -e 's/-bfd=//'`
+      if [ "x$bfddir" = xdownload ] ; then
+	  bfddir=`pwd`/binutils-2.18
+	  if [ -r "$bfddir/lib/libbfd.a" ] ; then
+	      echo "BFD download already found, skipping"
+	  else
+	      mkdir .tmp
+	      cd .tmp
+	      wget http://www.cs.uoregon.edu/research/paracomp/tau/tauprofile/dist/binutils-2.18.tar.gz
+	      tar -xzf binutils-2.18.tar.gz
+	      cd binutils-2.18
+	      ./configure CFLAGS=-fPIC CXXFLAGS=-fPIC --prefix=$bfddir
+	      make && make install
+	      cd ..
+	      cd ..
+	      rm -rf .tmp
+	  fi
+      fi
       fixmakeargs="$fixmakeargs bfdlink=-L$bfddir/lib"
       fixmakeargs="$fixmakeargs bfdinclude=-I$bfddir/include"
       if [ ! -d $bfddir ]
       then
-        echo "Error: Cannot access BFD directory $bfddir"
-        exit 1
+          echo "Error: Cannot access BFD directory $bfddir"
+          exit 1
       fi
-    shift
+      shift
     ;;
 
   -perfinc=*)
