Query Python interpreter for Python paths
When building with -python, TAU's configure script would try to find an
include directory and libpython relative to the interpreter. It would
pick the first one listed by ls. This doesn't always work correctly,
because multiple Pythons can be installed into the same directory, in
which case TAU could pick a different Python include and library version
than the interpreter.

This changes `configure` to execute python and use the module
`sysconfig` to get the Python include directory, library directory, and
library name. If that fails, it falls back to the old approach.

Also, -python and -python3 now take optional arguments to specify a
Python interpreter by name, if a version other than the default is
needed.


Former-commit-id: b952846b32167c5012734ccf84fe6e5e03b84805

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -784,6 +784,7 @@ usage() {
     echo "-otf=<dir> ....... Specify location of Open Trace Format (OTF) Package."
     echo "-darshan=<dir> ............... Specify location of Darshan I/O package."
     echo "-python .. Automatically choose python options based on Python in path."
+    echo "-python=<interp> .... Choose Python options based on named interpreter."
     echo "-python3  Automatically choose python options based on Python3 in path."
     echo "-pythoninc=<dir> ........ Specify location of Python include directory."
     echo "-pythonlib=<dir> ............ Specify location of Python lib directory."
@@ -962,7 +963,8 @@ for arg in "$@"; do
         echo "-upcnetwork=<value> .. Specify network (mpi, udp,...) for Berkeley UPC."
         echo "-gasnet=<dir>  ............ Specify location of GASNET for UPC wrapper."
         echo "-python .. Automatically choose python options based on Python in path."
-	echo "-python3  Automatically choose python options based on Python3 in path."
+        echo "-python=<interp> .... Choose Python options based on named interpreter."
+	    echo "-python3  Automatically choose python options based on Python3 in path."
         echo "-pythoninc=<dir> ........ Specify location of Python include directory."
         echo "-pythonlib=<dir> ............ Specify location of Python lib directory."
         echo "-starpu[=<dir>] ................................ Enable StarPU support."
@@ -2651,9 +2653,37 @@ for arg in "$@"; do
             shift
             ;;
 
+        -python=*)
+            pythonintv=`echo $arg | sed -e 's/-python=//' -e 's/ /#/g'`
+            python=yes
+            pythonbin=$( which $( echo $pythonintv ) | sed 's,[^/]*$,,' )
+            if [ ! -f $pythonbin/$pythonintv ] ; then
+                echo "Error: Cannot access Python interpreter $pythonintv"
+                exit 1
+            fi
+        # Python can/will spawn threads
+        pthread=yes
+            shift
+            ;;
+
         -python)
             pythonbin=`which python | sed 's,[^/]*$,,'`
             python=yes
+            pythonintv=python
+        # Python can/will spawn threads
+        pthread=yes
+            shift
+            ;;
+
+	-python3=*)
+            pythonintv=`echo $arg | sed -e 's/-python3=//' -e 's/ /#/g'`
+	    python=yes
+            python3=yes
+            pythonbin=$( which $( echo $pythonintv ) | sed 's,[^/]*$,,' )
+            if [ ! -f $pythonbin/$pythonintv ] ; then
+                echo "Error: Cannot access Python interpreter $pythonintv"
+                exit 1
+            fi
         # Python can/will spawn threads
         pthread=yes
             shift
@@ -3281,21 +3311,39 @@ done
 # Check for Python
 if [ "x$python3"  = "xyes" ] ; then
   if [ "x$pythoninc" = "x" ] ; then
-    pythoninc=`echo ${pythonbin}../include/python3* | sed -e 's/ .*//g'`
-    echo "Using Python3 include files from: $pythoninc"
+    # First try to get pythoninc by querying the python interpreter
+    echo "Checking for Python include paths from interpreter ${pythonintv}..."
+    pythoninc=`${pythonintv} ./utils/python_get_paths.py inc | sed -e 's/ .*//g'`
+    if [ "x$pythoninc" = "x" ] ; then
+        echo "Checking for Python include paths relative to ${pythonbin}..."
+        # If that fails, fall back to searching relative to the interpreter
+        pythoninc=`echo ${pythonbin}../include/python3* | sed -e 's/ .*//g'`
+    fi
+    if [ -d $pythoninc ] ; then
+        echo "Using Python3 include files from: $pythoninc"
+    fi
     if [ ! -d $pythoninc ] ; then
         echo "Error: Cannot access Python include directory $pythoninc"
         exit 1
     fi
   fi
   if [ "x$pythonlib" = "x" ] ; then
-    for libdir in "lib64" "lib32" "lib" ; do
-      pythonlib=`echo ${pythonbin}../${libdir}/python3* | sed -e 's/ .*//g'`
-      if [ -d "$pythonlib" ] ; then
+    # First try to get pythonlib by querying the python interpreter
+    echo "Checking for Python library path from interpreter ${pythonintv}..."
+    pythonlib=`${pythonintv} ./utils/python_get_paths.py libdir | sed -e 's/ .*//g'`
+    if [ "x$pythonlib" = "x" ] ; then
+        echo "Checking for Python library path relative to ${pythonbin}..."
+        # If that fails, fall back to searching relative to the interpreter
+        for libdir in "lib64" "lib32" "lib" ; do
+        pythonlib=`echo ${pythonbin}../${libdir}/python3* | sed -e 's/ .*//g'`
+        if [ -d "$pythonlib" ] ; then
+            echo "Using Python3 library files from: $pythonlib"
+            break
+        fi
+        done
+    else
         echo "Using Python3 library files from: $pythonlib"
-        break
-      fi
-    done
+    fi
     if [ ! -d $pythonlib ] ; then
       echo "Error: Cannot access Python lib directory $pythonlib"
       exit 1
@@ -3305,21 +3353,39 @@ else
 
 if [ "x$python"  = "xyes" ] ; then
   if [ "x$pythoninc" = "x" ] ; then
-    pythoninc=`echo ${pythonbin}../include/python* | sed -e 's/ .*//g'`
-    echo " Using Python include files from:$pythoninc"
+    # First try to get pythoninc by querying the python interpreter
+    echo "Checking for Python include paths from interpreter ${pythonintv}..."
+    pythoninc=`${pythonintv} ./utils/python_get_paths.py inc | sed -e 's/ .*//g'`
+    if [ "x$pythoninc" = "x" ] ; then
+        # If that fails, fall back to searching relative to the interpreter
+        echo "Checking for Python include paths relative to ${pythonbin}..."
+        pythoninc=`echo ${pythonbin}../include/python* | sed -e 's/ .*//g'`
+    fi
+    if [ -d $pythoninc ] ; then
+        echo "Using Python include files from: $pythoninc"
+    fi
     if [ ! -d $pythoninc ] ; then
         echo "Error: Cannot access Python include directory $pythoninc"
         exit 1
     fi
   fi
   if [ "x$pythonlib" = "x" ] ; then
-    for libdir in "lib64" "lib32" "lib" ; do
-      pythonlib=`echo ${pythonbin}../${libdir}/python* | sed -e 's/ .*//g'`
-      if [ -d "$pythonlib" ] ; then
-	echo "Using Python library files from: $pythonlib"
-        break
-      fi
-    done
+    echo "Checking for Python library path from interpreter ${pythonintv}..."
+    # First try to get pythonlib by querying the python interpreter
+    pythonlib=`${pythonintv} ./utils/python_get_paths.py libdir | sed -e 's/ .*//g'`
+    if [ "x$pythonlib" = "x" ] ; then
+        # If that fails, fall back to searching relative to the interpreter
+        echo "Checking for Python library path relative to ${pythonbin}..."
+        for libdir in "lib64" "lib32" "lib" ; do
+        pythonlib=`echo ${pythonbin}../${libdir}/python* | sed -e 's/ .*//g'`
+        if [ -d "$pythonlib" ] ; then
+            echo "Using Python library files from: $pythonlib"
+            break
+        fi
+        done
+    else
+        echo "Using Python library files from: $pythonlib"
+    fi
     if [ ! -d $pythonlib ] ; then
       echo "Error: Cannot access Python lib directory $pythonlib"
       exit 1
@@ -10868,6 +10934,10 @@ if [ $sproc = yes ] ; then
 fi
 
 if [ $python = yes ] ; then
+    if [ "x$pythonlibrary" = "x" ] ; then
+        echo "Checking for Python library name from interpreter ${pythonintv}... "
+        pythonlibrary=`${pythonintv} ./utils/python_get_paths.py libname | sed -e 's/ .*//g'`
+    fi
     if [ "x$pythonlibrary" != "x" ] ; then
         if [ ! -f $pythonlib/$pythonlibrary ] ; then
                 echo "ERROR: Python library $pythonlib/$pythonlibrary not found."
