Added -roctracer.
Former-commit-id: d10f5baa7f6a37556e333350a2775342d9d0fabc

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -477,7 +477,7 @@ for arg in "$@"; do
 	    echo "Compiler Options:"
 	    echo "-c++=<compiler>  ............................ specify the C++ compiler."
 	    echo "    options [CC|KCC|g++|*xlC*|cxx|pgc++|pgcpp|FCC|guidec++|aCC|c++|ecpc|"
-	    echo "    armclang++|clang++|bgclang++|g++4|g++-*|icpc|scgcc|scpathCC|pathCC|orCC]."
+	    echo "    armclang++|clang++|bgclang++|hcc|g++-*|icpc|scgcc|scpathCC|pathCC|orCC]."
 	    echo "-cc=<compiler> ................................ specify the C compiler."
 	    echo "     options [cc|gcc|clang|bgclang|gcc4|scgcc|KCC|pgcc|guidec|*xlc*|ecc|"
             echo "         armclang|pathcc|orcc]."
@@ -548,6 +548,8 @@ for arg in "$@"; do
            # echo "-rocprofiler=<dir> .............. Specify location of ROCm rocprofiler."
            # echo "-rocprofilerinc=<dir> .... Specify location of rocprofiler include dir."
            # echo "-rocprofilerlibrary=<library> .... Specify name of rocprofiler library."
+            echo "-roctracer=<dir> .................. Specify location of ROCm roctracer."
+            echo "-hip=<dir> .................... Specify location of ROCm HIP directory."
 	    echo ""
 	    echo "Other Options:"
 	    echo "-iowrapper .................................... Build POSIX IO Wrapper."
@@ -634,7 +636,7 @@ for arg in "$@"; do
         echo "  where [OPTIONS] are:"
         echo "-c++=<compiler>  ............................ specify the C++ compiler."
         echo "    options [CC|KCC|g++|*xlC*|cxx|pgc++|pgcpp|FCC|guidec++|aCC|c++|ecpc|"
-        echo "       armclang++|clang++|bgclang++|g++4|icpc|scgcc|scpathCC|pathCC|orCC]."
+        echo "       armclang++|clang++|bgclang++|hcc|hipcc|icpc|scgcc|scpathCC|pathCC|orCC]."
         echo "-cc=<compiler> ................................ specify the C compiler."
         echo "   options [cc|gcc|gcc4|scgcc|clang|pgcc|guidec|*xlc*|ecc|pathcc|orcc|armclang]."
         echo "-fortran=<compiler> ..................... specify the Fortran compiler."
@@ -730,6 +732,8 @@ for arg in "$@"; do
         #echo "-rocprofiler=<dir> .............. Specify location of ROCm rocprofiler."
         #echo "-rocprofilerinc=<dir> .... Specify location of rocprofiler include dir."
         #echo "-rocprofilerlibrary=<library> .... Specify name of rocprofiler library."
+        echo "-roctracer=<dir> .................. Specify location of ROCm roctracer."
+        echo "-hip=<dir> .................... Specify location of ROCm HIP directory."
         echo "-hpctoolkit-src-dir=<dir> .......... Specify patched HPCToolkit source."
         echo "-hpctoolkit-install-dir=<dir> . Specify patched HPCToolkit Install dir."
         echo "-scalasca=<dir>  ................ Specify location of SCALASCA package."
@@ -1102,6 +1106,8 @@ zeptodir=
 cuda=no
 rocm=no
 rocprofiler=no
+roctracer=no
+hip=no
 use_opencl=no
 use_openacc=no
 cupti=no
@@ -1123,7 +1129,7 @@ for arg in "$@"; do
 
 	-cc=*)
 	    myarg=`echo $arg | sed 's/-cc=//'`
-	    if [ $myarg = cc -o $myarg = gcc -o $myarg = gcc4 -o $myarg = gcc-5 -o $myarg = gcc-6 -o $myarg = gcc-7 -o $myarg = gcc-8 -o $myarg = KCC -o $myarg = pgcc -o $myarg = guidec -o $myarg = xlc -o $myarg = ecc -o $myarg = icc -o $myarg = powerpc64-linux-gcc -o $myarg = pathcc -o $myarg = fcc -o $myarg = orcc -o $myarg = opencc -o $myarg = qk-pgcc -o $myarg = scgcc -o $myarg = scpathcc -o $myarg = mips64el-gentoo-linux-gnu-gcc -o $myarg = powerpc64-bgq-linux-gcc -o $myarg = powerpc-bgp-linux-gcc -o $myarg = x86_64-w64-mingw32-gcc -o $myarg = mpiicc -o $myarg = mpifcc -o $myarg = mpifccpx -o $myarg = clang -o $myarg = bgclang -o $myarg = mpc_cc -o $myarg = mpc_icc -o $myarg = mpicc -o $myarg = mcc -o $myarg = oshcc -o $myarg = armclang ]
+	    if [ $myarg = cc -o $myarg = gcc -o $myarg = gcc4 -o $myarg = gcc-5 -o $myarg = gcc-6 -o $myarg = gcc-7 -o $myarg = gcc-8 -o $myarg = KCC -o $myarg = pgcc -o $myarg = guidec -o $myarg = xlc -o $myarg = ecc -o $myarg = icc -o $myarg = powerpc64-linux-gcc -o $myarg = pathcc -o $myarg = fcc -o $myarg = orcc -o $myarg = opencc -o $myarg = qk-pgcc -o $myarg = scgcc -o $myarg = scpathcc -o $myarg = mips64el-gentoo-linux-gnu-gcc -o $myarg = powerpc64-bgq-linux-gcc -o $myarg = powerpc-bgp-linux-gcc -o $myarg = x86_64-w64-mingw32-gcc -o $myarg = mpiicc -o $myarg = mpifcc -o $myarg = mpifccpx -o $myarg = clang -o $myarg = hcc -o $myarg = hipcc -o $myarg = bgclang -o $myarg = mpc_cc -o $myarg = mpc_icc -o $myarg = mpicc -o $myarg = mcc -o $myarg = oshcc -o $myarg = armclang ]
 	    then
 		c_compiler=$myarg
 
@@ -1136,7 +1142,7 @@ for arg in "$@"; do
 		testmp=`echo $myarg | sed -e 's/^mp//'`
 		if [ "y$testxlc" = "y$myarg"  -a "y$testmp" = "y$myarg" ]
 		then
-		    echo "WARNING: valid options for cc are 'cc', 'gcc', 'gcc4', 'gcc-*', 'KCC', 'guidec', '*xlc*', 'ecc', 'icc', 'pathcc', 'fcc', 'orcc', 'opencc', 'qk-pgcc', 'powerpc64-bgq-linux-gcc', 'powerpc-bgp-linux-gcc', 'x86_64-w64-mingw32-gcc', 'mcc', 'mpiicc', 'pgcc' , 'mpc_cc', 'mpc_icc', 'mpifcc', 'mpifccpx', 'clang', 'bgclang', 'mpicc', 'mcc', or 'oshcc'"
+		    echo "WARNING: valid options for cc are 'cc', 'gcc', 'gcc4', 'gcc-*', 'KCC', 'guidec', '*xlc*', 'ecc', 'icc', 'pathcc', 'fcc', 'orcc', 'opencc', 'qk-pgcc', 'powerpc64-bgq-linux-gcc', 'powerpc-bgp-linux-gcc', 'x86_64-w64-mingw32-gcc', 'mcc', 'mpiicc', 'pgcc' , 'mpc_cc', 'mpc_icc', 'mpifcc', 'mpifccpx', 'clang', 'hcc', 'hipcc', 'bgclang', 'mpicc', 'mcc', or 'oshcc'"
 		    #       exit 1
 		else
 		    if [ "y$testxlc" != "y$myarg" ]
@@ -1152,7 +1158,7 @@ for arg in "$@"; do
 
 	-c++=*)
 	    myarg=`echo $arg | sed 's/-c++=//'`
-	    if [ $myarg = CC -o $myarg = KCC -o $myarg = g++ -o $myarg = g++4 -o $myarg = g++-5 -o $myarg = g++-6 -o $myarg = g++-7 -o $myarg = g++-8 -o $myarg = cxx  -o $myarg = NCC -o $myarg = pgc++ -o $myarg = pgCC  -o $myarg = pgcpp -o $myarg = egcs -o $myarg = FCC -o $myarg = guidec++ -o $myarg = aCC -o $myarg = c++ -o $myarg = ecpc -o $myarg = icpc -o $myarg = powerpc64-linux-g++ -o $myarg = pathCC -o $myarg = orCC -o $myarg = openCC -o $myarg = qk-pgCC -o $myarg = scg++ -o $myarg = scpathCC -o $myarg = mips64el-gentoo-linux-gnu-g++ -o $myarg = powerpc-bgp-linux-g++ -o $myarg = powerpc64-bgq-linux-g++ -o $myarg = mpicxx  -o $myarg = x86_64-w64-mingw32-g++  -o $myarg = mpiicpc -o $myarg = mpiFCC -o $myarg = mpiFCCpx -o $myarg = mpc_cxx -o $myarg = mpc_icpc -o $myarg = clang++ -o $myarg = bgclang++ -o $myarg = mpicxx -o $myarg = mcxx -o $myarg = oshCC -o $myarg = oshc++ -o $myarg = oshcxx  -o $myarg = armclang++ ]
+	    if [ $myarg = CC -o $myarg = KCC -o $myarg = g++ -o $myarg = g++4 -o $myarg = g++-5 -o $myarg = g++-6 -o $myarg = g++-7 -o $myarg = g++-8 -o $myarg = cxx  -o $myarg = NCC -o $myarg = pgc++ -o $myarg = pgCC  -o $myarg = pgcpp -o $myarg = egcs -o $myarg = FCC -o $myarg = guidec++ -o $myarg = aCC -o $myarg = c++ -o $myarg = ecpc -o $myarg = icpc -o $myarg = powerpc64-linux-g++ -o $myarg = pathCC -o $myarg = orCC -o $myarg = openCC -o $myarg = qk-pgCC -o $myarg = scg++ -o $myarg = scpathCC -o $myarg = mips64el-gentoo-linux-gnu-g++ -o $myarg = powerpc-bgp-linux-g++ -o $myarg = powerpc64-bgq-linux-g++ -o $myarg = mpicxx  -o $myarg = x86_64-w64-mingw32-g++  -o $myarg = mpiicpc -o $myarg = mpiFCC -o $myarg = mpiFCCpx -o $myarg = mpc_cxx -o $myarg = mpc_icpc -o $myarg = clang++ -o $myarg = hcc -o $myarg = hipcc -o $myarg = bgclang++ -o $myarg = mpicxx -o $myarg = mcxx -o $myarg = oshCC -o $myarg = oshc++ -o $myarg = oshcxx  -o $myarg = armclang++ ]
 	    then
 		cxx_compiler=$myarg
                 if [  $cxx_compiler = mpc_cxx -o $cxx_compiler = mpc_icpc  ]
@@ -1166,7 +1172,7 @@ for arg in "$@"; do
 		testmp=`echo $myarg | sed -e 's/^mp//'`
 		if [ "y$testxlc" = "y$myarg" -a "y$testmp" = "y$myarg" ]
 		then
-		    echo "WARNING: valid options for c++ are 'CC', 'KCC', 'g++', 'g++4', '*xlC*', 'cxx' , 'NCC', 'egcs', 'pgCC', 'pgcpp', 'FCC', 'guidec++', 'aCC', 'ecpc', 'icpc', 'pathCC', 'c++', 'qk-pgCC', 'x86_64-w64-mingw32-g++', 'mpiicpc', 'mpiFCC', 'mpiFCCpx', 'orCC', 'openCC', 'mpc_cxx',  'mpc_icpc', 'clang++', 'bgclang++', 'mpicxx', 'mcxx', 'oshCC', oshcxx, 'oshc++', or 'armclang++' "
+		    echo "WARNING: valid options for c++ are 'CC', 'KCC', 'g++', 'g++4', '*xlC*', 'cxx' , 'NCC', 'egcs', 'pgCC', 'pgcpp', 'FCC', 'guidec++', 'aCC', 'ecpc', 'icpc', 'pathCC', 'c++', 'qk-pgCC', 'x86_64-w64-mingw32-g++', 'mpiicpc', 'mpiFCC', 'mpiFCCpx', 'orCC', 'openCC', 'mpc_cxx',  'mpc_icpc', 'clang++', 'hcc', 'hipcc', 'bgclang++', 'mpicxx', 'mcxx', 'oshCC', oshcxx, 'oshc++', or 'armclang++' "
 		    #       exit 1
 		else
 		    if [ "y$testxlc" != "y$myarg" ]
@@ -2547,6 +2553,31 @@ for arg in "$@"; do
 	    shift
 	    ;;
 
+	-hip=*)
+	    hipdir=`echo $arg | sed -e 's/-hip=//' -e 's/ /#/g'`
+            if [ ! -d $hipdir ]; then
+              echo  "Error: Cannot access hip directory $hipdir"
+              exit 1
+	    else
+	      fixmakeargs="$fixmakeargs hipdir=$hipdir HIP"
+              hip=yes
+              tauoptions="${tauoptions}-hip"
+            fi
+	    shift
+	    ;;
+	-roctracer=*)
+	    roctracerdir=`echo $arg | sed -e 's/-roctracer=//' -e 's/ /#/g'`
+            if [ ! -d $roctracerdir ]; then
+              echo  "Error: Cannot access roctracer directory $roctracerdir"
+              exit 1
+	    else
+	      fixmakeargs="$fixmakeargs roctracerdir=$roctracerdir ROCTRACER"
+              roctracer=yes
+              tauoptions="${tauoptions}-roctracer"
+            fi
+	    shift
+	    ;;
+
 	-rocprofiler=*)
 	    rocprofilerdir=`echo $arg | sed -e 's/-rocprofiler=//' -e 's/ /#/g'`
             if [ ! -d $rocprofilerdir ]; then
@@ -3127,7 +3158,7 @@ esac
 
 if [ "$c_compiler" != "" -a "$c_compiler" != "default" ]; then
     TAU_CCOM="$c_compiler"          # for 'archfind'
-    if [ "$c_compiler" = pgcc ]
+    if [ "$c_compiler" = pgcc -o "$c_compiler" = hcc -o "$c_compiler" = hipcc ]
     then
        TAU_CCOM=""
     fi
@@ -3668,7 +3699,7 @@ if [ "x$fortran_compiler" = "xno" ]; then
     fixmakeargs="$fixmakeargs NOFORTRAN"
 fi
 
-if [ $cxx_compiler = clang++ -o $cxx_compiler = bgclang++ ]; then
+if [ $cxx_compiler = clang++ -o $cxx_compiler = bgclang++ -o $cxx_compiler = hcc  -o $cxx_compiler = hipcc ]; then
     fixmakeargs="$fixmakeargs CLANG"
 fi
 
@@ -4118,7 +4149,7 @@ case $cxx_compiler in
 	echo "Default C++ compiler will be CC"
 	fixmakeargs="$fixmakeargs USE_CFRONT"
 	;;
-    *llvm*|*clang*)
+    *llvm*|*clang* | hcc | hipcc )
 	echo "Using CLANG Compilers"
         fixmakeargs="$fixmakeargs CLANG COMPINST_LLVM"
         tauoptions="${tauoptions}-clang"
@@ -4601,7 +4632,7 @@ case $cxx_compiler in
       		fixmakeargs="$fixmakeargs IBM_FORTRAN"
 
 		;;
-            *clang*)
+            *clang* | hcc | hipcc )
 		tauoptions="${tauoptions}-clang"
 		echo "Using CLANG Compilers"
 		fixmakeargs="$fixmakeargs CLANG"
