ROCm 6.2.0 introduced a lock to avoid multiple instances of rocprofiler (ROCm 6.2.4 has this lock). https://github.com/ROCm/rocprofiler/commits/a5192bb9b337a930b0179653ec8785336f92859e/src/core/profiling_lock.cpp
This change has introduced a racing condition where sometimes profiling applications with MPI and rocprofiler thows:

ERROR: rocprofiler_pool_open(),
A profiling instance already exists! Multiple profiling instances are not allowed.

This lock can be avoided using ONLY roctracer. Disabled rocprofiler by default when building for ROCm, rocprofiler or roctracer must be selected.

Tested for both ROCm 5.* and ROCm 6.*
Configuration example ROCm 5.*: -c++=hipcc -cc=amdclang -fortran=mpif90 -bfd=download -rocm=/opt/rocm-5.5.0 -roctracer=/opt/rocm-5.5.0/roctracer/ -mpi
Configuration example for ROCm 6.*: -c++=mpicxx -cc=mpicc -fortran=mpif90 -rocm=/opt/rocm-6.2.3 -roctracer=/opt/rocm-6.2.3 -mpi -bfd=download


Former-commit-id: 5df258e975df60480a4dfdfd64c121d505ff759f

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3188,16 +3188,16 @@ for arg in "$@"; do
 
         -rocm)
             rocmdir=/opt/rocm
-            #fixmakeargs="$fixmakeargs rocmdir=$rocmdir ROCM ROCPROFILER"
             fixmakeargs="$fixmakeargs rocmdir=$rocmdir ROCM"
             rocm=yes
-            rocprofiler=yes
+            echo $roctracer
             tauoptions="${tauoptions}-rocm"
             pthread=yes
             shift
             ;;
 
         -rocm=*)
+        echo $roctracer
             rocmdir=`echo $arg | sed -e 's/-rocm=//' -e 's/ /#/g'`
             if [ ! -d $rocmdir ]; then
               echo  "Error: Cannot access ROCm directory $rocmdir"
@@ -3206,23 +3206,21 @@ for arg in "$@"; do
               fixmakeargs="$fixmakeargs rocmdir=$rocmdir ROCM"
               rocm=yes
             fi
-            #fixmakeargs="$fixmakeargs ROCPROFILER"
-            rocprofiler=yes
             tauoptions="${tauoptions}-rocm"
             pthread=yes
             shift
             ;;
 
-	-rocm-core=*)
-	    rocmcore_dir=`echo $arg | sed -e 's/-rocm-core=//' -e 's/ /#/g'`
-	    if [ ! -d $rocmcore_dir ]; then
-              echo  "Error: Cannot access ROCm Core directory $rocmcore_dir"
-              exit 1
-	    fi
-	    shift
-	    ;;
-
-	-rocprofv2)
+    	-rocm-core=*)
+    	    rocmcore_dir=`echo $arg | sed -e 's/-rocm-core=//' -e 's/ /#/g'`
+    	    if [ ! -d $rocmcore_dir ]; then
+                  echo  "Error: Cannot access ROCm Core directory $rocmcore_dir"
+                  exit 1
+    	    fi
+    	    shift
+    	    ;;
+    
+    	-rocprofv2)
             fixmakeargs="$fixmakeargs ROCPROFILERV2"
             rocprofv2=yes
             tauoptions="${tauoptions}-rocprofv2"
