git sucks
Former-commit-id: 008dee937778fb607040f7c414ab35fc1dc60a0d

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -779,6 +779,7 @@ dwarf=no
 java=no
 openmp=no
 ompt=no
+omptlib=
 omptenabled=no
 xlsmp=no
 ibmxlc=no
@@ -1485,10 +1486,31 @@ for arg in "$@"; do
       openmp=yes
     shift
     ;;
+
+  -omptlib=*)
+      ompt=yes
+      omptfile=`echo $arg | sed -e 's/-omptlib=//'`
+      if [ ! -f $omptfile ]
+      then
+        echo "Error: Cannot access OpenMP runtime library $omptfile"
+        exit 1
+      fi
+      # split the ompt library path
+      omptdir=${omptfile%/*}
+      if [ ! -d $omptdir ]
+      then
+        echo "Error: Cannot access directory $omptdir"
+        exit 1
+      fi
+      omptlib="-Wl,-rpath=$omptdir#$omptfile"
+    shift
+    ;;
+
   -ompt*)
       ompt=yes
     shift
     ;;
+
   -xlsmp=*)
       xlsmp=yes
       xlsmpdir=`echo $arg | sed -e 's/-xlsmp=//'`
@@ -1973,7 +1995,6 @@ else
   fi
 fi
 
-
 # -- some functions
 
 configure_java () {
@@ -2170,6 +2191,9 @@ cp ${tauroot}/tools/src/common/resources/tau16x16.gif $JARTARGET
 # install the perl scripts for ebs post-processing in the bin dir
 cp ${tauroot}/tools/src/tau_ebs_process.pl $BINTARGET
 cp ${tauroot}/utils/ebs2otf/tau_ebs2otf.pl $BINTARGET
+
+# install post-mortem address translation tool
+cp ${tauroot}/tools/src/tau_resolve_addresses.py $BINTARGET
 
 case $machine in
     
@@ -2833,6 +2857,10 @@ if [ "$machine" = "apple" ] ; then
 	configure_perfexplorer
 	exit 0
     fi
+fi
+
+if [ $ompt = yes ]; then
+  fixmakeargs="$fixmakeargs TAU_OMPT omptlib=$omptlib"
 fi
 
 if [ $machine = bgq -o $machine = bgp -o $machine = bgl ] ; then
@@ -4521,10 +4549,20 @@ then
     if [ "x$oshcc_var" != "x" -a $? = 0 ]
     then
       openshmem_include_dir=`echo $oshcc_var | sed -e 's@bin/oshcc@include@g'`
-      if [ -r $openshmem_include_dir/mpp/shmem.h ] 
+      if [ -r $openshmem_include_dir/mpp/shmem.h -a -r $openshmem_include_dir/../bin/mpiexec_mpt ] 
       then
         shmemincargs="-I$openshmem_include_dir#-I$openshmem_include_dir/mpp"
         fixmakeargs="$fixmakeargs SGI_MPT_SHMEM"
+      else
+        if [ -r $oshcc_var ]
+        then 
+          openshmem=yes
+          if [ -r $openshmem_include_dir/mpp/shmem.h ] 
+          then
+            shmemincargs="-I$openshmem_include_dir#-I$openshmem_include_dir/mpp"
+          fi
+          fixmakeargs="$fixmakeargs OPENSHMEM"
+        fi
       fi
     fi
     if [ $catamount = yes ] 
@@ -6244,9 +6282,9 @@ fi
 ######################################################################
 # Install BFD if requested
 ######################################################################
-binutils=binutils-2.23.1
+binutils=binutils-2.23.2
 binutilstgz=$binutils.tar.gz
-binutilsurl=http://ftp.gnu.org/gnu/binutils/$binutilstgz
+binutilsurl=http://www.cs.uoregon.edu/research/paracomp/tau/tauprofile/dist/$binutilstgz
 if [ "x$bfddir" = xnone ]; then
 	echo "BFD disabled."
 	turnbfdoff=yes
@@ -6261,7 +6299,7 @@ if [ "x$bfd" = "xyes" -a ! "$turnbfdoff" = yes ] ; then
 			mkdir $tempdir
 			cd $tempdir
 			if [ "$machine" = "apple" ] ; then
-                            curl $binutilsurl > $binutilstgz
+                            curl -L $binutilsurl > $binutilstgz
 			else 
                             wget $binutilsurl
 			fi
@@ -6680,6 +6718,9 @@ fi
 ######################################################################
 # Check for TLS, or Thread Local Storage
 ######################################################################
+
+tlsfound=no
+
 if [ $openmp = yes ] ; then
   cat <<EOF > conftest_tls.cc
 __thread int number = -1;
@@ -6691,11 +6732,63 @@ EOF
   if $cxx_compiler $orig_useropt -c conftest_tls.cc 1> /dev/null 2>&1 ; then
       fixmakeargs="$fixmakeargs TLS_AVAILABLE"
       echo "yes"
+      tlsfound=yes
   else
       echo "no"
   fi
 
   /bin/rm -f conftest_tls.o conftest_tls.cc
+fi
+
+######################################################################
+# Check for declspec(thread) support
+######################################################################
+if [ $openmp = yes ] && [ $tlsfound = no ] ; then
+  cat <<EOF > conftest_dtls.cc
+__declspec(thread) int number = -1;
+int main() {
+  return number;
+}
+EOF
+  $echo "Checking for __declspec(thread) support... ${nnl}"
+  if $cxx_compiler $orig_useropt -c conftest_dtls.cc 1> /dev/null 2>&1 ; then
+      fixmakeargs="$fixmakeargs DTLS_AVAILABLE"
+      echo "yes"
+      tlsfound=yes
+  else
+      echo "no"
+  fi
+
+  /bin/rm -f conftest_dtls.o conftest_dtls.cc
+fi
+
+######################################################################
+# Check for pthread_getspecific() support
+######################################################################
+if [ $openmp = yes ] && [ $tlsfound = no ] ; then
+  cat <<EOF > conftest_pgs.cc
+#include "pthread.h"
+static pthread_key_t key;
+int number = 1;
+
+int main() {
+  pthread_key_create(&key, NULL);
+  pthread_setspecific(key, &number);
+  int *newnum;
+  newnum = (int*)pthread_getspecific(key);
+  return *newnum;
+}
+EOF
+  $echo "Checking for pthread_getspecific() support... ${nnl}"
+  if $cxx_compiler $orig_useropt -c conftest_pgs.cc 1> /dev/null 2>&1 ; then
+      fixmakeargs="$fixmakeargs PGS_AVAILABLE"
+      echo "yes"
+      tlsfound=yes
+  else
+      echo "no"
+  fi
+
+  /bin/rm -f conftest_pgs.o conftest_pgs.cc
 fi
 
 
@@ -6709,7 +6802,7 @@ fi
 # GOMP wrapping is only available for openmp
 if [ $openmp = yes ] ; then
 # GOMP wrapping is only available for GCC
-  if [ $c_compiler = gcc ] ; then
+  if [ $c_compiler = gcc ] || [ $machine = craycnl -a "x$PE_ENV" = xGNU ] ; then
 # GOMP wrapping is not compatible with Opari.
     if [ $opari = no ] ; then
 	  if [ $opari1 = no ] ; then
@@ -6783,9 +6876,10 @@ EOF
 				fi
 				rm -f opencl.cpp opencl.o
 			fi
-			if [ $cupti = no -a -f "$cudainclude/../extras/CUPTI/include/cupti_events.h" ] ; then
+			cudadir=`dirname $cudainclude`
+			if [ $cupti = no -a -f "$cudadir/extras/CUPTI/include/cupti_events.h" ] ; then
 				tauoptions="${tauoptions}-cupti"
-				cupti="$cudainclude/../extras/CUPTI"
+				cupti="$cudadir/extras/CUPTI"
 				fixmakeargs="$fixmakeargs CUPTI cuptiinclude=$cupti/include"
 				echo "Using CUPTI library found in $cupti."
 			fi
@@ -6866,9 +6960,12 @@ if [ -d $otfdir/include/otf2 ]; then
 else
   if [ $otf = yes ] ; then
     fixmakeargs="$fixmakeargs OTF otfdir=$otfdir"
-    if [ ! -d $otfdir/${architecture} ] ; then
+    if [ ! -d $otfdir/${architecture} -a -d $otfdir/src ] ; then
       fixmakeargs="$fixmakeargs OTFSRC"
     fi  
+    if [ -r $otfdir/lib/libopen-trace-format.a ]; then
+      fixmakeargs="$fixmakeargs OTFLIB_LONGNAME"
+    fi
   fi
 fi
 
@@ -6890,36 +6987,49 @@ if [ $ebs2otf = yes ] ; then
   if [ -f utils/ebs2otf/ebs2otf.so ] ; then
       touch utils/ebs2otf/ebs2otf.so
   fi
+  fixmakeargs="$fixmakeargs EBS2OTF "
   if [ $otf = yes ] ; then
-      echo "Warning: -otf option enables TAU Tracing as a default. EBS will only work with TAU profiles. Please make sure Profiles are enabled before use."
+    echo "Warning: -otf option enables TAU Tracing as a default. EBS will only work with TAU profiles. Please make sure Profiles are enabled before use."
+  fi
+fi
+if [ $otf = yes ] ; then
       if [ "$otflib" = "" ] ; then
-	  otflib="$otfdir/${architecture}/lib"
+        if [ -d $otfdir/lib ]; then 
+	      otflib="$otfdir/lib"
+        else 
+	      otflib="$otfdir/${architecture}/lib"
+        fi
 	  echo "OTF Library implicitly set to $otflib"
       fi
       if [ "$otfinc" = "" ] ; then
-	  otfinc="$otfdir/include"
+        if [ -r $otfdir/include/otf.h ]; then
+	      otfinc="$otfdir/include"
+        else 
+          if [ -r $otfdir/include/open-trace-format/otf.h ]; then
+	        otfinc="$otfdir/include/open-trace-format"
+          fi
+        fi
 	  echo "OTF Header directory implicitly set to $otfinc"
       fi
-  fi 
-  if [ ! -d $otflib ]
+    if [ ! -d $otflib ]
       then
       echo "Error: No available OTF support. Library not found at $otflib."
       exit 1
-  fi
-  if [ ! -d $otfinc ]
+    fi
+    if [ ! -d $otfinc ]
       then
       echo "Error: No available OTF support. Headers not found at $otfinc."
       exit 1
-  fi
-  if [ ! -f $otfinc/OTF_Version.h ] ; then
+    fi
+    if [ $ebs2otf = yes -a ! -f $otfinc/OTF_Version.h ] ; then
       echo "Error: OTF_Version.h cannot be found. EBS will not support this version of OTF."
       exit 1
       # *CWL* Need version control code here. Still trying to decide the
       #    best way about it. The above conditional will at least trim away
       #    ancient versions of OTF.
-  fi
+    fi
 
-  fixmakeargs="$fixmakeargs EBS2OTF otflib=$otflib otfinc=$otfinc"
+    fixmakeargs="$fixmakeargs otflib=$otflib otfinc=$otfinc"
 fi
 
 if [ $ebs_has_rt = yes ] ; then
