Checked minor and major version for java.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -990,11 +990,18 @@ for arg in "$@"; do
         exit 1
       fi 
       jv=`$jdkdir/bin/java -version 2>&1 | grep version | awk '{ print $3; }'| sed -e s/\"//g`
-    if [ `echo $jv | sed -e s/1.6\.*// | wc -c` -eq 1 ] || [ `echo $jv | sed -e s/1.7\.*// | wc -c` -eq 1 ]
-    then
-        echo "Error: Specify a JDK of version 1.5 or earlier"
-        exit 1
-    fi
+      eval major=${jv/./;minor=}
+      minor=`echo $minor | sed 's/\([0-9]*\).*/\1/g'`
+      echo "major = $major, minor = $minor"
+      if [ $major = 1 ]
+      then
+        if [ $minor -lt 5 ]
+        then
+          echo "Error: Specify a JDK of version 1.5 or later"
+          exit 1
+        fi
+      fi
+
     shift
     ;;
 
