Fixing broken SOS configure when directory specified.
Former-commit-id: 9bda5ecac5e5990a0373183df0b4375fbe13c15e

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -7952,8 +7952,10 @@ if [ "x$sos" = "xyes" ] ; then
     p=`pwd`
     cd $targetdir/$architecture/; clone "$sosurl" "$sosrepos"; installsos "$sosrepos"
   else
-    echo "Error: Cannot access SOS directory $sosdir"
-    exit 1   
+    if [ ! -d "$sosdir" ] ; then
+      echo "Error: Cannot access SOS directory $sosdir"
+      exit 1   
+	fi
   fi
 fi
 
