configure exits and gives an error if you try to configure both -PROFILEPHASE and -PROFILECALLPATH. Resolves issue [0000143].
git-svn-id: file:///mnt/fast/tau2git/svnroot/trunk/tau2@4955 a8e31b63-e6ca-409b-a01b-2eec1b506579

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1551,6 +1551,12 @@ if [ $phase = yes ]
   then
     fixmakeargs="$fixmakeargs PROFILECALLPATH PROFILEPHASE"
     tauoptions="${tauoptions}-phase"
+   if [ $callpath = yes ]
+   then
+     echo "ERROR: Incompatible options specified."
+     echo "You must choose between -PROFILECALLPATH and -PROFILEPHASE. You cannot choose both!!"
+     exit 1
+   fi
 fi
 
 if [ $setnode0 = yes -a $trace = no ]
