Configure test for CRAY. Halt configure if using the GPU measurement system on cray with any compiler env. other than GNU (cuda driver limitation).
Former-commit-id: 1b1d3af7027372ea26c05c702eab51ad2dcb4c97

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6009,6 +6009,11 @@ if [ $cuda = yes ] ; then
 			if [ -f "$cudainclude/CL/cl.h" ] ; then
 				fixmakeargs="$fixmakeargs OPENCL TAU_USE_GPU openclinclude=$cudainclude"
 			fi
+		else
+			if [ "$machine" == "craycnl" -a "$PE_ENV" != "GNU" ]; then
+				echo "ERROR: TAU's GPU measurement system is only available in the GNU compiler environment on CRAY. Please swap modules and reconfigure."
+				exit 1
+			fi
 		fi
 	else
 		echo "Error: Cannot find GPU headers, TAU currently supports either CUDA or OpenCL"
