-bfd=download now uses -prefix, so it will handle multiple arches as well as the tau -prefix.
git-svn-id: file:///mnt/fast/tau2git/svnroot/trunk/tau2@6802 a8e31b63-e6ca-409b-a01b-2eec1b506579

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -837,31 +837,6 @@ do
   -bfd=*)
       bfd=yes
       bfddir=`echo $arg | sed -e 's/-bfd=//'`
-      if [ "x$bfddir" = xdownload ] ; then
-	  bfddir=`pwd`/binutils-2.18
-	  if [ -r "$bfddir/lib/libbfd.a" ] ; then
-	      echo "BFD download already found, skipping"
-	  else
-	      mkdir .tmp
-	      cd .tmp
-	      wget http://www.cs.uoregon.edu/research/paracomp/tau/tauprofile/dist/binutils-2.18.tar.gz
-	      tar -xzf binutils-2.18.tar.gz
-	      cd binutils-2.18
-	      ./configure CFLAGS=-fPIC CXXFLAGS=-fPIC --prefix=$bfddir
-	      make && make install
-	      cd ..
-	      cd ..
-	      rm -rf .tmp
-	  fi
-      fi
-      fixmakeargs="$fixmakeargs bfdlink=-L$bfddir/lib#-L$bfddir/lib64"
-      fixmakeargs="$fixmakeargs bfdinclude=-I$bfddir/include"
-      if [ ! -d $bfddir ]
-      then
-          echo "Error: Cannot access BFD directory $bfddir"
-          exit 1
-      fi
-      shift
     ;;
 
   -perfinc=*)
@@ -1420,7 +1395,6 @@ do
 
   -prefix=*)
     tauprefix=`echo $arg | sed -e 's/-prefix=//' -e 's/ /_/g'`
-    echo "tauprefix =  $tauprefix "
     fixmakeargs="$fixmakeargs tauprefix=$tauprefix"
     shift
     ;;
@@ -1445,6 +1419,17 @@ do
     ;;
   esac
 done
+
+
+
+
+
+if [ ${tauprefix} = unknown ] ; then
+  targetdir=${tauroot}
+else
+  targetdir=${tauprefix}
+fi
+
 
 # -- some functions
 
@@ -1645,8 +1630,7 @@ esac
 
 make_directories () {
 
-if [ $tauprefix = unknown ] 
-then 
+if [ $tauprefix = unknown ] ; then 
   fixmakeargs="$fixmakeargs tauprefix=$tauroot"
   # make bin dir if it does not exist
   if [ ! -d ./$architecture ] 
@@ -1728,6 +1712,37 @@ if [ "x$detectarch" = "x" ]
 fi
 
 
+
+
+if [ "x$bfd" = "xyes" ] ; then
+    if [ "x$bfddir" = xdownload ] ; then
+	bfddir=$targetdir
+	if [ -r "$bfddir/lib/libbfd.a" ] ; then
+	    echo "BFD download already found, skipping"
+	else
+	    mkdir .tmp
+	    cd .tmp
+	    wget http://www.cs.uoregon.edu/research/paracomp/tau/tauprofile/dist/binutils-2.18.tar.gz
+	    tar -xzf binutils-2.18.tar.gz
+	    cd binutils-2.18
+	    ./configure CFLAGS=-fPIC CXXFLAGS=-fPIC --prefix=$bfddir
+	    make && make install
+	    cd ..
+	    cd ..
+	    rm -rf .tmp
+	fi
+    fi
+    fixmakeargs="$fixmakeargs bfdlink=-L$bfddir/lib#-L$bfddir/lib64"
+    fixmakeargs="$fixmakeargs bfdinclude=-I$bfddir/include"
+    if [ ! -d $bfddir ] ; then
+        echo "Error: Cannot access BFD directory $bfddir"
+        exit 1
+    fi
+    shift
+fi
+
+
+
 ###############################################################
 # if there are no arguments, GUESS at system configuration
 if [ $tauarch = unknown -o $tauarch = none ]
@@ -1764,12 +1779,6 @@ if [ $tauarch = unknown -o $tauarch = none ]
 fi
 
 
-if [ ${tauprefix} = unknown ]
-then
-  targetdir=${tauroot}
-else
-  targetdir=${tauprefix}
-fi
 
 
 # use -m32 when specifying 32 bit on an Opteron/EM64T
