Adding PerfSuite integration support
git-svn-id: file:///mnt/fast/tau2git/svnroot/trunk/tau2@6492 a8e31b63-e6ca-409b-a01b-2eec1b506579

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -428,6 +428,8 @@ compensate=no
 smarts=no
 pcl=no
 papi=no
+perfsuite=no
+perfsuitedir=
 bfd=no
 bfddir=
 perf=no
@@ -832,6 +834,20 @@ do
         exit 1
       fi
     shift
+    ;;
+
+  -perfsuite=*)
+      perfsuite=yes
+      perfsuitedir=`echo $arg | sed -e 's/-perfsuite=//'`
+      fixmakeargs="$fixmakeargs TAU_PERFSUITE"
+      fixmakeargs="$fixmakeargs perfsuitelink=-L$perfsuitedir/lib#-lpshwpc"
+      fixmakeargs="$fixmakeargs perfsuiteinclude=-I$perfsuitedir/include"
+      if [ ! -d $perfsuitedir ]
+      then
+          echo "Error: Cannot access PerfSuite directory $perfsuitedir"
+          exit 1
+      fi
+      shift
     ;;
 
   -bfd=*)
