Updated Opari to Opari2-1.0
Former-commit-id: accc8a33a0426d5005c0514a72228a8c63a69019

diff --git a/utils/opari2/Makefile.in b/utils/opari2/Makefile.in
--- a/utils/opari2/Makefile.in
+++ b/utils/opari2/Makefile.in
@@ -309,10 +309,10 @@ CLEANFILES = $(builddir)/user_provided_configure_args \
 	$(builddir)/mpi_compiler_suite_to_source $(am__append_1) \
 	$(am__append_2) doc/doxygen-user/main.dox
 DISTCLEANFILES = $(builddir)/config.summary
+DOC_SRC_DIR = $(srcdir)/doc
 
 ###############################################################################
 @SVN_CONTROLLED_TRUE@USER_DOC_DIR = $(top_distdir)$(ac_scorep_doxygen_distdir)/doc
-@SVN_CONTROLLED_FALSE@DOC_SRC_DIR = $(srcdir)/doc
 
 ###############################################################################
 SCOREP_RECURSIVE_TARGETS = $(am__append_3) check-build-recursive
@@ -781,10 +781,11 @@ ps: ps-recursive
 
 ps-am:
 
-uninstall-am: uninstall-local
-
+uninstall-am:
+	@$(NORMAL_INSTALL)
+	$(MAKE) $(AM_MAKEFLAGS) uninstall-hook
 .MAKE: $(RECURSIVE_CLEAN_TARGETS) $(RECURSIVE_TARGETS) ctags-recursive \
-	install-am install-strip tags-recursive
+	install-am install-strip tags-recursive uninstall-am
 
 .PHONY: $(RECURSIVE_CLEAN_TARGETS) $(RECURSIVE_TARGETS) CTAGS GTAGS \
 	all all-am am--refresh check check-am clean clean-generic \
@@ -801,21 +802,23 @@ uninstall-am: uninstall-local
 	installdirs installdirs-am maintainer-clean \
 	maintainer-clean-generic mostlyclean mostlyclean-generic pdf \
 	pdf-am ps ps-am tags tags-recursive uninstall uninstall-am \
-	uninstall-local
+	uninstall-hook
 
 
 prohibit-svn-files-in-dist:
 	@find $(top_distdir) -type d | grep "\.svn"; \
 	if [ $$? -eq 0 ]; then \
-            echo "ERROR: subversion files found in distrubution. This is usually caused by";  \
+            echo "ERROR: subversion files found in distribution. This is usually caused by";  \
             echo "referencing directories in EXTRA_DIST. Please specify the files that need"; \
             echo "to go into the distribution explicitly."; \
             exit 1; \
         fi
 
-@SVN_CONTROLLED_TRUE@doxygen-user-install:
+common-uninstall:
+	rm -rf $(DESTDIR)$(docdir)
+	rm -rf $(DESTDIR)$(datadir)/@PACKAGE_NAME@
 
-@SVN_CONTROLLED_TRUE@doxygen-user-uninstall:
+@SVN_CONTROLLED_TRUE@doxygen-user-install:
 
 @SVN_CONTROLLED_TRUE@doxygen-user-generate: doxygen-user-pdf doxygen-user-html-compress copy-revision-file-to-dist
 
@@ -824,11 +827,13 @@ prohibit-svn-files-in-dist:
 
 @SVN_CONTROLLED_TRUE@copy-revision-file-to-dist:
 @SVN_CONTROLLED_TRUE@	$(MKDIR_P) "$(distdir)/build-config/"
-@SVN_CONTROLLED_TRUE@	cp -p "$(srcdir)/build-config/REVISION" "$(distdir)/build-config/"
-@SVN_CONTROLLED_TRUE@	if grep -E [A-Z] "$(srcdir)/build-config/REVISION" ||                               \
-@SVN_CONTROLLED_TRUE@           grep "-" "$(srcdir)/build-config/REVISION"; then                                 \
-@SVN_CONTROLLED_TRUE@            echo "WARNING: distribution does not match a single, unmodified revision." >&2; \
-@SVN_CONTROLLED_TRUE@        fi
+@SVN_CONTROLLED_TRUE@	for i in REVISION REVISION_COMMON; do                                                   \
+@SVN_CONTROLLED_TRUE@	    cp -p "$(srcdir)/build-config/$$i" "$(distdir)/build-config/";                      \
+@SVN_CONTROLLED_TRUE@	    if grep -E [A-Z] "$(srcdir)/build-config/$$i" ||                                    \
+@SVN_CONTROLLED_TRUE@                grep "-" "$(srcdir)/build-config/$$i"; then                                     \
+@SVN_CONTROLLED_TRUE@                echo "WARNING: distribution does not match a single, unmodified revision." >&2; \
+@SVN_CONTROLLED_TRUE@            fi                                                                                  \
+@SVN_CONTROLLED_TRUE@        done
 
 @SVN_CONTROLLED_TRUE@doxygen-user-html-compress:
 @SVN_CONTROLLED_TRUE@	if test -d "$(USER_DOC_DIR)/html"; then                               \
@@ -878,10 +883,10 @@ prohibit-svn-files-in-dist:
 
 @SVN_CONTROLLED_FALSE@doxygen-user-install:
 @SVN_CONTROLLED_FALSE@	if test -f "$(DOC_SRC_DIR)/html.tar.gz"; then                            \
-@SVN_CONTROLLED_FALSE@            $(MKDIR_P) $(DESTDIR)$(pkgdatadir)/doc;                  \
+@SVN_CONTROLLED_FALSE@            $(MKDIR_P) $(DESTDIR)$(docdir);                  \
 @SVN_CONTROLLED_FALSE@            $(INSTALL_DATA) $(DOC_SRC_DIR)/html.tar.gz                           \
-@SVN_CONTROLLED_FALSE@                            $(DESTDIR)$(pkgdatadir)/doc/html.tar.gz; \
-@SVN_CONTROLLED_FALSE@	    cd $(DESTDIR)$(pkgdatadir)/doc;                          \
+@SVN_CONTROLLED_FALSE@                            $(DESTDIR)$(docdir)/html.tar.gz; \
+@SVN_CONTROLLED_FALSE@	    cd $(DESTDIR)$(docdir);                          \
 @SVN_CONTROLLED_FALSE@            tar xzvf html.tar.gz;                                                \
 @SVN_CONTROLLED_FALSE@	    rm -f html.tar.gz;                                                   \
 @SVN_CONTROLLED_FALSE@	fi
@@ -890,20 +895,19 @@ prohibit-svn-files-in-dist:
 @SVN_CONTROLLED_FALSE@            dirs=`find . -type d`;                                                              \
 @SVN_CONTROLLED_FALSE@            cd -;                                                                               \
 @SVN_CONTROLLED_FALSE@            for i in $$dirs; do                                                                 \
-@SVN_CONTROLLED_FALSE@                $(MKDIR_P) $(DESTDIR)$(pkgdatadir)/doc/$$i;                         \
+@SVN_CONTROLLED_FALSE@                $(MKDIR_P) $(DESTDIR)$(docdir)/$$i;                         \
 @SVN_CONTROLLED_FALSE@            done;                                                                               \
 @SVN_CONTROLLED_FALSE@	    cd $(DOC_SRC_DIR);                                                                  \
 @SVN_CONTROLLED_FALSE@            files=`find . -type f`;                                                             \
 @SVN_CONTROLLED_FALSE@            cd -;                                                                               \
 @SVN_CONTROLLED_FALSE@            for i in $$files; do                                                                \
-@SVN_CONTROLLED_FALSE@                $(INSTALL_DATA) $(DOC_SRC_DIR)/$$i $(DESTDIR)$(pkgdatadir)/doc/$$i; \
+@SVN_CONTROLLED_FALSE@                $(INSTALL_DATA) $(DOC_SRC_DIR)/$$i $(DESTDIR)$(docdir)/$$i; \
 @SVN_CONTROLLED_FALSE@            done;                                                                               \
-@SVN_CONTROLLED_FALSE@            rm -rf $(DESTDIR)$(pkgdatadir)/doc/doxygen-user;                        \
-@SVN_CONTROLLED_FALSE@            rm -rf $(DESTDIR)$(pkgdatadir)/doc/doxygen-dev;                         \
+@SVN_CONTROLLED_FALSE@            rm -rf $(DESTDIR)$(docdir)/doxygen-user;                        \
+@SVN_CONTROLLED_FALSE@            rm -rf $(DESTDIR)$(docdir)/doxygen-dev;                         \
 @SVN_CONTROLLED_FALSE@        fi
 
-@SVN_CONTROLLED_FALSE@doxygen-user-uninstall:
-@SVN_CONTROLLED_FALSE@	rm -rf $(DESTDIR)$(pkgdatadir)/doc
+@SVN_CONTROLLED_FALSE@copy-revision-file-to-dist:
 
 ###############################################################################
 
@@ -920,7 +924,7 @@ prohibit-svn-files-in-dist:
 
 bitten-copy-tarball-to-prefix: $(distdir).tar.gz
 	$(MKDIR_P) $(DESTDIR)$(prefix)
-	$(INSTALL_DATA) $(distdir).tar.gz $(DESTDIR)$(prefix)/
+	$(INSTALL_DATA) $(distdir).tar.gz $(DESTDIR)$(prefix)/$(PACKAGE)-latest.tar.gz
 
 bitten-print-environment:
 	env
@@ -986,8 +990,7 @@ install-exec-local:
 
 install-data-local: doxygen-user-install
 
-uninstall-local: doxygen-user-uninstall
-	rm -rf $(DESTDIR)$(datadir)/@PACKAGE_NAME@
+uninstall-hook: common-uninstall
 	rm -f  $(DESTDIR)$(bindir)/pomp2_parse_init_regions.awk
 
 # Tell versions [3.59,3.63) of GNU make to not export all variables.
