Cleanup tau_shmem_wrap.
Former-commit-id: 00adbe1c6d58f1ea49af6254e6dc220221af18c4

diff --git a/src/wrappers/shmem/openshmem/tau_shmem_wrap b/src/wrappers/shmem/openshmem/tau_shmem_wrap
--- a/src/wrappers/shmem/openshmem/tau_shmem_wrap
+++ b/src/wrappers/shmem/openshmem/tau_shmem_wrap
@@ -1,70 +1,42 @@
-#!/bin/sh
-usage()
-{
+#!/bin/bash
+
+if [ $# -lt 3 ] ; then
     cmd=`basename $0`
     echo ""
-    echo " $cmd - Generates a wrapper library that can intercept "
-    echo " at link time or at runtime OpenSHMEM routines specified in a header file"
-    echo " Usage: $cmd <headerfile> <library>  [-w (default) | -d | -r] -shmem=<dir> "
-    echo " -w (default): generates wrappers for re-linking the application"
-    echo " -d : generates wrappers by redefining routines during compilation in header files"
-    echo " -r : generates wrappers that may be pre-loaded using tau_exec at runtime"
-    echo " -shmem=<dir> : specifies the OpenSHMEM directory"
+    echo " Usage: $cmd <headerfile> <library> -shmem=<path>"
+    echo "   <headerfile> : SHMEM header file to parse, e.g. shmem.h"
+    echo "   <library>    : name of the library to generate, e.g. tau_shmem"
+    echo "   -shmem=<dir> : path to SHMEM libraries and header files"
     echo "NOTE: $cmd reads the TAU_MAKEFILE  environment variable to get PDT settings"
-    echo " Example: "
-#    echo " % $cmd tau_upcr.h -lm -gasnet=/usr/local/packages/gasnet-1.18.0 -gasnetconduit=mpi -upc=/usr/local/packages/gupc-4.7.0.2"
-    echo " % $cmd tau_shmem.h -lm -shmem=/usr/local/packages/shmem"
-    echo " generates a wrapper library that may be linked in using TAU_OPTIONS -optTauWrapFile=<wrapperdir>/link_options.tau"
-    echo "" 
+    echo ""
     exit 1
-}
-
-shmemdir=/usr/local/packages/openshmem
-runtime_specified=0;
-header_redirection_specified=0;
-headerfile=""
-library=""
-modarg=""
-if [ $# = 0 ] ; then
-    usage
 fi
 
-if [ $# -gt 1 ]; then
-  headerfile=$1
-  library=$2
-  shift;
-  shift;
-fi
-
-for arg in "$@"; do
-  case $arg in 
-    -r)
-      runtime_specified=1; 
-      shift; 
-      ;;
-    -d)
-      header_redirection_specified=1; 
-      shift; 
-      ;;
-    -shmem=*)
-      shmemdir=`echo $arg | sed -e 's/-shmem=//g'`
-      shift;
-      ;;
-  esac
-done
-
-if [ "x$TAU_MAKEFILE" = "x" ] ;then
+if [ -z "$TAU_MAKEFILE" ] ; then
   echo "ERROR: Please set the TAU_MAKEFILE environment variable."
   exit 1
 fi
 
-if [ ! -r $TAU_MAKEFILE ] ;then
+if [ ! -r $TAU_MAKEFILE ] ; then
   echo "ERROR: environment variable TAU_MAKEFILE is set but the file is not readable"
   exit 1
 fi
 
+headerfile="$1"
+library="$2"
+shmemdir=`echo "$3" | sed -e 's/-shmem=//g'`
+
 if [ ! -d "$shmemdir" ] ; then
-  echo "ERROR: invalid OpenSHMEM directory: $shmemdir"
+  echo "ERROR: invalid SHMEM directory: $shmemdir"
+  exit 1
+fi
+
+if [ -r "$shmemdir/lib64/libopenshmem.a" ] ; then
+  libshmem="$shmemdir/lib64/libopenshmem.a"
+elif [ -r "$shmemdir/lib/libopenshmem.a" ] ; then
+  libshmem="$shmemdir/lib/libopenshmem.a"
+else
+  echo "ERROR: Cannot locate libopenshmem.a in $shmemdir"
   exit 1
 fi
 
@@ -77,65 +49,27 @@ if [ ! -x $parser ]; then
   echo "ERROR: Can't execute $parser: Using PDT = $pdtdir, ARCH = $tauarch"
   exit 1
 fi
-baseheader=`basename $headerfile .h`
 
-#echo $parser $headerfile -DGASNET_SEQ -I$upcdir/include -DUPCRI_BUILDING_LIBUPCR=1 -I$gasnetdir/include -I$gasnetdir/include/$gasnetconduit -DGASNETT_USE_GCC_ATTRIBUTE_MAYALIAS
-#$parser $headerfile -DGASNET_SEQ -I$upcdir/include -I$gasnetdir/include -I$gasnetdir/include/$gasnetconduit -DGASNETT_USE_GCC_ATTRIBUTE_MAYALIAS
-echo $parser $headerfile -I$shmemdir/include
+echo "$parser $headerfile -I$shmemdir/include"
 $parser $headerfile -I$shmemdir/include
-#mv $baseheader.pdb $headerfile.pdb 
 
-#if [ $runtime_specified = 1 ] ; then
-#  runtimeopt='-r'
-#else
-#  if [ $header_redirection_specified = 1 ]; then
-#    runtimeopt=''
-#  else 
-#    runtimeopt='-w'
-#  fi
-#fi
-
-
-# Locate libopenshmem.a
-if [ -r "$shmemdir/lib64/libopenshmem.a" ] ; then
-  libshmem="$shmemdir/lib64/libopenshmem.a"
-elif [ -r "$shmemdir/lib/libopenshmem.a" ] ; then
-  libshmem="$shmemdir/lib/libopenshmem.a"
-else
-  echo "ERROR: Cannot locate libopenshmem.a in $shmemdir"
-  exit 1
-fi
-
-# Generate wr.c and wr_dynamic.c
-echo $basedir/bin/tau_wrap $headerfile.pdb $headerfile -o wr_dynamic.c -r $library $* -f select.tau --shmem
+# Generate wr_dynamic.c *BEFORE* wr.c or link_options.tau will be empty
+echo "$basedir/bin/tau_wrap $headerfile.pdb $headerfile -o wr_dynamic.c -r $library $* -f select.tau --shmem"
 $basedir/bin/tau_wrap $headerfile.pdb $headerfile -o wr_dynamic.c -r $library $* -f select.tau --shmem
-echo $basedir/bin/tau_wrap $headerfile.pdb $headerfile -o wr.c -w $library $* -f select.tau --shmem
+
+# Generate wr.c
+echo "$basedir/bin/tau_wrap $headerfile.pdb $headerfile -o wr.c -w $library $* -f select.tau --shmem"
 $basedir/bin/tau_wrap $headerfile.pdb $headerfile -o wr.c -w $library $* -f select.tau --shmem
 
 dirname=`basename ${headerfile} .h`_wrapper
 
-# Fix the Makefile with the correct smp args.
-#sed -e "s@^EXTRA_FLAGS=@EXTRA_FLAGS=-DGASNET_SEQ -I$upcdir/include -I$gasnetdir/include -I$gasnetdir/include/$gasnetconduit -DGASNETT_USE_GCC_ATTRIBUTE_MAYALIAS @g" $dirname/Makefile > $dirname/Makefile~
-#mv -f $dirname/Makefile~ $dirname/Makefile
-
-# Link the object file directly.
+# Fix linker options for installation
 echo -n "-L$basedir/lib -lTAU_shmem_wrap" >> $dirname/link_options.tau
-#sed -e "s@WRAPPER_LIBRARY@$basedir/lib/wrappers/shmem/tau_shmem_wrap_static.o@" $dirname/link_options.tau.master > $dirname/link_options.tau
 
-# Build and install
-cd $dirname
-make
-cd ..
-rm -f ${headerfile}.pdb
+# Build and install the wrapper
+make -C "$dirname"
 mkdir -p $basedir/lib/wrappers/shmem
-echo cp $dirname/link_options.tau $basedir/lib/wrappers/shmem
-cp $dirname/link_options.tau $basedir/lib/wrappers/shmem
-echo cp $dirname/tau_shmem_wrap_static.o $basedir/lib/wrappers/shmem
-cp $dirname/tau_shmem_wrap_static.o $basedir/lib/wrappers/shmem
-echo cp $dirname/tau_shmem_wrap_dynamic.o $basedir/lib/wrappers/shmem
-cp $dirname/tau_shmem_wrap_dynamic.o $basedir/lib/wrappers/shmem
+cp -fv $dirname/link_options.tau $basedir/lib/wrappers/shmem
+cp -fv $dirname/libtau_shmem_wrap.so $basedir/lib/libTAUsh_shmem_wrap.so
+cp -fv $dirname/libtau_shmem_wrap.a $basedir/lib/libTAU_shmem_wrap.a
 
-echo cp $dirname/libtau_shmem_wrap.so $basedir/lib/libTAUsh_shmem_wrap.so
-cp $dirname/libtau_shmem_wrap.so $basedir/lib/libTAUsh_shmem_wrap.so
-echo cp $dirname/libtau_shmem_wrap.a $basedir/lib/TAU_shmem_wrap.a
-cp $dirname/libtau_shmem_wrap.a $basedir/lib/libTAU_shmem_wrap.a
