Replaced old opari2 with 2.0.8 (including slightly modified header files in include/opari2)
Former-commit-id: 745543d1760f70ee6b9f3c2cee7b628af9f411f2

diff --git a/utils/opari2/doc/Makefile.inc.am b/utils/opari2/doc/Makefile.inc.am
--- a/utils/opari2/doc/Makefile.inc.am
+++ b/utils/opari2/doc/Makefile.inc.am
@@ -9,13 +9,13 @@
 ## Copyright (c) 2009-2011,
 ## Gesellschaft fuer numerische Simulation mbH Braunschweig, Germany
 ##
-## Copyright (c) 2009-2011,
+## Copyright (c) 2009-2011, 2019-2020,
 ## Technische Universitaet Dresden, Germany
 ##
 ## Copyright (c) 2009-2011,
 ## University of Oregon, Eugene, USA
 ##
-## Copyright (c) 2009-2011, 2015,
+## Copyright (c) 2009-2011, 2015, 2019,
 ## Forschungszentrum Juelich GmbH, Germany
 ##
 ## Copyright (c) 2009-2011,
@@ -45,7 +45,7 @@
 ## make dist. When creating a distribution, the developer should make sure
 ## that she has doxygen and related tools e.g. pdflatex in PATH in order to
 ## generate a complete documentation, see also
-## vendor/common/build-config/m4/ac_scorep_doxygen.m4.
+## build-config/common/m4/ac_scorep_doxygen.m4.
 ##
 ## make install is ignorant of documentation issues in developer mode.
 ##
@@ -58,7 +58,7 @@ DOC_SRC_DIR = $(srcdir)/doc
 doxygen-uninstall:
 	rm -rf $(DESTDIR)$(docdir)
 
-if SVN_CONTROLLED #-----------------------------------------------------------
+if GIT_CONTROLLED
 
 USER_DOC_DIR = $(top_distdir)$(ac_scorep_doxygen_distdir)/doc
 
@@ -67,25 +67,25 @@ doxygen-user-install:
 doxygen-user-generate: doxygen-user-pdf doxygen-user-html-compress copy-revision-file-to-dist
 
 update-revision:
-	echo `svnversion $(srcdir)` > "$(srcdir)/build-config/REVISION"
+	@$(am__tty_colors); \
+	if $(AM_V_P); then echo "cd $(srcdir) && git describe --always --dirty > 'build-config/REVISION'"; \
+	else               echo "  GEN      $${mgn}$(srcdir)/build-config/REVISION$$std"; fi; \
+	cd $(srcdir) && git describe --always --dirty > "build-config/REVISION"
 
 copy-revision-file-to-dist:
-	$(MKDIR_P) "$(distdir)/build-config/"
-	for i in REVISION REVISION_COMMON; do                                                   \
-	    cp -p "$(srcdir)/build-config/$$i" "$(distdir)/build-config/";                      \
-	    if grep -E [A-Z] "$(srcdir)/build-config/$$i" ||                                    \
-                grep "-" "$(srcdir)/build-config/$$i"; then                                     \
-                echo "WARNING: distribution does not match a single, unmodified revision." >&2; \
-            fi                                                                                  \
-        done
+	@$(MKDIR_P) "$(distdir)/build-config/"
+	@cp -p "$(srcdir)/build-config/REVISION" "$(distdir)/build-config/"
+	@case `cat "$(distdir)/build-config/REVISION"` in *-dirty)                           \
+            echo >&2 "WARNING: distribution does not match a single, unmodified revision.";; \
+        esac
 
 doxygen-user-html-compress:
-	if test -d "$(USER_DOC_DIR)/html"; then                               \
-	    cd "$(USER_DOC_DIR)"; tar czvf html.tar.gz html; rm -rf html/;    \
+	$(AM_V_at)if test -d "$(USER_DOC_DIR)/html"; then                     \
+	    cd "$(USER_DOC_DIR)"; tar czf html.tar.gz html; rm -rf html/;    \
 	fi
 
 doxygen-project-number: update-revision
-	echo "PROJECT_NUMBER = \"@PACKAGE_VERSION@ (revision `cat $(srcdir)/build-config/REVISION`)\"" > doc/doxygen-project-number.cfg
+	$(AM_V_at)echo "PROJECT_NUMBER = \"@PACKAGE_VERSION@ (revision `cat $(srcdir)/build-config/REVISION`)\"" > doc/doxygen-project-number.cfg
 
 CLEANFILES += doc/doxygen-project-number.cfg
 
@@ -93,51 +93,72 @@ doxygen-user-clean:
 	rm -rf $(USER_DOC_DIR)/*
 
 
-if HAVE_DOXYGEN #-----------------------------------------------------
+if HAVE_DOXYGEN
+
+OPARI2_V_DOXYGEN = $(opari2__v_DOXYGEN_@AM_V@)
+opari2__v_DOXYGEN_ = $(opari2__v_DOXYGEN_@AM_DEFAULT_V@)
+opari2__v_DOXYGEN_0 = @$(am__tty_colors); echo "  DOXYGEN  $${blu}$@$$std";
+opari2__v_DOXYGEN_1 =
+
+OPARI2_V_DEVNULL = $(opari2__v_DEVNULL_@AM_V@)
+opari2__v_DEVNULL_ = $(opari2__v_DEVNULL_@AM_DEFAULT_V@)
+opari2__v_DEVNULL_0 = >/dev/null 2>&1
+opari2__v_DEVNULL_1 =
 
 doxygen-user: doxygen-project-number doc/doxygen-user/main.dox doc/doxygen-user.cfg
-	$(MKDIR_P) "$(USER_DOC_DIR)/tags"
-	echo "OUTPUT_DIRECTORY = $(USER_DOC_DIR)" > doc/doxygen-user-at-make-time.cfg
-	echo "GENERATE_TAGFILE = $(USER_DOC_DIR)/tags/@PACKAGE@.tag" >> doc/doxygen-user-at-make-time.cfg
-	cat doc/doxygen-project-number.cfg doc/doxygen-user-at-make-time.cfg doc/doxygen-user.cfg > doc/doxygen-user-html.cfg
-	$(MKDIR_P) "$(USER_DOC_DIR)/html"
-	cp $(abs_srcdir)/doc/images/* $(USER_DOC_DIR)/html
-	$(DOXYGEN) doc/doxygen-user-html.cfg
+	$(AM_V_at)$(MKDIR_P) "$(USER_DOC_DIR)/tags"
+	$(AM_V_at)echo "OUTPUT_DIRECTORY = $(USER_DOC_DIR)" > doc/doxygen-user-at-make-time.cfg
+	$(AM_V_at)echo "GENERATE_TAGFILE = $(USER_DOC_DIR)/tags/@PACKAGE@.tag" >> doc/doxygen-user-at-make-time.cfg
+	$(AM_V_at)cat doc/doxygen-project-number.cfg doc/doxygen-user-at-make-time.cfg doc/doxygen-user.cfg > doc/doxygen-user-html.cfg
+	$(AM_V_at)$(MKDIR_P) "$(USER_DOC_DIR)/html"
+	$(AM_V_at)cp $(abs_srcdir)/doc/images/* $(USER_DOC_DIR)/html
+	$(AM_V_at)if $(AM_V_P); then echo "QUIET = NO"; \
+	else                         echo "QUIET = YES"; fi >>doc/doxygen-user-html.cfg
+	$(OPARI2_V_DOXYGEN)$(DOXYGEN) doc/doxygen-user-html.cfg
 
 CLEANFILES += doc/doxygen-user-html.cfg doc/doxygen-user-at-make-time.cfg doxygen.err
 
-else # i.e. ! HAVE_DOXYGEN -------------------------------------------
+else !HAVE_DOXYGEN
 
 doxygen-user:
 	echo "WARNING: doxygen not available. Cannot generate documentation." >&2
 
-endif # HAVE_DOXYGEN -------------------------------------------------
+endif !HAVE_DOXYGEN
 
-if HAVE_DOXYGEN_LATEX #-----------------------------------------------
+if HAVE_DOXYGEN_LATEX
+
+OPARI2_V_pdflatex    = $(opari2__v_pdflatex_@AM_V@)
+opari2__v_pdflatex_  = $(opari2__v_pdflatex_@AM_DEFAULT_V@)
+opari2__v_pdflatex_0 = -interaction batchmode
+opari2__v_pdflatex_1 = -interaction nonstopmode
 
 doxygen-user-pdf: doxygen-user
-	cat doc/doxygen-user-html.cfg > doc/doxygen-user-pdf.cfg
-	echo "ENABLED_SECTIONS = LATEX" >> doc/doxygen-user-pdf.cfg
-	echo "GENERATE_HTML    = NO"    >> doc/doxygen-user-pdf.cfg
-	cp $(abs_srcdir)/doc/doxygen-user/opari2.sty $(USER_DOC_DIR)/pdf/
-	cp $(DOC_SRC_DIR)/license.tex $(USER_DOC_DIR)/pdf/
-	-cp $(DOC_SRC_DIR)/images/project_logo.pdf $(USER_DOC_DIR)/pdf/
-	$(DOXYGEN) doc/doxygen-user-pdf.cfg
-	cd "$(USER_DOC_DIR)/pdf" && \
-	make &&                     \
-	mv refman.pdf ../ &&        \
-	rm -f * &&                  \
+	$(AM_V_at)cat doc/doxygen-user-html.cfg > doc/doxygen-user-pdf.cfg
+	$(AM_V_at)echo "ENABLED_SECTIONS = LATEX" >> doc/doxygen-user-pdf.cfg
+	$(AM_V_at)echo "GENERATE_HTML    = NO"    >> doc/doxygen-user-pdf.cfg
+	$(AM_V_at)cp $(DOC_SRC_DIR)/license.tex $(USER_DOC_DIR)/pdf/
+	-$(AM_V_at)cp $(DOC_SRC_DIR)/images/project_logo.pdf $(USER_DOC_DIR)/pdf/
+	$(AM_V_at)echo "LATEX_CMD_NAME = \"pdflatex -file-line-error $(OPARI2_V_pdflatex)\"" >>doc/doxygen-user-pdf.cfg
+	$(AM_V_at)if $(AM_V_P); then echo "QUIET = NO"; \
+	          else               echo "QUIET = YES"; \
+	                             echo "MAKEINDEX_CMD_NAME = \"makeindex -q\""; \
+	          fi >>doc/doxygen-user-pdf.cfg
+	$(OPARI2_V_DOXYGEN)$(DOXYGEN) doc/doxygen-user-pdf.cfg
+	$(AM_V_at)cd "$(USER_DOC_DIR)/pdf" && \
+	make $(OPARI2_V_DEVNULL) &&           \
+	mv refman.pdf ../ &&                  \
+	rm -f * &&                            \
 	mv ../refman.pdf @PACKAGE@.pdf
 
-else # i.e. ! HAVE_DOXYGEN_LATEX -------------------------------------
+else !HAVE_DOXYGEN_LATEX
 
 doxygen-user-pdf: doxygen-user
 	echo "WARNING: pdflatex not available. Cannot generate doxygen pdf documentation." >&2
 	if test -d "$(USER_DOC_DIR)/pdf"; then rm -rf "$(USER_DOC_DIR)/pdf"; fi
 
-endif # HAVE_DOXYGEN_LATEX -------------------------------------------
+endif !HAVE_DOXYGEN_LATEX
 
-else # i.e. ! SVN_CONTROLLED -----------------------------------------
+else !GIT_CONTROLLED
 
 doxygen-user-clean:
 
@@ -146,14 +167,14 @@ doxygen-user-generate:
 doxygen-user-pdf:
 
 doxygen-user-install:
-	if test -f "$(DOC_SRC_DIR)/html.tar.gz"; then                                   \
+	$(AM_V_at)if test -f "$(DOC_SRC_DIR)/html.tar.gz"; then                         \
             $(MKDIR_P) $(DESTDIR)$(docdir);                                             \
             $(INSTALL_DATA) $(DOC_SRC_DIR)/html.tar.gz $(DESTDIR)$(docdir)/html.tar.gz; \
-	    cd $(DESTDIR)$(docdir);                                                     \
-            tar xzvf html.tar.gz;                                                       \
-	    rm -f html.tar.gz;                                                          \
-	fi
-	if test -d "$(DOC_SRC_DIR)"; then                                                   \
+            cd $(DESTDIR)$(docdir);                                                     \
+            tar xzf html.tar.gz;                                                        \
+            rm -f html.tar.gz;                                                          \
+        fi
+	$(AM_V_at)if test -d "$(DOC_SRC_DIR)"; then                                         \
             cd $(DOC_SRC_DIR);                                                              \
             dirs="pdf tags";                                                                \
             cd -;                                                                           \
@@ -172,7 +193,7 @@ doxygen-user-install:
 
 copy-revision-file-to-dist:
 
-endif # SVN_CONTROLLED
+endif !GIT_CONTROLLED
                                                                              ##
                                                                              ##
 ###############################################################################
