Added = in -tool=<beacon|sos>
Former-commit-id: fc10c6b126830838b52b1458784bcde66ec09d34

diff --git a/examples/mm_sos/pycoolr b/examples/mm_sos/pycoolr
--- a/examples/mm_sos/pycoolr
+++ b/examples/mm_sos/pycoolr
@@ -6,7 +6,7 @@ config=
 
 usage()
 {
- echo "Usage: $0 [REQUIRED] [-tool <beacon|sos>] [OPTIONAL] [-config=full-path-to-config-file]" 1>&2;
+ echo "Usage: $0 [REQUIRED] [-tool=<beacon|sos>] [OPTIONAL] [-config=full-path-to-config-file]" 1>&2;
  exit 1;
 }
 
