tau_exec should check if darshan is in the environment
Former-commit-id: 496a3fd97b6de0c3acdd3cbd65825f20489f9332

diff --git a/tools/src/tau_exec b/tools/src/tau_exec
--- a/tools/src/tau_exec
+++ b/tools/src/tau_exec
@@ -3,6 +3,13 @@
 LANG="C"
 export LANG
 
+darshan_module_loaded=`env | grep LOADEDMODULES | grep darshan | wc -l`
+if [ $darshan_module_loaded -gt 0 ] ; then
+    echo "ERROR: Darshan is not compatible with TAU."
+    echo "Please unload any darshan modules before running tau_exec."
+    exit 1
+fi
+
 eval `tau-config`
 
 scriptname=`basename $0`
