When running ptts on Cray with ALPS, use %U and do all post-processing on rank 0.
Former-commit-id: ab2c3cd83b7142e60f1a4d2ddc45512eed9a21e2

diff --git a/tools/src/tau_exec b/tools/src/tau_exec
--- a/tools/src/tau_exec
+++ b/tools/src/tau_exec
@@ -878,7 +878,11 @@ else
       echo "ERROR: dryrun not implemented for ptts"
       exit 1
     fi
-    samplefile="$pttsprefix/sample.${node}.smp"
+    if [[ -z "${ALPS_APP_PE}" ]]; then
+      samplefile="$pttsprefix/sample.${node}.smp"
+    else
+      samplefile="$pttsprefix/sample%U.smp"
+    fi
     reportfile="$pttsprefix/report.${node}.tsr"
     reportlog="$pttsprefix/report_ts.${node}.log"
     # view-static_ts paths should be relative to $pttsprefix
@@ -897,23 +901,59 @@ else
     fi
     rm -rf "$samplefile" "$reportfile" "$reportlog" "$pttsprefix/$viewdir" "$pttsprefix/$viewlog"
     sample_ts $ts_sample_flags -o "$samplefile" -r $@
-    err=$? ; [ $err -eq 0 ] || exit $err
-    retval=$err
-    # Get the return code of the child process as the tau_exec return code
-    # Post-process samples
-    echo "PTTS($node): Postprocessing samples..."
-    report_ts $ts_report_flags -i "$samplefile" -o "$reportfile" >$reportlog 2>&1
-    err=$? ; [ $err -eq 0 ] || exit $err
-    # Generate report. view-static must be run in $pttsprefix
-    cd "$pttsprefix"
-    view-static_ts  -i "`basename $reportfile`" -o "$viewdir" >$viewlog 2>&1
-    err=$? ; [ $err -eq 0 ] || exit $err
-    cd "$OLDPWD"
-    # Clean up and package the report
-    rm -f "$samplefile" "$reportfile" "$reportlog" "$pttsprefix/$viewlog" "$pttsprefix/${viewdir}.html"
-    compress_ptts_report
-    if [ "$node" -eq 0 ] ; then
-      write_ptts_index
+    if [[ -z "${ALPS_APP_PE}" ]]; then
+      err=$? ; [ $err -eq 0 ] || exit $err
+      retval=$err
+      # Get the return code of the child process as the tau_exec return code
+      # Post-process samples
+      echo "PTTS($node): Postprocessing samples..."
+      report_ts $ts_report_flags -i "$samplefile" -o "$reportfile" >$reportlog 2>&1
+      err=$? ; [ $err -eq 0 ] || exit $err
+      # Generate report. view-static must be run in $pttsprefix
+      cd "$pttsprefix"
+      view-static_ts  -i "`basename $reportfile`" -o "$viewdir" >$viewlog 2>&1
+      err=$? ; [ $err -eq 0 ] || exit $err
+      cd "$OLDPWD"
+      # Clean up and package the report
+      rm -f "$samplefile" "$reportfile" "$reportlog" "$pttsprefix/$viewlog" "$pttsprefix/${viewdir}.html"
+      compress_ptts_report
+      if [ "$node" -eq 0 ] ; then
+        write_ptts_index
+      fi
+    else
+      if [ "$node" -eq 0 ] ; then
+        err=$? ; [ $err -eq 0 ] || exit $err
+        retval=$err
+        # Get the return code of the child process as the tau_exec return code
+        # Post-process samples
+        i=-1
+        while [ $i -lt $(($nodecount-1)) ] ; do
+          ((i++))
+          echo "PTTS($i): Postprocessing samples..."
+          report_ts $ts_report_flags -i "$pttsprefix/sample.${i}.smp" -o "$pttsprefix/report.${i}.tsr" >"$pttsprefix/report_ts.${i}.log" 2>&1
+          err=$?
+          if [ $err -ne 0 ] ; then
+            echo "PTTS($i): Error generating report.${i}.tsr"
+            retval=$(($retval+$err))
+            continue
+          fi
+          # Generate report. view-static must be run in $pttsprefix
+          cd "$pttsprefix"
+          view-static_ts  -i "report.${i}.tsr" -o "node_${i}" >"view-static_ts.${i}.log" 2>&1
+          if [ $err -ne 0 ] ; then
+            echo "PTTS($i): Error generating node_${i}"
+            retval=$(($retval+$err))
+            continue
+          fi
+          cd "$OLDPWD"
+          # Clean up and package the report
+          rm -f "$pttsprefix/sample.${i}.smp" "$pttsprefix/report.${i}.tsr" "$pttsprefix/report_ts.${i}.log" "$pttsprefix/view-static_ts.${i}.log" "$pttsprefix/node_${i}.html"
+        done
+        compress_ptts_report
+        write_ptts_index
+      else
+        retval=0
+      fi
     fi
   else
     $dryrun $@
