Added tau_exec -qsub mode for BGP:
qsub mode:
    Original:
      qsub -n 1 --mode smp -t 10 ./a.out
    With TAU:
      tau_exec -qsub -io -memory -- qsub -n 1 --mode smp -t 10 ./a.out


git-svn-id: file:///mnt/fast/tau2git/svnroot/trunk/tau2@8200 a8e31b63-e6ca-409b-a01b-2eec1b506579

diff --git a/tools/src/tau_exec b/tools/src/tau_exec
--- a/tools/src/tau_exec
+++ b/tools/src/tau_exec
@@ -20,6 +20,7 @@ usage()
     echo "Options:"
 
     echo "        -v       verbose mode"
+    echo "        -qsub    Use qsub mode (see below)"
     echo "        -io      track I/O"
     echo "        -memory  track memory"
     options=`tau-config --list-options`
@@ -33,6 +34,12 @@ usage()
     echo "Example:"
     echo "    mpirun -np 2 tau_exec -io ./ring"
     echo ""
+    echo "qsub mode:"
+    echo "    Original:"
+    echo "      qsub -n 1 --mode smp -t 10 ./a.out"
+    echo "    With TAU:"
+    echo "      tau_exec -qsub -io -memory -- qsub -n 1 --mode smp -t 10 ./a.out"
+    echo ""
     exit
 }
 
@@ -41,8 +48,8 @@ if [ $# = 0 ] ; then
 fi
 
 
-dryrun="false"
-processT="false"
+dryrun=false
+processT=false
 TauOptions=""
 TauOptionsExclude=""
 verbose=false
@@ -50,6 +57,7 @@ binding_specified=""
 binding_options=""
 track_io=false
 track_memory=false
+qsub_mode=false
 TAU_PAPI_DEFAULT_DOMAIN=PAPI_DOM_USER
 
 
@@ -57,7 +65,7 @@ for arg in "$@" ; do
   # Thanks to Bernd Mohr for the following that handles quotes and spaces (see configure for explanation)
   modarg=`echo "x$arg" | sed -e 's/^x//' -e 's/"/\\\"/g' -e s,\',%@%\',g -e 's/%@%/\\\/g' -e 's/ /\\\ /g'`
 
-  if [ "$processT" = "true" ] ; then
+  if [ "$processT" = true ] ; then
       binding_options=`echo $binding_options $arg | sed -e 's/,/ /g' | tr '[A-Z]' '[a-z]'`
       processT="false"
       shift
@@ -78,12 +86,16 @@ for arg in "$@" ; do
 	      track_memory=true
 	      shift
 	      ;;
+          -qsub)
+              qsub_mode=true
+	      shift
+	      ;;
 	  -s)
 	      dryrun=true
 	      shift
 	      ;;
 	  -V)
-	      echo '$Id: tau_exec,v 1.11 2010/05/06 17:33:34 amorris Exp $';
+	      echo '$Id: tau_exec,v 1.12 2010/05/12 21:45:26 amorris Exp $';
 	      exit 0;
 	      ;;
 	  -T)
@@ -181,14 +193,15 @@ else
   TAUEX_LD_PRELOAD=$BASEDIR/lib/$theBinding/libTAU$TAU_SHLIBX:$LD_PRELOAD
 fi
 
-if [ $track_memory = "true" ] ; then
-    # Add the memory wrapper library to the LD_PRELOAD list
-    TAUEX_LD_PRELOAD=$BASEDIR/lib/$theBinding/libTAU-memorywrap$TAU_SHLIBX:$TAUEX_LD_PRELOAD
-fi
 
 if [ $track_io = "true" ] ; then
     # Add the io wrapper library to the LD_PRELOAD list
     TAUEX_LD_PRELOAD=$BASEDIR/lib/$theBinding/libTAU-iowrap$TAU_SHLIBX:$TAUEX_LD_PRELOAD
+fi
+
+if [ $track_memory = "true" ] ; then
+    # Add the memory wrapper library to the LD_PRELOAD list
+    TAUEX_LD_PRELOAD=$BASEDIR/lib/$theBinding/libTAU-memorywrap$TAU_SHLIBX:$TAUEX_LD_PRELOAD
 fi
 
 
@@ -199,27 +212,29 @@ else
 fi
 
 
-prog="$1"
-if [ ! -x "$prog" ] ; then
-    prog=`which $prog 2>/dev/null`
-fi
+if [ $qsub_mode = false ]; then
+    prog="$1"
+    if [ ! -x "$prog" ] ; then
+	prog=`which $prog 2>/dev/null`
+    fi
+    
+    if [ ! -x "$prog" ] ; then
+	echo "tau_exec: $1: command not found"
+	exit
+    fi 
 
-if [ ! -x "$prog" ] ; then
-    echo "tau_exec: $1: command not found"
-    exit
-fi 
-
-$TAU_LDD "$prog" 2>/dev/null | grep libTAU$TAU_SHLIBX &> /dev/null
-if [ $? == 1 ] ; then
-    nm "$prog" 2>/dev/null | grep Tau_init &> /dev/null
+    $TAU_LDD "$prog" 2>/dev/null | grep libTAU$TAU_SHLIBX &> /dev/null
     if [ $? == 1 ] ; then
-	echoIfVerbose "TAU: Detected uninstrumented binary, adding TAU preload wrapper"
-	TAUEX_LD_PRELOAD=$TAUEX_LD_PRELOAD:$BASEDIR/lib/$theBinding/libTAU-preload$TAU_SHLIBX
-    else
+	nm "$prog" 2>/dev/null | grep Tau_init &> /dev/null
+	if [ $? == 1 ] ; then
+	    echoIfVerbose "TAU: Detected uninstrumented binary, adding TAU preload wrapper"
+	    TAUEX_LD_PRELOAD=$TAUEX_LD_PRELOAD:$BASEDIR/lib/$theBinding/libTAU-preload$TAU_SHLIBX
+	else
+	    echoIfVerbose "TAU: Detected instrumented binary, not using TAU preload wrapper"
+	fi
+    else 
 	echoIfVerbose "TAU: Detected instrumented binary, not using TAU preload wrapper"
     fi
-else 
-    echoIfVerbose "TAU: Detected instrumented binary, not using TAU preload wrapper"
 fi
 
 
@@ -238,29 +253,43 @@ if [ $verbose = "true" ] ; then
 fi
 
 
-# execute the program
-if [ $dryrun = "true" ]; then
-    if [ $apple = 1 ]; then
-      echo "export DYLD_LIBRARY_PATH=$TAUEX_LD_LIBRARY_PATH"
-      echo "export DYLD_INSERT_LIBRARIES=$TAUEX_LD_PRELOAD"
-      echo "export DYLD_FORCE_FLAT_NAMESPACE="
+
+if [ $qsub_mode = true ] ; then
+    cmd="$@"
+    # don't use the current LD_LIBRARY_PATH or it will screw things up for the backend
+    TAUEX_LD_LIBRARY_PATH=$BASEDIR/lib/$theBinding
+    env_option="--env LD_PRELOAD=$TAUEX_LD_PRELOAD:LD_LIBRARY_PATH=$TAUEX_LD_LIBRARY_PATH"
+    newCmd=`echo $cmd | sed -e 's/qsub//'`
+    if [ $dryrun = "true" ]; then
+	echo qsub $env_option $newCmd
     else
-      echo "export LD_LIBRARY_PATH=$TAUEX_LD_LIBRARY_PATH"
-      echo "export LD_PRELOAD=$TAUEX_LD_PRELOAD"
+	qsub $env_option $newCmd
     fi
-    echo "$@"
-    exit 0;
 else
-    if [ $apple = 1 ]; then
-      export DYLD_LIBRARY_PATH=$TAUEX_LD_LIBRARY_PATH
-      export DYLD_INSERT_LIBRARIES=$TAUEX_LD_PRELOAD
-      export DYLD_FORCE_FLAT_NAMESPACE=""
+
+    if [ $dryrun = "true" ]; then
+	if [ $apple = 1 ]; then
+	    echo "export DYLD_LIBRARY_PATH=$TAUEX_LD_LIBRARY_PATH"
+	    echo "export DYLD_INSERT_LIBRARIES=$TAUEX_LD_PRELOAD"
+	    echo "export DYLD_FORCE_FLAT_NAMESPACE="
+	else
+	    echo "export LD_LIBRARY_PATH=$TAUEX_LD_LIBRARY_PATH"
+	    echo "export LD_PRELOAD=$TAUEX_LD_PRELOAD"
+	fi
+	echo "$@"
+	exit 0;
     else
-      export LD_LIBRARY_PATH=$TAUEX_LD_LIBRARY_PATH
-      export LD_PRELOAD=$TAUEX_LD_PRELOAD
+	if [ $apple = 1 ]; then
+	    export DYLD_LIBRARY_PATH=$TAUEX_LD_LIBRARY_PATH
+	    export DYLD_INSERT_LIBRARIES=$TAUEX_LD_PRELOAD
+	    export DYLD_FORCE_FLAT_NAMESPACE=""
+	else
+	    export LD_LIBRARY_PATH=$TAUEX_LD_LIBRARY_PATH
+	    export LD_PRELOAD=$TAUEX_LD_PRELOAD
+	fi
+	"$@"
+	retval=$?
+	unset LD_PRELOAD
+	exit $retval
     fi
-    "$@"
-    retval=$?
-    unset LD_PRELOAD
-    exit $retval
 fi
