Check if TAU was configured with l0 metric support if ZET_ENABLE_METRICS is enabled, show an error if not supported.
Former-commit-id: 67d794938455afabbe99d87a07aa4b4068e69060

diff --git a/tools/src/tau_exec b/tools/src/tau_exec
--- a/tools/src/tau_exec
+++ b/tools/src/tau_exec
@@ -1140,6 +1140,16 @@ if [ $track_l0 = "true" ]; then
 
 fi
 
+if [ -v "$ZET_ENABLE_METRICS" ]; then
+  if [[ "$ZET_ENABLE_METRICS" != "0" ]]; then
+     isl0metrics=`echo $theBinding | grep l0metrics`
+     if [ "x$isl0metrics" == "x"  ]; then
+        echo "ERROR: TAU was not configured with support for L0 Metrics, reconfigure TAU or remove the profiling of L0 metrics"
+        exit 1
+     fi
+  fi
+fi
+
 if [ $track_rocm = "true" ] ; then
   if [ `echo $TAU_METRICS | grep -v "TAUGPU_TIME"` ]; then
     if [ `echo $TAU_METRICS | grep "TIME"` ]; then
