Add memory debugger command line options.
tau_compiler.sh: -optMemDbg and -optTrackMemoryLeaks are synonymous.
tau_exec: Added new -memory_debug option that does everything -memory
does but also sets TAU_TRACK_MEMORY_LEAKS=1 and
TAU_MEMDBG_PROTECT_ABOVE=1


Former-commit-id: b0f8e1c9f3df82547101b3c987e8eff1ba6ecb52

diff --git a/tools/src/tau_exec b/tools/src/tau_exec
--- a/tools/src/tau_exec
+++ b/tools/src/tau_exec
@@ -20,15 +20,16 @@ usage()
 # Common options first
     echo "Options:"
 
-    echo "        -v       verbose mode"
-    echo "        -qsub    Use qsub mode (BG/P only, see below)"
-    echo "        -io      track I/O"
-    echo "        -memory  track memory"
-    echo "        -cuda    track GPU events via CUDA"
-    echo "        -cupti   track GPU events via CUPTI (Also see env. variable TAU_CUPTI_API)"
-    echo "        -opencl  track GPU events via OpenCL"
-    echo "        -armci   track ARMCI events via PARMCI"
-    echo "        -ebs     enable Event-based sampling"
+    echo "        -v            verbose mode"
+    echo "        -qsub         Use qsub mode (BG/P only, see below)"
+    echo "        -io           track I/O"
+    echo "        -memory       track memory allocation/deallocation"
+    echo "        -memory_debug enable memory debugger"
+    echo "        -cuda         track GPU events via CUDA"
+    echo "        -cupti        track GPU events via CUPTI (Also see env. variable TAU_CUPTI_API)"
+    echo "        -opencl       track GPU events via OpenCL"
+    echo "        -armci        track ARMCI events via PARMCI"
+    echo "        -ebs          enable Event-based sampling"
     echo "        -ebs_period=<count> sampling period (default 1000)"
     echo "        -ebs_source=<counter> counter (default itimer)"
     options=`tau-config --list-options`
@@ -55,6 +56,14 @@ usage()
     echo "    With TAU:"
     echo "      tau_exec -qsub -io -memory -- qsub -n 1 --mode smp -t 10 ./a.out"
     echo ""
+    echo "Memory Debugging:"
+    echo "    -memory option:"
+    echo "      Loads the memory debugger but only tracks allocation/deallocation"
+    echo "    -memory_debug option:"
+    echo "      Loads detects memory leaks, checks for invalid alignment, and checks for"
+    echo "      array overflow.  This is exactly like setting TAU_TRACK_MEMORY_LEAKS=1"
+    echo "      and TAU_MEMDBG_PROTECT_ABOVE=1 and running with -memory"
+    echo ""
     exit
 }
 
@@ -72,6 +81,7 @@ binding_specified=""
 binding_options=""
 track_io=false
 track_memory=false
+memory_debug=false
 track_cuda=false
 track_cupti=false
 track_opencl=false
@@ -107,6 +117,10 @@ for arg in "$@" ; do
 	      ;;
 	  -memory)
 	      track_memory=true
+	      shift
+	      ;;
+	  -memory_debug)
+	      memory_debug=true
 	      shift
 	      ;;
 	  -cuda)
@@ -270,7 +284,7 @@ if [ $track_io = "true" ] ; then
     export LD_BIND_NOW=1
 fi
 
-if [ $track_memory = "true" ] ; then
+if [ $track_memory = "true" ] || [ $memory_debug = "true" ] ; then
     # Add the memory wrapper library to the LD_PRELOAD list
     TAUEX_LD_PRELOAD=$BASEDIR/lib/$theBinding/libTAU-memorywrap$TAU_SHLIBX:$TAUEX_LD_PRELOAD
     #use the auditor
@@ -301,7 +315,7 @@ if [ $track_cupti = "true" ] ; then
 			echo "ERROR: CUPTI library not found. Please ensure that 'cupti' is on the list of bindings specified with the '-T' option."
 			exit
 		else
-			# Add the memory wrapper library to the LD_PRELOAD list
+			# Add the wrapper library to the LD_PRELOAD list
 			TAUEX_LD_PRELOAD=$BASEDIR/lib/$theBinding/libTAU-CUact.so:$TAUEX_LD_PRELOAD
 			TAUEX_LD_PRELOAD=$BASEDIR/lib/$theBinding/libTAU-CUpti.so:$TAUEX_LD_PRELOAD
 			TAUEX_LD_PRELOAD=$BASEDIR/lib/$theBinding/libTAU-CudaQP.so:$TAUEX_LD_PRELOAD
@@ -443,40 +457,49 @@ if [ $qsub_mode = true ] ; then
     else
 	qsub $env_option $newCmd
     fi
+    
 else
 
     if [ $dryrun = "true" ]; then
-	if [ $track_memory = "true" ] ; then
-			echo "export LD_BIND_NOW=1"
-	fi
-	if [ $track_io = "true" ] ; then
-			echo "export LD_BIND_NOW=1"
-	fi
-
-	if [ $apple = 1 ]; then
-	    echo "export DYLD_LIBRARY_PATH=$TAUEX_LD_LIBRARY_PATH"
-	    echo "export DYLD_INSERT_LIBRARIES=$TAUEX_LD_PRELOAD"
-	    echo "export DYLD_FORCE_FLAT_NAMESPACE="
-	else
-	    echo "export LD_LIBRARY_PATH=$TAUEX_LD_LIBRARY_PATH"
-	    echo "export LD_AUDIT=$TAUEX_LD_AUDITOR"
-	    echo "export LD_PRELOAD=$TAUEX_LD_PRELOAD"
-	fi
-	echo "$@"
-	exit 0;
+      if [ $track_memory = "true" ] || [ $memory_debug = "true" ] ; then
+        echo "export LD_BIND_NOW=1"
+      fi
+      if [ $track_io = "true" ] ; then
+        echo "export LD_BIND_NOW=1"
+      fi
+      if [ $apple = 1 ]; then
+        echo "export DYLD_LIBRARY_PATH=$TAUEX_LD_LIBRARY_PATH"
+        echo "export DYLD_INSERT_LIBRARIES=$TAUEX_LD_PRELOAD"
+        echo "export DYLD_FORCE_FLAT_NAMESPACE="
+      else
+        echo "export LD_LIBRARY_PATH=$TAUEX_LD_LIBRARY_PATH"
+        echo "export LD_AUDIT=$TAUEX_LD_AUDITOR"
+        echo "export LD_PRELOAD=$TAUEX_LD_PRELOAD"
+      fi
+      if [ $memory_debug = "true" ] ; then
+        echo "export TAU_TRACK_MEMORY_LEAKS=1"
+        echo "export TAU_MEMDBG_PROTECT_ABOVE=1"
+      fi
+      echo "$@"
+      exit 0;
+    elif [ $apple = 1 ]; then
+      export DYLD_LIBRARY_PATH=$TAUEX_LD_LIBRARY_PATH
+      export DYLD_INSERT_LIBRARIES=$TAUEX_LD_PRELOAD
+      export DYLD_FORCE_FLAT_NAMESPACE=""
     else
-	if [ $apple = 1 ]; then
-	    export DYLD_LIBRARY_PATH=$TAUEX_LD_LIBRARY_PATH
-	    export DYLD_INSERT_LIBRARIES=$TAUEX_LD_PRELOAD
-	    export DYLD_FORCE_FLAT_NAMESPACE=""
-	else
-	    export LD_LIBRARY_PATH=$TAUEX_LD_LIBRARY_PATH
-	    export LD_AUDIT=$TAUEX_LD_AUDITOR
-	    export LD_PRELOAD=$TAUEX_LD_PRELOAD
-	fi
-	"$@"
-	retval=$?
-	unset LD_PRELOAD
-	exit $retval
+      export LD_LIBRARY_PATH=$TAUEX_LD_LIBRARY_PATH
+      export LD_AUDIT=$TAUEX_LD_AUDITOR
+      export LD_PRELOAD=$TAUEX_LD_PRELOAD
     fi
+    if [ $memory_debug = "true" ] ; then
+      export TAU_TRACK_MEMORY_LEAKS=1
+      export TAU_MEMDBG_PROTECT_ABOVE=1
+    fi
+    
+    $@
+    retval=$?
+    unset LD_PRELOAD
+    exit $retval
+fi
+
 fi
