Completed this item:
Date: Sat, 31 May 2008 01:37:53 +0200
From: Philip Mucci <mucci@cs.utk.edu>
To: Alan Morris <amorris@cs.uoregon.edu>
Cc: tau-sicortex-support@paratools.com, Tushar Mohan <tmohan@sicortex.com>, Henry Hall <hlh@sicortex.com>
Subject: Re: [Tau-sicortex-support] TAU release, next OS "Andrea" freeze date approaching...

Ok, at least it should say, "No matching bindings for xxx,yyy,zzz in library dir <dir>". That would help debugging and let us
know what it is looking for. I want to know what it is matching against.

Phil

On May 30, 2008, at 8:22 PM, Alan Morris wrote:
> > > > - tauex: -v does not show it's attempt at finding a binding when none is found
> > > I'm not sure I understand.  Are you referring to the "Matching bindings:" output?  If there aren't any matching bindings,
> > > what would it list?  Do you want that string output regardless?
> >
> > It should list what it was hoping to find.
>
> All it's really doing is doing an 'ls' on the directory and grepping for the options the user specified (e.g. -T MPI,PTHREAD).
> Should we just spit back the list, MPI,PTHREAD?  I think what you want is for it to list out something like
> "shared-multiplecounters-mpi-vampirtrace-trace", but tauex does not actually construct that string.
>


git-svn-id: file:///mnt/fast/tau2git/svnroot/trunk/tau2@6005 a8e31b63-e6ca-409b-a01b-2eec1b506579

diff --git a/tools/src/tauex.in b/tools/src/tauex.in
--- a/tools/src/tauex.in
+++ b/tools/src/tauex.in
@@ -130,7 +130,7 @@ for arg in "$@" ; do
 	      shift
 	      ;;
 	  -V)
-	      echo '$Id: tauex.in,v 1.22 2008/05/28 19:34:44 amorris Exp $';
+	      echo '$Id: tauex.in,v 1.23 2008/06/03 20:57:27 amorris Exp $';
 	      exit 0;
 	      ;;
 	  -m)
@@ -210,8 +210,10 @@ if [ "x$binding_specified" = "x" ] ; then
     fi
     
     if [ "$SICORTEX" = "yes" ] ; then
+	bindingsdir=$PREFIX/lib64 
 	bindings=`ls $PREFIX/lib64 | grep TAU-shared`
     else
+	bindingsdir=$BASEDIR/lib 
 	bindings=`ls $BASEDIR/lib | grep shared`
     fi
     
@@ -246,7 +248,7 @@ if [ "x$binding_specified" = "x" ] ; then
     done
 
     if [ "x$theBinding" = "x" ] ; then
-	echo "Error: Couldn't find a matching TAU binding" >&2
+	echo "Error: No matching binding for '$TauOptions' in directory $bindingsdir" >&2
 	exit 1
     fi
 else
