Updated Opari to Opari2-1.0
Former-commit-id: def3384617c6ad9339437f7afe0bc0f18678808d

diff --git a/utils/opari2/vendor/common/build-config/Makefile.inc.am b/utils/opari2/vendor/common/build-config/Makefile.inc.am
--- a/utils/opari2/vendor/common/build-config/Makefile.inc.am
+++ b/utils/opari2/vendor/common/build-config/Makefile.inc.am
@@ -90,12 +90,17 @@ DISTCLEANFILES += $(builddir)/config.summary
 prohibit-svn-files-in-dist:
 	@find $(top_distdir) -type d | grep "\.svn"; \
 	if [ $$? -eq 0 ]; then \
-            echo "ERROR: subversion files found in distrubution. This is usually caused by";  \
+            echo "ERROR: subversion files found in distribution. This is usually caused by";  \
             echo "referencing directories in EXTRA_DIST. Please specify the files that need"; \
             echo "to go into the distribution explicitly."; \
             exit 1; \
         fi
 
+DOC_SRC_DIR = $(srcdir)/doc
+
+common-uninstall:
+	rm -rf $(DESTDIR)$(docdir)
+	rm -rf $(DESTDIR)$(datadir)/@PACKAGE_NAME@
 
 
 ###############################################################################
@@ -125,8 +130,6 @@ USER_DOC_DIR = $(top_distdir)$(ac_scorep_doxygen_distdir)/doc
 
 doxygen-user-install:
 
-doxygen-user-uninstall:
-
 doxygen-user-generate: doxygen-user-pdf doxygen-user-html-compress copy-revision-file-to-dist
 
 update-revision:
@@ -134,11 +137,13 @@ update-revision:
 
 copy-revision-file-to-dist:
 	$(MKDIR_P) "$(distdir)/build-config/"
-	cp -p "$(srcdir)/build-config/REVISION" "$(distdir)/build-config/"
-	if grep -E [A-Z] "$(srcdir)/build-config/REVISION" ||                               \
-           grep "-" "$(srcdir)/build-config/REVISION"; then                                 \
-            echo "WARNING: distribution does not match a single, unmodified revision." >&2; \
-        fi
+	for i in REVISION REVISION_COMMON; do                                                   \
+	    cp -p "$(srcdir)/build-config/$$i" "$(distdir)/build-config/";                      \
+	    if grep -E [A-Z] "$(srcdir)/build-config/$$i" ||                                    \
+                grep "-" "$(srcdir)/build-config/$$i"; then                                     \
+                echo "WARNING: distribution does not match a single, unmodified revision." >&2; \
+            fi                                                                                  \
+        done
 
 doxygen-user-html-compress:
 	if test -d "$(USER_DOC_DIR)/html"; then                               \
@@ -199,8 +204,6 @@ endif # HAVE_DOXYGEN_LATEX -------------------------------------------
 
 else # i.e. ! SVN_CONTROLLED -------------------------------------------------
 
-DOC_SRC_DIR = $(srcdir)/doc
-
 doxygen-user-clean:
 
 doxygen-user-generate:
@@ -209,10 +212,10 @@ doxygen-user-pdf:
 
 doxygen-user-install:
 	if test -f "$(DOC_SRC_DIR)/html.tar.gz"; then                            \
-            $(MKDIR_P) $(DESTDIR)$(pkgdatadir)/doc;                  \
+            $(MKDIR_P) $(DESTDIR)$(docdir);                  \
             $(INSTALL_DATA) $(DOC_SRC_DIR)/html.tar.gz                           \
-                            $(DESTDIR)$(pkgdatadir)/doc/html.tar.gz; \
-	    cd $(DESTDIR)$(pkgdatadir)/doc;                          \
+                            $(DESTDIR)$(docdir)/html.tar.gz; \
+	    cd $(DESTDIR)$(docdir);                          \
             tar xzvf html.tar.gz;                                                \
 	    rm -f html.tar.gz;                                                   \
 	fi
@@ -221,20 +224,19 @@ doxygen-user-install:
             dirs=`find . -type d`;                                                              \
             cd -;                                                                               \
             for i in $$dirs; do                                                                 \
-                $(MKDIR_P) $(DESTDIR)$(pkgdatadir)/doc/$$i;                         \
+                $(MKDIR_P) $(DESTDIR)$(docdir)/$$i;                         \
             done;                                                                               \
 	    cd $(DOC_SRC_DIR);                                                                  \
             files=`find . -type f`;                                                             \
             cd -;                                                                               \
             for i in $$files; do                                                                \
-                $(INSTALL_DATA) $(DOC_SRC_DIR)/$$i $(DESTDIR)$(pkgdatadir)/doc/$$i; \
+                $(INSTALL_DATA) $(DOC_SRC_DIR)/$$i $(DESTDIR)$(docdir)/$$i; \
             done;                                                                               \
-            rm -rf $(DESTDIR)$(pkgdatadir)/doc/doxygen-user;                        \
-            rm -rf $(DESTDIR)$(pkgdatadir)/doc/doxygen-dev;                         \
+            rm -rf $(DESTDIR)$(docdir)/doxygen-user;                        \
+            rm -rf $(DESTDIR)$(docdir)/doxygen-dev;                         \
         fi
 
-doxygen-user-uninstall:
-	rm -rf $(DESTDIR)$(pkgdatadir)/doc
+copy-revision-file-to-dist:
 
 endif # SVN_CONTROLLED 
                                                                              ##
@@ -272,7 +274,7 @@ endif # SVN_CONTROLLED
 
 bitten-copy-tarball-to-prefix: $(distdir).tar.gz
 	$(MKDIR_P) $(DESTDIR)$(prefix)
-	$(INSTALL_DATA) $(distdir).tar.gz $(DESTDIR)$(prefix)/
+	$(INSTALL_DATA) $(distdir).tar.gz $(DESTDIR)$(prefix)/$(PACKAGE)-latest.tar.gz
 
 bitten-print-environment:
 	env
