Fix building with Python on OSX.
For reasons unknown to me, configuring with -python builds TAU as a
Darwin bundle (aka dynamic module) instead of a dynamic library.
Bundles cannot be linked against!  They must be opened with dlopen().
As far as I can tell, you will never want libTAU.so to be a bundle.

If anyone can tell me why libTAU.so should be a bundle I'll reverse
this commit :-)


Former-commit-id: 34e19fef02696ba712a6a178d378cc475669a833

diff --git a/utils/FixMakefile b/utils/FixMakefile
--- a/utils/FixMakefile
+++ b/utils/FixMakefile
@@ -439,6 +439,13 @@ case $1 in
         pythonlib=`echo $1 | sed -e 's/^pythonlib=//'`
 	# Discover python library version
 	pythonso=`ls $pythonlib/libpython*.so | head -1 | xargs basename | sed -e 's/lib//' -e 's/\.so//'`
+	if [ "x$pythonso" = "x" ] ; then
+	  pythonso=`ls $pythonlib/libpython*.dylib | head -1 | xargs basename | sed -e 's/lib//' -e 's/\.dylib//'`
+	  if [ "x$pythonso" = "x" ] ; then
+	    echo "ERROR: Cannot find python library (libpython*.[so|dylib]"
+	    exit 1
+	  fi
+	fi
 	echo "s,^PYTHON_LIBDIR=.*$,PYTHON_LIBDIR=$pythonlib,g" >> $sedout
 	echo "s,^PYTHON_LIB_SO=.*$,PYTHON_LIB_SO=$pythonso,g" >> $sedout
 	#echo "Using PYTHON LIB DIR =" $pythonlib
